### ISSUE TITLE
Proceed to Checkout + PayPal checkout button showing up even when it's the only enabled Gateway

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/woocommerce-gateway-paypal-express-checkout#119]
If PayPal Express is the only enabled payment gateway, we should remove the Proceed to Checkout button from the cart:

![screen shot 2016-05-13 at 2 26 40 pm](https://cloud.githubusercontent.com/assets/3220162/15262365/bb250ed6-1916-11e6-96d6-33397da929cd.png)

The `Proceed to Checkout` button from WooCommerce just takes you to the Checkout page and adds an extra step where there really shouldn't be one.

**Comment by dgadwa** [comment]
> https://gist.github.com/mikejolley/ad2ecc286c9ad6cefbb7065ba6dfef48

Unhooking the button worked nicely.  As a new WC dev, I'm surprised that this issue is still ongoing 2+ years later.  Adding a toggle to the UI would make a lot of sense, IMO.  Either way, thanks for documenting this and for the solution.
