### ISSUE TITLE
When guest checkout disabled user is returned to checkout with an error prompt to fill in password field

### ISSUE THREAD

**Issue by jkohlbach** [woocommerce/woocommerce-gateway-paypal-express-checkout#172]
IF you have the Guest checkout disabled in WooCommerce settings and the user logs into PayPal via the paypal express button on the Cart page, it will drop the user to the checkout page on return complaining that the password field was not set.

https://snag.gy/0jYkHy.jpg

**Comment by jkohlbach** [comment]
Forgot to mention also that automatic generation of user password is turned OFF in this instance.

**Comment by jkohlbach** [comment]
Any movement on this yet? It's really quite a bad problem.

**Comment by gedex** [comment]
I'm looking into this. What's PPEC and WooCommerce versions you're using?

**Comment by jkohlbach** [comment]
Latest of both: 4.6.1 and 2.6.4 respectively.

Thanks for getting onto it.

Based on reports from customers it mainly happens when clicking the button from the Cart page, it then comes back to the Checkout with that error and the password field is missing resulting in an inability to order.

**Comment by jkohlbach** [comment]
Sorry just re-read the comment, I thought you asked for the WP version *doh*

PPEC version is 1.1.2

**Comment by dwainm** [comment]
@gedex  @jkohlbach  with guest checkout enabled by default: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/177 .  How is this issue affected?

**Comment by gedex** [comment]
@jkohlbach could try by pulling `master` branch and see if it fixes the issue?
