### ISSUE TITLE
Feature: Option to disable checkout with PayPal button on Cart page

### ISSUE THREAD

**Issue by jkohlbach** [woocommerce/woocommerce-gateway-paypal-express-checkout#173]
On some sites the cart page is finely tuned to funnel users through to the checkout process via the existing Proceed To Checkout button.

In these cases it might be desirable to disable the checkout with PayPal button on the Cart page altogether since you can still use PayPal express quite effectively from the Checkout page.

**Comment by vestaxpdx** [comment]
+1
