### ISSUE TITLE
Custom fields are not able to be filled in when using PP Express

### ISSUE THREAD

**Issue by slash1andy** [woocommerce/woocommerce-gateway-paypal-express-checkout#175]
Once you select PP Express, go login, etc., then you are unable to fill in/manipulate the custom fields added in via hooks, or a plugin such as https://woocommerce.com/products/woocommerce-checkout-field-editor/

If the field is required, it makes checkout impossible, and if it's not required, it still means the customer misses the fields. 

Re: https://wordpress.org/support/topic/express-checkout-does-not-work-with-woocommerce-checkout-field-edtior-plugin/

**Comment by toddheslin** [comment]
I've got this same issue. Let me know if I can be useful in providing a use-case or debugging. At the moment we have had to turn of the custom field 'Delivery instructions' where the customer nominates to 'leave at front door' or 'signature on delivery'. We can't make it compulsory because it's not showing up for Paypal transactions, however most customers leave it blank meaning that their deliveries often get missed.

**Comment by gedex** [comment]
Adding more steps for buyer to fill fields beats the purpose of "express" checkout. We can provide compatibilities with well known extensions (best if it's under our control). Extensions to consider to be supported may includes:

* CFE as @slash1andy suggested.

@toddheslin Do you use CFE too for delivery instruction?

**Comment by toddheslin** [comment]
I use WooCommerce Checkout Manager. Thanks @gedex

**Comment by meghanni** [comment]
I have the same issue and would really like this to be fixed. Is there a workaround?

**Comment by allendav** [comment]
A ticket was opened 19 days ago for this as well - 496141-zd-woothemes - I've let the user know that this has been added to the 1.2.0 milestone - any ETA on that milestone @gedex ?

**Comment by gedex** [comment]
No ETA yet @allendav, will updated here once we're ready to release.

**Comment by allendav** [comment]
Looking at this now

**Comment by allendav** [comment]
After discussing with the team, we decided that that the express checkout experience really doesn't support the idea of having custom fields and that a more appropriate PayPal gateway should be used in these circumstances instead. It would be better to use PayPal in core or PayPal Pro in these situations.

Closing as no plan to fix.

**Comment by galapogos01** [comment]
Very disappointing outcome.
