### ISSUE TITLE
No shipment costs by paying with this method

### ISSUE THREAD

**Issue by dwainm** [woocommerce/woocommerce-gateway-paypal-express-checkout#179]
https://wordpress.org/support/topic/problem-with-shipment-costs-not-shipment-costs-by-paying-with-paypal-express/page/2/#post-8164524

**Comment by mikejolley** [comment]
@dwainm was there a fix for this?

**Comment by dwainm** [comment]
@mikejolley solution here seems to be not allowing users the use express checkout on the cart page for items that require shipping. I'm not finding a way for this extension to hook into the process and add the shipping details we get from PayPal to `WC()->customer`. The global customer is also used as the main point for figuring out shipping.  What are your thoughts on this?

**Comment by mikejolley** [comment]
@dwainm I don't follow. This isn't needed - the shipping options display when you get back from PayPal. The whole point of express is to bypass our checkout + billing details. This is what I thought the user was reporting as the fault; no methods on return.

cc @roykho

**Comment by dwainm** [comment]
@mikejolley Ther reason fo this is that the user doesn't come back to the checkout page where shipping can be calculated but rather the order review page. This why I thought to only alow carts without the need for shipping to checkout from the cart page.

The only other solution I see is if we embed the shipping calculation on the order review page and recreate the cart object to create the same setup to allow a user to choose shipping options?

**Comment by roykho** [comment]
@dwainm - actually the original design was that they are suppose to see shipping options AFTER they come back from PP and in my test, they do see this when logged in. As guest however, it is intermittent where in my test sometimes they see it sometimes they don't. We need to re-open this.

**Comment by dwainm** [comment]
Ok if it worked like this before then there must be a fix.

**Comment by pawelkmpt** [comment]
This was not included in any release, right? I see last release is 1.1.2 from August 2016 and this was closed in October. When next release is planned? Is it safe to use master branch on production? Client is losing a lot of money on free shipping.
