### ISSUE TITLE
Loading animation to cover the cart page after the user has logged into PayPal

### ISSUE THREAD

**Issue by 6-3-N** [woocommerce/woocommerce-gateway-paypal-express-checkout#180]
From the Cart page, after logging into PayPal with the mini browser popup and continuing, the PayPal window closes and the user sees the Cart page again until being redirected to the Order Confirmation page. The Cart page is visible for a good few seconds, and potentially a lot longer if on a slow mobile network, for example.

So, it would be good to have the loading animation and mask cover the Cart page tables after the user has logged into PayPal and the popup closes, to give some feedback that they are being redirected to the Order Confirmation page.

**Comment by allendav** [comment]
Sorry, no plan to implement this change at this time. Closing this issue.
