### ISSUE TITLE
Sales tax not updating correctly.

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce-gateway-paypal-express-checkout#183]
WooCommerce PayPal Express Checkout Gateway - Version 1.1.2
WooCommerce - Version 2.6.4
- Default Customer Location `Shop base address`
- Set your store with a tax local to your base location (eg. Ohio state tax)
- Calculate Tax Based On `Customer Shipping Address`

Add items to your cart, then click the yellow "Checkout with PayPal" button. In the PayPal checkout window select a shipping address that does not meet the local tax you previously set up (eg. Florida).

**Expected**
The cart's sales tax is updated as no sales tax should be charge for Florida

**Actual**
The cart's sales tax does not update and the Ohio state tax is still shown.

It's important to note that this only happens if the customer's address does not fall under one of the sales taxes that you've set up. If you use an address that falls under a different tax, the cart will update to the proper tax.

**Comment by gedex** [comment]
@FreshPhil Fix in `master` already. Could you please verify?

**Comment by FreshPhil** [comment]
Sorry for the delay @gedex - Tested and confirmed fixed. Thank you!
