### ISSUE TITLE
Shipping address is overwritten, but why?

### ISSUE THREAD

**Issue by kopiro** [woocommerce/woocommerce-gateway-paypal-express-checkout#187]
https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/includes/class-wc-gateway-ppec-checkout-handler.php#L217

Here, the shipping address is overwritten by the Paypal response.
The main question is, why?

If we set the `ADDROVERRIDE` param to `true` (as is), we can discard the address returned by Paypal.

https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/includes/class-wc-gateway-ppec-checkout-handler.php#L530

**Comment by dwainm** [comment]
Hi @kopiro 

Please see discussions on #190 . With how the PayPal Express checkout extension works with WooCommerce, we do not require users to be logged in so we have no guaranteed address when confirming the order. This is the most common case for this plugin.

If you would like to use shipping details in the users WordPress account you should use one of the other PayPal options which we suggest will be more appropriate for this.

**Comment by dwainm** [comment]
Some options for you to consider:
https://woocommerce.com/products/woocommerce-gateway-paypal-powered-by-braintree/
https://woocommerce.com/products/paypal-advanced/

**Comment by kopiro** [comment]
Understood.
But, there is a little "bug" that is very hard to find, and of course it was my case.

I had a "custom checkout field" called "company", but you overwrite it :)

https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/includes/class-wc-gateway-ppec-checkout-handler.php#L148

I deleted that row, and everything fine, but maybe you can call it in another way, maybe `paypal_company`, something like that.

**Comment by dwainm** [comment]
@kopiro renaming the field would require a refactor in other places as well so not something we'd prefer to do now.
