### ISSUE TITLE
[P2][4.4] Add EC button on the product page

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce-gateway-paypal-express-checkout#194]
This enables the merchant to do a one-click checkout from the product page. This is available in the other competitive plugins as well.
## Details
- On gateway setting, provides option (checkbox) to enable this
- On single product page, render the EC button below add to cart secion

**Comment by bor0** [comment]
@mattyza @gedex I am wondering how should the flow be on this one. Should the PayPal popup appear on the product page or should we redirect them to the cart page and then show the popup?
