### ISSUE TITLE
[P2][4.8] Makes EC shortcut button in cart page optional

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce-gateway-paypal-express-checkout#197]
Currently the button appears by default. Merchants want it to be configurable. We need the button to be configurable, and enabled by default in the gateway setting.
## Detail
- Provides option (checkbox) to display EC button on cart page. Enabled by default
- If enabled display EC button on cart page, otherwise don't display EC button on cart page.

Might be dupe of #173

**Comment by gedex** [comment]
Hold this for now.

**Comment by bor0** [comment]
Closing as a duplicate.
