### ISSUE TITLE
Add response handler based on NVP method

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce-gateway-paypal-express-checkout#209]
Currently `includes/class-wc-gateway-ppec-checkout-details.php` so many some classes that basically convert the response from `GetExpressCheckoutDetails` call. This can be simplified into one class that parses the response.

**Comment by thenbrent** [comment]
Closing this as it is now stale, which signals to me that it is not a sufficiently large issue to prioritize over others.

If we see customer facing issues that require this refactoring, then we can reopen.
