### ISSUE TITLE
PayPal doesn't adjust taxes based on actual taxes needed

### ISSUE THREAD

**Issue by slash1andy** [woocommerce/woocommerce-gateway-paypal-express-checkout#226]
If you have the following settings in place, your customers will have taxes calculate for their order based on the shop base, bypassing their shipping address. 

* Taxes all entered and displayed excluding taxes
* A tax rate for a state or a city that is the same as your shop base location
* Default customer location set to shop base location 
* Calculate taxes based on customer shipping address

Then add a taxable product to your cart. Go to the cart page, select the PPE option, it will charge you tax, and not change the charge even once you fill in the shipping details in the actual checkout page. 

Note that you have to either not have a saved shipping address, or be checking out as a guest, as when you are logged in with a saved shipping address, the cart uses that to calculate your totals/taxes. 

![](https://woothemes.zendesk.com/attachments/token/R0R4a8zi1crdCzCPVKyIy2Qgh/?name=2016-12-02_09-46-41.png)

501379-zd-woothemes

@roykho

**Comment by FreshPhil** [comment]
As per #183 this seems to be fixed in master. Should be fixed for the next release?

**Comment by gedex** [comment]
@slash1andy can you confirm with `master` branch?

**Comment by roykho** [comment]
Closing for now due to lack of activity. Please re-open if issue persists.
