### ISSUE TITLE
Unable to create account on checkout page.

### ISSUE THREAD

**Issue by cyrano198** [woocommerce/woocommerce-gateway-paypal-express-checkout#227]
All of our orders require an account with our website, the registration for which is given in WooCommerce within the billing fields. Since this plugin overrides the display of those fields by removing and adding a custom hook to woocommerce_checkout_billing completely, my new users are unable to checkout.

**Comment by roykho** [comment]
Unfortunately perhaps this is not the right plugin for you then because the "Express" means it bypasses all customer facing form fields for a faster checkout. Try using just the regular PayPal Standard that comes with WooCommerce core.
