### ISSUE TITLE
PHP Fatal error: Call to undefined function wc_reduce_stock_levels()

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-paypal-express-checkout#228]
In live chat today, a user reports that they received notification from PayPal that the IPN was failing to deliver the message. The error log indicates this is most likely due to a fatal error resulting from the function call here: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/4a40b5fa3dd46588e80d56d0af33d1761ec22cdc/includes/abstracts/abstract-wc-gateway-ppec-paypal-request-handler.php#L80 - and I can not find a function named `wc_reduce_stock_levels` in WooCommerce 2.6.9

@roykho

**Comment by roykho** [comment]
@gedex - it appears that function no longer exists?

**Comment by gedex** [comment]
@roykho looks like this function is not available in 2.6.x, but available in `master` branch or 2.7. I'll double check this, afaik the IPN handler was copied from PayPal standard IPN handler.

**Comment by gedex** [comment]
So following should be used:

```
$order->reduce_order_stock();
```

instead of:

```
wc_reduce_stock_levels( $order_id );
```

**Comment by LC43** [comment]
and, if you get this in Sept. 2017, the correct function is `wc_reduce_stock_levels( $order->get_id() );`
