### ISSUE TITLE
Implement End to End Tests

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce-gateway-paypal-express-checkout#229]

**Comment by mattallan** [comment]
Closing this issue. Robot Ninja is currently being used to run a suite of end to end tests for PPEC.
These tests currently consist of adding a product to the cart and completing the payment for (support has been added for:
 - smart payment buttons disabled/enabled
 - different paypal landing pages

See PR in Robot Ninja for details: https://github.com/woocommerce/robot-ninja-wall-e/pull/650
