### ISSUE TITLE
When using paypal button on cart page, user account credentials fields (Billing Details) are missing

### ISSUE THREAD

**Issue by jtsternberg** [woocommerce/woocommerce-gateway-paypal-express-checkout#234]
![](http://b.ustin.co/1bZ4V+)

When purchasing a membership product, after logging in/authorizing with paypal, I cannot complete order because the account information, including the password is required, but there is no where to enter new-account details (password, username, etc).

This is specifically when using the express button on the cart page (not when selecting as a gateway on the regular checkout page)

**Comment by jtsternberg** [comment]
This seems similar/related to #233.

**Comment by allendav** [comment]
This seems related to #175 (admittedly not custom fields, but like that issue, after completing paypal's flow, you're unable to get to fields on the checkout form)

**Comment by allendav** [comment]
If registration is required and express checkout is being used, we're thinking of sending them a temp password.

cc @roykho
