### ISSUE TITLE
PayPal sending a mismatch in state format for shipping address

### ISSUE THREAD

**Issue by zandyring** [woocommerce/woocommerce-gateway-paypal-express-checkout#240]
The customer describes: In WooCommerce the state field is a drop down so it will always have the state in a specific format, e.g. Queensland. However whenever someone has their PayPal address as QLD this gets passed back into WooCommerce. This for me is breaking the sync of orders through to my shipping platform as it is expecting it in the WooCommerce format of the state but it’s receiving an unknown format. It also means if you go to edit the shipping address in WooCommerce nothing is selected in the state field so you have to make sure you check the state before editing so you can select it again when editing the shipping address. 

Example image: http://tinypic.com/view.php?pic=21l49og&s=9#.WNVhphLysUE

Ticket ref: 540881

**Comment by allendav** [comment]
@zandyring - good news! I just confirmed this was a bug in 1.1.2 but is working correctly in 1.2.0 and higher.  I noticed the customer is running 1.1.2 and upgrading to 1.2.0 or higher should fix the problem.

**Comment by zandyring** [comment]
Huzzah!
