### ISSUE TITLE
Add Table Rate Shipping support

### ISSUE THREAD

**Issue by danieldudzic** [woocommerce/woocommerce-gateway-paypal-express-checkout#243]
The customer in 553051-zd-woothemes claims, the previous ( paid ) extension ( by SkyVerge ) did support table rate shippings.

Now, with the new ( free ) extension it no longer works.

Is that compatibility something we could consider adding?

> Basically, when customers pay via PayPal Express Checkout it returns users back to the checkout pay to review the order, but WooCommerce can't find a shipping method, we think this is happening because of how PayPal Express is returning the address back to WooCommerce. When trying to order with the regular PayPal Pro checkout option we do not have this issue.

> Note: we used to use the SkyVerge "WooCommerce PayPal Express Gateway" plugin and we never had an issue, but it was retired after the free "WooCommerce PayPal Express Checkout Gateway" plugin came out and we are now having this issue.

**Comment by laurendavissmith** [comment]
Moved to the ideas board
