### ISSUE TITLE
Customer phone number not imported from PayPal account into WooCommerce order

### ISSUE THREAD

**Issue by seanreloaded** [woocommerce/woocommerce-gateway-paypal-express-checkout#246]
Like the subject says, upon successful transaction using PPEC, the customer's phone number in their PayPal account is not added in to the WooCommerce customer info as part of the order billing or shipping addresses.

**Comment by allendav** [comment]
Hey @seanreloaded - PayPal returns a contact phone number only if the Merchant Account Profile settings require that the buyer enter one. Please have the merchant check their Merchant Account Profile settings at PayPal.

I'm having trouble with the PayPal sandbox site today, so I cannot verify this myself at this time unfortunately.

**Comment by allendav** [comment]
See also #254

**Comment by bor0** [comment]
This is not an issue on the extension side. To mimic PayPal phone number behaviour, before [this line](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/1.3.0/includes/class-wc-gateway-ppec-client.php#L204), I added:
`$result['PHONENUM'] = '123456';`.

In this case, the extension captures the phone number:
![screen shot 2017-06-07 at 10 11 12 am](https://user-images.githubusercontent.com/1620929/26868621-eaaeaa1e-4b69-11e7-9d5a-21af528797ae.png)
![screen shot 2017-06-07 at 10 11 59 am](https://user-images.githubusercontent.com/1620929/26868623-ec4f3082-4b69-11e7-9361-5a4e0a51c2b8.png)
