### ISSUE TITLE
Able to checkout without triggering required shipment cost

### ISSUE THREAD

**Issue by zandyring** [woocommerce/woocommerce-gateway-paypal-express-checkout#248]
This follows closely this issue https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/179

With PayPal Express, it's possible to set shipping to be calculated on the cart page, and then bypass that setting entirely, thereby never charging shipping even when required.

Shipping is set to add a $12 flat rate to addresses in California and North Carolina.
![screen shot 2017-04-03 at 2 37 53 pm](https://cloud.githubusercontent.com/assets/7304712/24624996/9ebaf714-187b-11e7-8790-f192b95e1c00.png)
![screen shot 2017-04-03 at 2 37 37 pm](https://cloud.githubusercontent.com/assets/7304712/24625009/ac674980-187b-11e7-89a6-2ce57226bd81.png)

Cart with one item. 
![screen shot 2017-04-03 at 2 33 55 pm](https://cloud.githubusercontent.com/assets/7304712/24624982/894b946a-187b-11e7-948e-836867da6879.png)

If I tap on "calculate shipping" it is correctly calculated:
![screen shot 2017-04-03 at 2 34 57 pm](https://cloud.githubusercontent.com/assets/7304712/24625032/bb886b24-187b-11e7-869a-8a2f473053ee.png)

If I never click on "calculate shipping" and just go through the yellow PayPal button, I (eventually) arrive at this screen after logging into PayPal on the pop-up:
![screen shot 2017-04-03 at 2 40 22 pm](https://cloud.githubusercontent.com/assets/7304712/24625068/cf69561c-187b-11e7-866d-a56373c54b60.png)

The shipping details are a North Carolina address, and are strictly pulled in from PayPal - I didn't enter them on the WooCommerce store at all.

**Comment by bor0** [comment]
Can use an AJAX call to update the cart before showing the popup, as is done similarly in #276. Will wait for that one to get merged before starting work on this one.
