### ISSUE TITLE
If there are no shipping options in WooCommerce, PayPal doesn't pass a shipping address to WC

### ISSUE THREAD

**Issue by zandyring** [woocommerce/woocommerce-gateway-paypal-express-checkout#249]
A customer found that if they didn't enable any shipping options, PayPal wouldn't pass a shipping address back to the Store: https://wordpress.org/support/topic/no-billing-adress-back/page/2/

They needed to set shipping as free, rather than omit shipping altogether, but it's worth considering at some point.

**Comment by allendav** [comment]
Confirmed - will investigate
