### ISSUE TITLE
PP is using an instance of WC Cart without checking it

### ISSUE THREAD

**Issue by just2ronald** [woocommerce/woocommerce-gateway-paypal-express-checkout#255]
I changed the plugin code woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-checkout-handler.php on line 120 from:
  if ( ! WC()->cart->needs_shipping() ) { ..
to this
if ( ! is_null( WC()->cart ) && ! WC()->cart->needs_shipping() ) { ..

This has solved it for me but would need checking by others.
(Credit to Giuseppe from Yith Themes)

**Comment by allendav** [comment]
Hey @just2ronald - under what circumstances does this result in a notice or error?

**Comment by just2ronald** [comment]
This was in combination with a 'customize checkout' plugin from Yith. When this is active I am unable to use the PPxpress option during checkout. Also, this throws an error within the settings page of the plugin. 
Thanks for checking up on this...

**Comment by allendav** [comment]
Hey @just2ronald - do you mind trying this PR to see if this works for you? We are tweaking how we filter those fields just a bit:  https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/258

**Comment by bor0** [comment]
This should be fixed by the PR @allendav mentioned above. `method_exists( WC()->cart, 'needs_shipping' )` will return false if `WC()->cart` is null:
```php
boro@bor0:~/dev/ext/woocommerce-gateway-paypal-express-checkout$ php -r "var_dump( method_exists( null, 'asdf' ) );"
Command line code:1:
bool(false)
```
