### ISSUE TITLE
phpunit.xml in root refers to /tests/phpunit directory which is not available in github

### ISSUE THREAD

**Issue by Jon007** [woocommerce/woocommerce-gateway-paypal-express-checkout#259]
phpunit.xml in root refers to /tests/phpunit directory which is not available in github

can this be added?

**Comment by mattyza** [comment]
Hi @Jon007. Thanks for posting this.

We'll be sure to add unit tests, as part of our unit test update cycle, in due course.

Thanks and regards,
Matty.
