### ISSUE TITLE
Double Stock Reduction

### ISSUE THREAD

**Issue by robyholmes** [woocommerce/woocommerce-gateway-paypal-express-checkout#261]
Hi,

Since we updated to WooCommerce V3 our orders have been running the Reduce Stock action twice. During testing we've found this only happens when customers check out using PayPal Express Checkout.

We are on the latest versions of both.
WooCommerce 3.0.4
PayPal Express Checkout 1.2.1

We are now using PayPal standard which works fine. We tested with all other plugs disabled the found the same issue.

Thank You, Rob Holmes

**Comment by Cocktail5555** [comment]
We are experiencing the same issue. This seems to be a bug in V3
