### ISSUE TITLE
Resend Customer invoice Email - pay link not working

### ISSUE THREAD

**Issue by tmikrut** [woocommerce/woocommerce-gateway-paypal-express-checkout#264]
### EXPLANATION OF THE ISSUE

When sending a customer invoice from Woocommerce order page, the  pay link in the email does not work if Paypal Express Checkout is the only enabled payment method. Error message received is "Sorry, it seems that there are no available payment methods for your location. Please contact us if you require assistance or wish to make alternate arrangements." 

### STEPS TO REPRODUCE THE ISSUE

1. Make sure Paypal Express Checkout is the only enabled payment method. 
2. Select an unpaid order and choose "Resend Customer invoice" in "Order actions". 
3. Click the "pay" link in the email. 
4. In the "pay for order"-page under payment methods you only receive "Sorry, it seems that there are no available payment methods for your location. Please contact us if you require assistance or wish to make alternate arrangements."

### SYSTEM STATUS

<details>
```
Tried on multiple systems, both 2.x and 3.x and it appears on all of them no matter what theme is used or plugins are enabled / disabled.

Plugin: WooCommerce PayPal Express Checkout Gateway
Plugin Version 1.2.1 | By WooCommerce

WC version:		3.0.6
WP version:		4.7.4
WP multisite:		–
WP memory limit:		256 MB
WP debug mode:		
WP cron:		
Language:		en_US
 
Server environment
Server info:		Apache/2.4.18 (Ubuntu)
PHP version:		7.0.15-0ubuntu0.16.04.4
PHP post max size:		8 MB
PHP time limit:		30
PHP max input vars:		1000
cURL version:		7.47.0, OpenSSL/1.0.2g
SUHOSIN installed:		–
MySQL version:		5.7.18
Max upload size:		2 MB
Default timezone is UTC:		

Database
WC database version:		3.0.6

```
</details>

**Comment by bor0** [comment]
@tmikrut, if I enable the `Enable the PayPal Mark on regular checkout` option in the PPEC settings screen, this is no longer an issue.

Can you please confirm?

**Comment by tmikrut** [comment]
@bor0 If I mark "Enable the PayPal Mark on regular checkout" the problem persists.

**Comment by bor0** [comment]
@tmikrut can you please upload some screenshots?

Here's what I get when the option is enabled:
![screen shot 2017-05-24 at 15 00 40 pm](https://cloud.githubusercontent.com/assets/1620929/26404348/dcc8abb2-4091-11e7-9f99-06b4bbc231e7.png)

Otherwise:
![screen shot 2017-05-24 at 15 01 08 pm](https://cloud.githubusercontent.com/assets/1620929/26404349/dd0a0c06-4091-11e7-983c-cdc7595519d0.png)

**Comment by bor0** [comment]
The only conditions we're unsetting `ppec_paypal` from the gateways list is:
1. The cart total is 0 or less
2. PayPal standard is enabled
3. The mark I mentioned above is unchecked

**Comment by tmikrut** [comment]
Please see screenshot below. There's no difference to me if I have the mark checked or not. 
![screenshot_20170524-151845](https://cloud.githubusercontent.com/assets/28725653/26405221/f5778e64-4094-11e7-8460-377cf76479d2.png)

**Comment by bor0** [comment]
@tmikrut do you have other plugins enabled? Or is PayPal standard enabled?

**Comment by tmikrut** [comment]
PayPal standard is disabled. I have other plugins but none for payments. Here are my settings as well. 
![img_20170524_153115](https://cloud.githubusercontent.com/assets/28725653/26405725/7d4dc460-4096-11e7-86a1-64230093b193.jpg)

**Comment by bor0** [comment]
I also tried mobile, with same results. Works when checked:
![test](https://cloud.githubusercontent.com/assets/1620929/26406030/58e95368-4097-11e7-8fb3-70026db74ea6.png)

**Comment by bor0** [comment]
I was finally able to reproduce this. I had an item in the cart, that's why it was always passing the check. Will do a PR soon.

**Comment by bor0** [comment]
@tmikrut thanks for the details on the issue! Could you check if the #266 patch resolves the issue for you?

**Comment by tmikrut** [comment]
Yes, that did the trick! Works like it should now. Thank you! :)
