### ISSUE TITLE
Billing title is a required field

### ISSUE THREAD

**Issue by tapash** [woocommerce/woocommerce-gateway-paypal-express-checkout#271]
After updating the plugin today, I see always 'Billing title is a required field'

how can I solve this?

**Comment by mattyza** [comment]
@tapash - Thanks for asking. 

When filling in the checkout form, I assume you've got a field under Billing which is for the customer's title (Mr. Mrs. etc).

I would assume that this field isn't filled in, which creates this message.

Is this assumption accurate?

Thanks in advance.

**Comment by bor0** [comment]
This message likely comes from core woocommerce instead of PPEC. As @mattyza mentioned above, I believe it's due to that field not being filled in.

**Comment by bor0** [comment]
I think this is related to #239. When I changed the address (by checking out from the cart screen), I got:
![screen shot 2017-06-05 at 11 26 26 am](https://cloud.githubusercontent.com/assets/1620929/26778530/efe19b24-49e1-11e7-9519-8397d415dfa2.png)

**Comment by bor0** [comment]
Ping @tapash.

**Comment by tapash** [comment]
@mattyza thanks
