### ISSUE TITLE
When trying to capture payments, transaction does not process

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce-gateway-paypal-express-checkout#273]
A follow up to #260, ticket is 558730-zd-woothemes

Updated to 1.3.0. When in Live mode and payment action set to Authorize, when admin changes the order status from on-hold to processing/completed or does capture charge order action, the order is not charged.

Transaction ID is still missing.

![](http://cld.wthms.co/fUUFbK+)
Link to screenshot: http://cld.wthms.co/fUUFbK 

@bor0

**Comment by bor0** [comment]
@yukikatayama / @madeincosmos / @mdmoore can you please re-test this against latest master? I believe #274 should also take care of it.

**Comment by yukikatayama** [comment]
@bor0 Sweet! I can confirm that transaction went through when selecting "capture charge" :)

![](https://cloudup.com/cnrpH0QiKF8+)
Link to screenshot: https://cloudup.com/cnrpH0QiKF8

**Comment by bor0** [comment]
@yukikatayama great! In this case I will be closing this issue and it will be included in the 1.4.0 release.
