### ISSUE TITLE
_paypal_status on Authorize transactions not updating to completed after capture

### ISSUE THREAD

**Issue by creativeround** [woocommerce/woocommerce-gateway-paypal-express-checkout#284]
_paypal_status is always "pending".

Is this suppose to update to "completed" after the transaction is captured?

**Comment by bor0** [comment]
@creativeround which version was this tested against?

**Comment by creativeround** [comment]
version 1.4.0

**Comment by bor0** [comment]
@creativeround can you check if the changes on the PR #291 fix the issue for you? Thanks!

**Comment by roykho** [comment]
No this is not how it is suppose to work. Unless the product is virtual/downloadable, the status after capture should be "processing" not "completed". cc @bor0

**Comment by creativeround** [comment]
It actually does move the order to "processing".  This fix works if the status should be "Processing" after capturing.  Is this so a shipping manager can ultimately change it to "Completed" after shipping? @roykho

**Comment by roykho** [comment]
@creativeround - that is correct. If the order is flag completed. The shipping handler would have no idea if shipping has been handled already or not. It serves as a flag for the handler. So capturing the charge should NOT move the status to completed. It should be processing.

However if you do need it to go straight to completed for whatever reason, you can use a plugin like this https://docs.woocommerce.com/document/woocommerce-order-status-control/

**Comment by creativeround** [comment]
Excellent.  I've confirmed this fixed [#291](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/291) is working.

**Comment by creativeround** [comment]
I did notice that when you change the order status to "Cancelled" on an order that is NOT captured, it will create an order note and set the status to "Failed". Is there a way we can set this to "Cancelled". "Failed" is not really a desired status, since the order status selected was "Cancelled".

Order Note:
"Payment voided via IPN. Order status changed from Cancelled to Failed."
