### ISSUE TITLE
NOSHIPPING=0 always.

### ISSUE THREAD

**Issue by smazur** [woocommerce/woocommerce-gateway-paypal-express-checkout#286]
After update to v1.4.0 we got an error from Paypal about wrong shipping address. The product is virtual and doesn't require shipping. I believe that's wrong behavior and needs to be  fixed.

**Comment by smazur** [comment]
Not sure why you did that, but that's wrong.
https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/commit/bbf954acaf8f9cee662783c04e3c84b59e98398c

**Comment by bor0** [comment]
I see how this can cause issues. That change was done because PayPal is not returning a shipping address when NOSHIPPING=1, and if there were no shipping methods defined in WC it wouldn't return an address.
