### ISSUE TITLE
Shipping Address being required on Virtual products

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce-gateway-paypal-express-checkout#288]
Seems related to #256 and possibly #286 ?

595583-zd-woothemes
596667-zd-woothemes
595170-zd-woothemes

**What I Expected**
When selling virtual products, you should be able to checkout without entering a shipping address

**What Happened**
When trying to checkout without entering a shipping address, you get the following error:
![](http://cld.wthms.co/ZgSKQK+)
Image Link: http://cld.wthms.co/ZgSKQK

**Steps To Reproduce**
- Setup a virtual product (downloadle or not, does not matter)
- Remove the requirement for the address fields from your checkout page
- Enter your name and email address
- Make payment attempt
![](http://cld.wthms.co/ksNKhz+)
Image Link: http://cld.wthms.co/ksNKhz

**Comment by bor0** [comment]
@FreshPhil can you please re-test against latest master? If all good I'll release 1.4.1 with that fix included. Thanks!

**Comment by FreshPhil** [comment]
@bor0 - Works for me!

Great job and thanks for the super fast turn around :1st_place_medal:

**Comment by slash1andy** [comment]
@bor0 sorry to reopen this, but the customer from above came back and said it's not working. I can confirm that he's running 1.4.1 and it's still spitting the same error back on checkout.

**Comment by reescott** [comment]
Submitted a pull request to fix this issue, while maintaining a fix to #249.

**Comment by bor0** [comment]
@slash1andy can you please verify the PR #295 to see if it resolves the issue? The code looks good to me.
