### ISSUE TITLE
Not Returning PayPal Transaction Fee

### ISSUE THREAD

**Issue by vzeazy** [woocommerce/woocommerce-gateway-paypal-express-checkout#289]
PayPal standard returns the trasnaction fee and stores it in the order meta.
This plugin appears to have some hint that this should be included as well:

grep -rl "PayPal Transaction Fee"
includes/gateways/paypal/includes/class-wc-gateway-paypal-pdt-handler.php
includes/gateways/paypal/includes/class-wc-gateway-paypal-ipn-handler.php

However, live orders did not have this information saved as expected.

Would love to see this get added.
It actually prevents me from utilizing the plugin, due to how accounting has been setup.

Thanks for the hard work with the plugin.

**Comment by bor0** [comment]
I'm assuming this is due to using `order->update_meta_data` without doing save on it.

@vzeazy can you check the patch on the PR #290 to see if that resolves the issue for you? Thanks!

**Comment by vzeazy** [comment]
Thanks @bor0 

Have applied the patch and still no luck.
Few live orders came in since and neither PayPal Express Checkout or regular PayPal Checkout (using the PPEC plugin) are returning the fee value.

**Comment by bor0** [comment]
@vzeazy in the code, the transaction fee appears only in IPN. Can you confirm your order has the note `IPN payment completed`?

**Comment by vzeazy** [comment]
Hey @bor0 my apologies for not responding sooner.
Thanks for pointing me in right direction, was not sure how IPN funcitoned.
