### ISSUE TITLE
Offer PayPal Credit on Checkout

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/woocommerce-gateway-paypal-express-checkout#292]
Ticket: 595437-zd-woothemes

Currently, plugin only offers PayPal Credit on the cart page, not the checkout. Because of this, customers who use PayPal Credit are not forced to sign up for an account. Even with guest checkout unchecked, customers are sent directly to PayPal Credit and not directed back to sign up for an account.

Please consider adding this feature so our users can take advantage of the PayPal credit option.

This feature is necessary when selling digital and membership based products.

**Comment by priyadilsha** [comment]
it's still not working. even though it mentioned in the changelog.

**Comment by laurendavissmith** [comment]
@bor0 can you retest this one when you get a second?

**Comment by bor0** [comment]
@priyadilsha what is not working? Can you please provide more context?
