### ISSUE TITLE
Bulk Capturing for Orders screen is not working

### ISSUE THREAD

**Issue by creativeround** [woocommerce/woocommerce-gateway-paypal-express-checkout#293]
If you select orders via the orders screen and do a Bulk > Capture Charge is will not capture PayPal Express Checkout Orders.

NOTE:  I'm also using the [Authorize.Net AIM plugin](https://woocommerce.com/products/authorize-net-aim/), this Bulk > Capture Charge functionality might be coming from this plugin.

**Comment by dwainm** [comment]
@creativeround to bulk capture with PayPal Express you can simply select the orders and Bulk mark as processing:

<img width="184" alt="screen shot 2017-06-30 at 12 43 13 pm" src="https://user-images.githubusercontent.com/1713474/27732475-bd2c2c30-5d91-11e7-9de8-71530028048d.png">

Capture Charge will not work as this is not part of this extension.

**Comment by creativeround** [comment]
Anyway we can integrate this on a Authorize.Net plugin detection?  Makes it hard for our customer service team to bulk capture orders if they have to selectively select PayPal Express orders for an separate process.  The Authorize.Net AIM plugin is a very popular plugin, that's why I ask.

**Comment by dwainm** [comment]
@creativeround I'm thinking that we should standardise this across all payment gateways: marking as processed should mean capture. This is the way it is used with Stripe as well.
