### ISSUE TITLE
Add Paypal button on top of checkout page

### ISSUE THREAD

**Issue by jesucarr** [woocommerce/woocommerce-gateway-paypal-express-checkout#296]
I'd like to have a Paypal button on top of the checkout form, as it happens with the Apple Pay button when enabled in the Stripe extension. 

This way the customer will see:
Checkout with Paypal
or
Buy with Apple Pay
or
(checkout form with credit card)

**Comment by mrohnstock** [comment]
Hi,

I would request the same thing, as other payment gateways (i.e. amazon pay) do already do the same:

![image](https://docs.woocommerce.com/wp-content/uploads/2013/08/amazonpay-checkout-banner.png)

an other [paypal payment gateway](https://wordpress.org/plugins/woo-paypalplus/) do the same:

![image](https://user-images.githubusercontent.com/823072/63001119-2901a180-be73-11e9-9b5b-9000c029dffe.png)

Would it be possible to add an option to show the same smart payment buttons as displayed on cart or on selecting the payment gateway paypal on checkout always on top of the checkout page?

Thanks!

**Comment by thenbrent** [comment]
Hi @jesucarr and @mrohnstock. Thanks for requesting this, and apologies for the delayed response. I've opened an _Idea_ for this request here: https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/38621899-add-paypal-checkout-button-above-checkout-page

If it proves popular, we will consider adding it to the roadmap. I've already added 2 votes to the idea. Please go ahead and add your own votes if you still want to see this feature.
