### ISSUE TITLE
Support tokenization to be able to take future payments

### ISSUE THREAD

**Issue by jesucarr** [woocommerce/woocommerce-gateway-paypal-express-checkout#297]
Being able to save the customer token, as it happens with the Stripe extension with "Enable saved cards", so plugins can take future payments just by calling the gateway process_payment function.

**Comment by laurendavissmith** [comment]
Moved to the ideas board for further evaluation

**Comment by jesucarr** [comment]
Where is this ideas board?

**Comment by laurendavissmith** [comment]
@jesucarr my apologies, here is the link to the ideas post: http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/34483696-support-tokenization-to-be-able-to-take-future-pay
