### ISSUE TITLE
Phone not returned and "Require Phone Number" setting not working

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce-gateway-paypal-express-checkout#301]
****Tickets Impacted**
569506-zd-woothemes

****What I expected**
When you've using the "Require Phone Number" option, if no phone number is returned from PayPal then the customer should be required to enter one before placing the order.

****What actually happened**

With "Require Phone Number" enabled and having phone number set as an option field in PayPal
![](http://cld.wthms.co/QR3yaY+)
Image Link: http://cld.wthms.co/QR3yaY

No phone number is requested by PayPal during their portion of the checkout (I'm guessing that's a PayPal issue? Are you able to confirm?):
![](http://cld.wthms.co/0xUrt2+)
Image Link: http://cld.wthms.co/0xUrt2

Then when the user comes back to WooCommerce, the customer is not prompted to enter a phone number, nor is there a place to do so:
![](http://cld.wthms.co/Q3m2Qv+)
Image Link: http://cld.wthms.co/Q3m2Qv

It's important to note that if your PayPal settings set the Phone as a mandatory field, the phone number is passed back normally. This issue only happens if Phone is set as an optional field.

**Comment by bor0** [comment]
@FreshPhil I think those fields are populated on the PP side. Related: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/246#issuecomment-294547752

**Comment by FreshPhil** [comment]
Thanks for clarifying @bor0 - I wasn't sure if this should still get a number from PayPal when using the "optional" setting in their PayPal account.

Still - if no number is returned from PayPal, the customer should be asked for one during PayPal, as per our description of the feature:
![](http://cld.wthms.co/5HahTe+)
Image Link: http://cld.wthms.co/5HahTe

**Comment by bor0** [comment]
@FreshPhil that option only affects WC, not PayPal. This is the effect it has on the code:
`$billing_fields['billing_phone']['required'] = 'yes' === $require_phone_number;`

**Comment by FreshPhil** [comment]
@bor0 sorry for the delayed reply - was on afk.

> that option only affects WC, not PayPal.

Sorry I miss-typed in my last reply. I meant to say that if no phone number is returned from PayPal, the customer should be asked for one during the checkout in WooCommerce.

In my example above, the "Require Phone Number" feature was enabled - yet when a phone number was not returned from PayPal - the customers was still not asked for one during the WooCommerce checkout process.

**Comment by bor0** [comment]
@FreshPhil can you please double-check if the fix for this (#311) works? Thanks!

**Comment by FreshPhil** [comment]
@bor0  confirmed, #311 resolves this. Thanks :)
