### ISSUE TITLE
Refunds not working on authorize then captured transactions

### ISSUE THREAD

**Issue by creativeround** [woocommerce/woocommerce-gateway-paypal-express-checkout#304]
When you capture the charge, PayPal does the capture in a new transaction ID.
The plugin is not updating the previous transaction ID to the new "captured" transaction ID.

When you go to do a refund, it's trying to refund on authorize transaction ID, not the final charge/capture transaction ID.

I manually changed the post_meta "_transaction_id" to the final charge/capture transaction ID and the refund processed.

**Comment by bor0** [comment]
@creativeround can you test if #307 fixes the issue for you? Thanks!

**Comment by randolphengineering** [comment]
This fix did not work.  Error 10011 still happens when refunding an "Authorization" only transaction.
