### ISSUE TITLE
PayPal error (10431): Subtotal Mismatch Behavior Problem

### ISSUE THREAD

**Issue by vestaxpdx** [woocommerce/woocommerce-gateway-paypal-express-checkout#312]
Hi

I am getting this error during checkout:

`PayPal error (10431): An error (10431) occurred while processing your PayPal payment. Please contact the store owner for assistance.`

**Environment**
-  WordPress V4.8.1
-  WooCommerce V3.1.2
-  WooCommerce PayPal Express Checkout Gateway V1.4.3

**Steps to Reproduce**
- Check enter prices inclusive of Tax in WC -> Settings -> Tax -> Tax Options.
- Set UK VAT amount to 20% in WC -> Settings -> Tax -> Standard Rates.
- Add an item worth £70.00 but set sale price as £50.00 to the cart. (Tax Status: Taxable, Tax Class: Standard).
- Add an item worth £730.00 but set sale price as £500.00 to the cart. (Tax Status: Taxable, Tax Class: Standard).
- Click the 'Proceed to checkout' button.
- Select PayPal Express payment option.
- Click the 'Continue to payment' button.
- The error: **PayPal error (10431): An error (10431) occurred while processing your PayPal payment. Please contact the store owner for assistance.** is displayed.

I am still getting this error on random basket amounts despite the possible fix in #310 

This is definitely to do with the option **Subtotal Mismatch Behavior** in WC -> Settings -> Checkout -> PayPal Express Checkout

If I have it set to **Do not send line items to PayPal** the checkout works. However when I try and complete the payment and land back on checkout complete page I get this error.

`Notice: Undefined index: items in /home/element/public_html/beta_site/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-client.php on line 602`

So just having **Do not send line items to PayPal** option on does not help my situation and I think potentially break other things.

I believe I should not have to have do this. It should still work with sending line items to PayPal like normal. 

See below my error log.

```
08-31-2017 @ 07:53:59 - WC_Gateway_PPEC_Client::_request: remote request to https://api-3t.sandbox.paypal.com/nvp with params: Array
(
    [LOGOIMG] => 
    [HDRIMG] => 
    [PAGESTYLE] => 
    [BRANDNAME] => MY_SHOP
    [RETURNURL] => MY_SHOP
    [CANCELURL] => MY_SHOP
    [ADDROVERRIDE] => 1
    [LANDINGPAGE] => Login
    [SOLUTIONTYPE] => Sole
    [PAYMENTREQUEST_0_PAYMENTACTION] => sale
    [PAYMENTREQUEST_0_ALLOWEDPAYMENTMETHOD] => InstantPaymentOnly
    [PAYMENTREQUEST_0_INSURANCEAMT] => 0
    [PAYMENTREQUEST_0_HANDLINGAMT] => 0
    [PAYMENTREQUEST_0_CUSTOM] => 
    [PAYMENTREQUEST_0_INVNUM] => 
    [PAYMENTREQUEST_0_CURRENCYCODE] => GBP
    [PAYMENTREQUEST_0_AMT] => 550
    [PAYMENTREQUEST_0_ITEMAMT] => 458.34
    [PAYMENTREQUEST_0_SHIPPINGAMT] => 0
    [PAYMENTREQUEST_0_TAXAMT] => 91.67
    [PAYMENTREQUEST_0_SHIPDISCAMT] => -0.01
    [NOSHIPPING] => 0
    [PAYMENTREQUEST_0_SHIPTONAME] => Pete Silver
    [PAYMENTREQUEST_0_SHIPTOSTREET] => MY_ADDRESS
    [PAYMENTREQUEST_0_SHIPTOSTREET2] => 
    [PAYMENTREQUEST_0_SHIPTOCITY] => MY_ADDRESS
    [PAYMENTREQUEST_0_SHIPTOSTATE] => MY_ADDRESS
    [PAYMENTREQUEST_0_SHIPTOZIP] => MY_ADDRESS
    [PAYMENTREQUEST_0_SHIPTOCOUNTRYCODE] => GB
    [L_PAYMENTREQUEST_0_NAME0] => F-One Mitu Surf 2016 - 5'10"
    [L_PAYMENTREQUEST_0_DESC0] => 
    [L_PAYMENTREQUEST_0_QTY0] => 1
    [L_PAYMENTREQUEST_0_AMT0] => 416.67
    [L_PAYMENTREQUEST_0_NAME1] => WMFG Kiteboard Pump 2.0T
    [L_PAYMENTREQUEST_0_DESC1] => 
    [L_PAYMENTREQUEST_0_QTY1] => 1
    [L_PAYMENTREQUEST_0_AMT1] => 41.67
    [L_PAYMENTREQUEST_0_NAME2] => Line Item Amount Offset
    [L_PAYMENTREQUEST_0_DESC2] => Adjust cart calculation discrepancy
    [L_PAYMENTREQUEST_0_QTY2] => 1
    [L_PAYMENTREQUEST_0_AMT2] => -5.68434188608E-14   <--- THIS MUST BE THE ISSUE?
    [METHOD] => SetExpressCheckout
    [VERSION] => 120.0
    [USER] => MY_USER
    [PWD] => MY_PASS
    [SIGNATURE] => MY_SIG
)

08-31-2017 @ 07:54:00 - WC_Gateway_PPEC_Client::_process_response: acknowleged response body: Array
(
    [TIMESTAMP] => 2017-08-31T06:54:01Z
    [CORRELATIONID] => 39fb86df16be
    [ACK] => Failure
    [VERSION] => 120.0
    [BUILD] => 000000
    [L_ERRORCODE0] => 10431
    [L_SHORTMESSAGE0] => Transaction refused because of an invalid argument. See additional error messages for details.
    [L_LONGMESSAGE0] => Item amount is invalid.
    [L_SEVERITYCODE0] => Error
)
```

You can see the line **Line Item Amount Offset** has an amount of **-5.68434188608E-14**

Just to note this happens on random basket amounts. Sometimes if I have 3 items in the basket it works or just 2 items and it does not work. It is totally random and luck of the draw with the final basket (line item) amounts that cause this error.

Cheers

**Comment by dheerajsingh2109** [comment]
Hi I am also getting a similar error. Has posted on https://wordpress.org/support/topic/amount-converted-from-xx-90-to-xx-90000000000001/ and was advised to update this ticket. 

On my website somehow some amounts are getting converted from from xx.90 to xx.90000000000001 when clicking on paypal express checkout. 
I have tried setting up the subtotal mismatch behaviour to do not send line items to paypal however that did not solve the issue. 
Interestingly this is happening only in case of a certain combination of products and/or if two products with a price ending in a decimal value 0fxx.95 are added to the cart, 
Here is an extract from the log

`09-05-2017 @ 23:10:35 - WC_Gateway_PPEC_Client::_request: remote request to https://api-3t.paypal.com/nvp with params: Array
(
    [LOGOIMG] => https://interiormantra.com.au/wp-content/uploads/2017/05/logo30may.png
    [HDRIMG] => 
    [PAGESTYLE] => 
    [BRANDNAME] => InteriorMantra
    [RETURNURL] => https://interiormantra.com.au/checkout/?woo-paypal-return=true
    [CANCELURL] => https://interiormantra.com.au/cart/?woo-paypal-cancel=true
    [LANDINGPAGE] => Login
    [SOLUTIONTYPE] => Sole
    [PAYMENTREQUEST_0_PAYMENTACTION] => sale
    [PAYMENTREQUEST_0_ALLOWEDPAYMENTMETHOD] => InstantPaymentOnly
    [PAYMENTREQUEST_0_INSURANCEAMT] => 0
    [PAYMENTREQUEST_0_HANDLINGAMT] => 0
    [PAYMENTREQUEST_0_CUSTOM] => 
    [PAYMENTREQUEST_0_INVNUM] => 
    [PAYMENTREQUEST_0_CURRENCYCODE] => AUD
    [PAYMENTREQUEST_0_AMT] => 69.90000000000001
    [PAYMENTREQUEST_0_ITEMAMT] => 74.90000000000001
    [PAYMENTREQUEST_0_SHIPPINGAMT] => 0
    [PAYMENTREQUEST_0_TAXAMT] => 0
    [PAYMENTREQUEST_0_SHIPDISCAMT] => -5
    [NOSHIPPING] => 0
    [L_PAYMENTREQUEST_0_NAME0] => Artificial Potted White Pansy (28cm - Set of 2)
    [L_PAYMENTREQUEST_0_DESC0] => 

Care Instructions:

 	Easy to care for, this piece can be quickly freshened up with a moist paper towel.

    [L_PAYMENTREQUEST_0_QTY0] => 1
    [L_PAYMENTREQUEST_0_AMT0] => 39.95
    [L_PAYMENTREQUEST_0_NAME1] => Artificial Green Cactus Succulents In Glass Vase (16cm – Set of 3)
    [L_PAYMENTREQUEST_0_DESC1] => 
    [L_PAYMENTREQUEST_0_QTY1] => 1
    [L_PAYMENTREQUEST_0_AMT1] => 34.95
    [L_PAYMENTREQUEST_0_NAME2] => Line Item Amount Offset
    [L_PAYMENTREQUEST_0_DESC2] => Adjust cart calculation discrepancy
    [L_PAYMENTREQUEST_0_QTY2] => 1
    [L_PAYMENTREQUEST_0_AMT2] => 0
    [METHOD] => SetExpressCheckout
    [VERSION] => 120.0
    [USER] => pragz.sri_api1.gmail.com
    [PWD] => W38XUZANDGJLKYTP
    [SIGNATURE] => AFcWxV21C7fd0v3bYYYRCpSSRl31AnaBkj2t5-H2pKXSuxbzuxfBeAjy
)

09-05-2017 @ 23:10:36 - WC_Gateway_PPEC_Client::_process_response: acknowleged response body: Array
(
    [TIMESTAMP] => 2017-09-05T13:10:36Z
    [CORRELATIONID] => 1a824b74876c8
    [ACK] => FailureWithWarning
    [VERSION] => 120.0
    [BUILD] => 38544305
    [L_ERRORCODE0] => 10401
    [L_ERRORCODE1] => 10426
    [L_ERRORCODE2] => 11812
    [L_ERRORCODE3] => 10413
    [L_SHORTMESSAGE0] => Transaction refused because of an invalid argument. See additional error messages for details.
    [L_SHORTMESSAGE1] => Transaction refused because of an invalid argument. See additional error messages for details.
    [L_SHORTMESSAGE2] => Invalid Data
    [L_SHORTMESSAGE3] => Transaction refused because of an invalid argument. See additional error messages for details.
    [L_LONGMESSAGE0] => Order total is invalid.
    [L_LONGMESSAGE1] => Item total is invalid.
    [L_LONGMESSAGE2] => The value of Description parameter has been truncated.
    [L_LONGMESSAGE3] => The totals of the cart item amounts do not match order amounts.
    [L_SEVERITYCODE0] => Error
    [L_SEVERITYCODE1] => Error
    [L_SEVERITYCODE2] => Warning
    [L_SEVERITYCODE3] => Error
)`

Moreover on further analysis we found that if we add any 2 products that have a price of 34.95 each; making the cart value as 69.90 i get the same error.

Please feel free to let me know in case any other details are needed from my end.

Thanks.

**Comment by kristinaplauche** [comment]
@bor0 @mattyza I'm seeing multiple cases of this error as well.

**Comment by Edragon** [comment]
Hi!
I am the one who open tickets at woo commerce, will switch to communicate here:

The option does not help - >
Subtotal Mismatch Behavior and select “Do not send line items to PayPal” . I see yours is set to that
Problem still existed after this.

Thanks.

**Comment by dheerajsingh2109** [comment]
Hi Edragon, 

Yes the problem did not fix even after Subtotal Mismatch Behavior is selected to “Do not send line items to PayPal. 

Thanks 
Dheeraj

**Comment by bor0** [comment]
Since I cannot reproduce this issue (it probably requires a good combination of products and totals), can some of you please try applying this patch and see if it resolves the issue?
```
diff --git a/includes/class-wc-gateway-ppec-client.php b/includes/class-wc-gateway-ppec-client.php
index c831b64..bc0ddb6 100644
--- a/includes/class-wc-gateway-ppec-client.php
+++ b/includes/class-wc-gateway-ppec-client.php
@@ -408,11 +408,13 @@ class WC_Gateway_PPEC_Client {
	 * @return array Line item
	 */
	protected function _get_extra_offset_line_item( $amount ) {
+		$decimals = $settings->get_number_of_decimal_digits();
+
		return array(
			'name'        => 'Line Item Amount Offset',
			'description' => 'Adjust cart calculation discrepancy',
			'quantity'    => 1,
-			'amount'      => $amount,
+			'amount'      => round( $amount, $decimals ),
		);
	}
 
@@ -426,11 +428,13 @@ class WC_Gateway_PPEC_Client {
	 * @return array Line item
	 */
	protected function _get_extra_discount_line_item( $amount ) {
+		$decimals = $settings->get_number_of_decimal_digits();
+
		return  array(
			'name'        => 'Discount',
			'description' => 'Discount Amount',
			'quantity'    => 1,
-			'amount'      => '-' . $amount,
+			'amount'      => '-' . round( $amount, $decimals ),
		);
	}
```

**Comment by justinbrewer** [comment]
I've just encountered a 10431 error on a website I am a customer of (and that I am not otherwise affiliated with). Pressing F12, it's immediately apparent that they use WooCommerce. It's safe to assume it's this issue.

After a short amount of digging, it appears that [the currency values are being stored as floats](https://stackoverflow.com/q/3730019), and those floats are being passed directly to [`wp_safe_remote_post`](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/e93a65af5b6e2754648ead67535b84e36b6d8aef/includes/class-wc-gateway-ppec-client.php#L133) without formatting them in a controlled manner first. Somewhere down that rabbit hole, the floats are eventually formatted automatically, untruncated. This also happens when the log message is being formatted.

I would guess that the solution is to implement the [`woocommerce_paypal_express_checkout_request_body`](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/e93a65af5b6e2754648ead67535b84e36b6d8aef/includes/class-wc-gateway-ppec-client.php#L119) filter, which doesn't seem to exist anywhere. In that filter, format the floats to strings, making sure to properly truncate them.

**Comment by brezocordero** [comment]
Probably related 698122-zd

**Comment by vestaxpdx** [comment]
Hi @bor0

Thanks for this. Sorry I have only just manage to get to testing this.

I can't see how the `$settings` object is accessed in those functions? As expected the patch is throwing a JSON error because of.

`Undefined variable: settings in /MY_SITE_URL/wp-content/plugins
/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-client.php`

**Comment by bor0** [comment]
@vestaxpdx nice catch! We need to initialize it. I updated the patch.

**Comment by vestaxpdx** [comment]
@bor0 cool! I Just updated the patch and it seemed to load PayPal with line items fine for my situation.

Can I ask what is the benefit of sending line items? Is it simply a more detailed better experience view for the customer. Is there any disadvantage to not sending line items etc.

**Comment by bor0** [comment]
AFAIK it is done so that you can see more details about the order from the PP side, so yeah, a better experience view for the customer.

**Comment by vestaxpdx** [comment]
Cool thanks for the info, lets hope this fixes everyone's issue too. 

Does seem like a nightmare this approach. Would be nice is everyone used the same amount of decimals and you didn't have to do all this extra work. :)

**Comment by anemonex** [comment]
Hi all I am also experiencing the 10431 error.

Where do I add the code from 'bor0' please?

Thank you

**Comment by zamson** [comment]
@bor0 patch seem to work for this problem

**Comment by bor0** [comment]
@zamson thank you for verifying. I will do a version release today with this patch included.

**Comment by adamlavery** [comment]
See also [#337](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/337)
