### ISSUE TITLE
With PPEC set as top(default) gateway, it is not automatically selected at Checkout.

### ISSUE THREAD

**Issue by tommyshellberg** [woocommerce/woocommerce-gateway-paypal-express-checkout#313]
Checkout payment methods order:
http://cld.wthms.co/HwPTvq

Result when going to Checkout page:
http://cld.wthms.co/YzGTVP

After modifying the order, I made sure to test in an Incognito window since this needs to be tested with a new session. This works properly for other gateways.

Make Stripe default:
http://cld.wthms.co/tbBxpa

Result:
http://cld.wthms.co/GNKzR2

**Comment by mitraval192** [comment]
it remembers on a session might be causing this issue in the same browser. so, Try the same thing with another user on the new browser or private browser(incognito).

**Comment by tommyshellberg** [comment]
I stated: 

>  I made sure to test in an Incognito window since this needs to be tested with a new session.

**Comment by gedex** [comment]
@tommyshellberg With latest `master` branch of PPEC and WC 3.2-rc, I'm not able to reproduce this. Here's the recording of it:

![ppec-313](https://user-images.githubusercontent.com/78313/31158578-cb14e20a-a8ec-11e7-81ec-f3785b2d5910.gif)

Maybe I missed steps here?

**Comment by thenbrent** [comment]
I can't reproduce this today either. When PayPal Checkout is moved to the top position on the admin screen, the only way I see it displayed below the top position on checkout is if:

* I've chosen a different payment method previously; or
* I didn't click _Save Changes_ at the bottom of the **WooCommerce > Settings > Payments** screen

If anyone is seeing this issue still, please feel free to reopen and ideally provide steps to reproduce.
