### ISSUE TITLE
incompatible with One Page Checkout

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-paypal-express-checkout#316]
Not sure if this belongs here or the opc repo, so starting here. In summary, the PayPal express checkout buttons do not render on a one-page checkout page. See ticket: 695388-zen replicated on a test site as well.

**Comment by dsmithweb** [comment]
Hello! Just checking if there's any update on this.

**Comment by iMazed** [comment]
Adding a ping. Ticket 695388-zd-woothemes has been open and waiting on this since October 21st.

**Comment by stephhjacq** [comment]
@mattyza any updates on this one? thanks

**Comment by mattyza** [comment]
Labeling this as a high priority enhancement, as the checkout screen and One Page Checkout are seen as different screens by WooCommerce, so we'd need to explicitly register this screen as an area where we'd like to show the PayPal buttons.

**Comment by Luminus** [comment]
Hey @mattyza I know this is an enhancement but your last comment indicates that it is a high priority enhancement so I'm erring on the side of pinging for prioritization.

Please let me know if things like this should be treated like other enhancements per [this post](https://woosupport.wordpress.com/2018/01/18/communicating-with-customer-on-bug-fixes/) instead.

**Comment by mattyza** [comment]
@Luminus - I'd treat this per our prioritisation process. This will definitely require some inspection, and shouldn't be closed without a report on what we can do to mitigate this.

I'd like to see the buttons displayed on OPC checkout screens, personally.

I wouldn't put a specific ETA to this, at this stage.

**Comment by jobthomas** [comment]
Another request - 4012504-hc

**Comment by laurendavissmith** [comment]
Moved to the ideas board
