### ISSUE TITLE
Extra line item sent even when do not send line items is set

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce-gateway-paypal-express-checkout#319]
An extra line item is added even when **do not send line items to PayPal** is set.  Is this expected behavior? 

![](http://cld.wthms.co/l3rs6O+)
http://cld.wthms.co/l3rs6O+

![](http://cld.wthms.co/ODfMS2+)
http://cld.wthms.co/ODfMS2

@bor0

**Comment by bor0** [comment]
@mdmoore, can you please try applying this patch and see if the issue re-occurs:
```
diff --git a/includes/class-wc-gateway-ppec-client.php b/includes/class-wc-gateway-ppec-client.php
index 9b43fc2..7e0b081 100644
--- a/includes/class-wc-gateway-ppec-client.php
+++ b/includes/class-wc-gateway-ppec-client.php
@@ -553,7 +553,7 @@ class WC_Gateway_PPEC_Client {
 				// Add line item to make up different between WooCommerce
 				// calculations and PayPal calculations.
 				$diff = round( $details['total_item_amount'] - $rounded_total, $decimals );
-				if ( abs( $diff ) > 0.000001 ) {
+				if ( abs( $diff ) > 0.000001 && 0.0 !== (float) $diff ) {
 					$extra_line_item = $this->_get_extra_offset_line_item( $diff );
 
 					$details['items'][]            = $extra_line_item;
@@ -611,7 +611,7 @@ class WC_Gateway_PPEC_Client {
 			}
 		}
 
-		if ( abs( $lisum ) > 0.000001 ) {
+		if ( abs( $lisum ) > 0.000001 && 0.0 !== (float) $diff ) {
 			$details['items'][] = $this->_get_extra_offset_line_item( $details['total_item_amount'] - $lisum );
 		}
 ```

**Comment by fhaps** [comment]
The same issue has been reported in 718729-zd-woothemes.

Is there any update on the patch?

**Comment by bor0** [comment]
@fhaps does the currently offered patch solve the issue?

**Comment by fhaps** [comment]
@bor0 I just tested the current master branch and unfortunately the issue hasn't been resolved. I'm still getting a "Line Item Amount Offset" included in the PayPal email receipts.

**Comment by breadadams** [comment]
The issue is still in place, `[Pri] Low` doesn't seem like the correct label for this 😬  (although I gather that's due to OP's absense...).

I'm happy to provide test results, I can do so in the morning. Should I give your latest snippet a go @bor0?

**Comment by bor0** [comment]
Yes, please :) thanks!

**Comment by terencenus** [comment]
@bor0 I tested the patch and it works for me
