### ISSUE TITLE
Redirect to PayPal Wallet on 10486 error

### ISSUE THREAD

**Issue by mattyza** [woocommerce/woocommerce-gateway-paypal-express-checkout#320]
When PayPal returns a 10486 "funding decline" error, we should redirect to the PayPal Wallet, so the customer can select an alternate payment type from their PayPal Wallet instead. This is proven to improve conversions for stores who implement this.

From PayPal:

> 1  What is the 10486 processor redirect 

A 10486 decline happens when a buyer tries to use a funding source which is not valid (invalid/maxed out credit card). By redirecting the user back to PayPal to choose an alternate funding source, we are allowing them to recover from a bad funding source and continue with the transaction. The users prefer PayPal, and would rather choose an alternative source from within their existing PayPal Wallet, hence the redirection. 

> 2. Why should partner redirect user back to the PayPal Digital Wallet?

Based on our work with other partners, we have seen that a user who chooses to pay with PayPal generally would prefer to use an alternative payment type from their wallet rather than put their credit card details online.  A user has multiple payment methods setup in the PayPal wallet. So if one doesn’t work, they can choose another one. We have also seen conversion uplift happen when users are redirected to the PayPal wallet. This is a very recommended change from us which would allow  users to have a smoother user experience.

> 3. What is the work required for woo to implement the change

The fix for this is super simple (simple redirect) you just make sure that the user when he/she sees a declines, is redirected to PayPal to choose an alternative source.  Details can be seen here:  https://developer.paypal.com/webapps/developer/docs/classic/express-checkout/ht_ec_fundingfailure10486/

**Comment by ppnsanders** [comment]
Hi,

Here is my summary based on the call today in regards to this issue.

The general flow when a 10486 is encountered is as follows:

1. Consumer adds items to a cart.
2. Consumer proceeds to checkout.
3. Consumer clicks the PayPal Express Checkout button on the cart page.
4. The [create payment](https://developer.paypal.com/docs/api/payments/#payment_create) API call is made and the `token`/`paymentId` is returned.
5. The [In-Context Checkout](https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/) launches.
6. Consumer logs into their PayPal account, reviews information, clicks "Continue".
7. The consumer is returned to the Merchant site.
8. The [payment details](https://developer.paypal.com/docs/api/payments/#payment_get) API call is made and details are returned to the page.
9. The consumer reviews the information, then clicks "Confirm & Pay".
10. The [execute payment](https://developer.paypal.com/docs/api/payments/#payment_execute) API call is made.
11. The Error response of `10486` is returned in the response.

At this point there are various options depending on the experience you would like to provide to the consumer.

*Option 1 (recommended):*

Present the consumer with an Error message, for example: 

```
This transaction could not be completed! Please go back to PayPal and select a different funding option!
```

Show a button or link at this point that re-initiates the In-Context experience via [checkout.js](https://github.com/paypal/paypal-checkout).

Option 2:

Present the error message as in Option 1, but use a full-page redirect.

> Note: This will also require that your return page handles the return data via the URL and not just the `onAuthorize()` callback as you do with [checkout.js](https://github.com/paypal/paypal-checkout).

Please let me know if you have any questions!

Thanks,

-Nate Sanders
Sr. Integration Engineer
PayPal, Inc.
nsanders@paypal.com

**Comment by dechov** [comment]
Closing per above comment (https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/320#issuecomment-400101341): the redirect is already in place.
