### ISSUE TITLE
Gravity Forms Addons + Checkout on Single Product compatabilty

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce-gateway-paypal-express-checkout#321]
If you have Gravity Forms Product Addons attached to a product that adds to the cost, it is not transferred to paypal when using the Checkout on Single Product feature. If the original product cost is $0, you end up with an error.

I haven't tested, but we should also check Product Addons for this same issue.

CC @bor0 

711181-zd-woothemes

**Comment by allendav** [comment]
Due to just one ticket in 2 years, closing this issue as no plan to fix.
