### ISSUE TITLE
A bug about missing paypal session after purchase.

### ISSUE THREAD

**Issue by fenying** [woocommerce/woocommerce-gateway-paypal-express-checkout#322]
WooCommerce: v2.6.2
PPEC Plugin: v1.4.3
WordPress: v4.7

Recently, I have tried using the PPEC plugin in my WP site. However, sometimes it behave strangely. When I click a Contine button in paypal purchase page, it does redirects to the checkout page, but it tells:

```
Your PayPal checkout session has expired. Please check out again.
```

With the debugger, I found it stopping in file [/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-checkout-handler.php (line 392)](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/includes/class-wc-gateway-ppec-checkout-handler.php#L392).

Anyway, the paypal session cannot be expired, because I have cleaned all browser cache and reopened the cart page. Thus, I tried adding breakpoints at many place, and finally found out the reason. Just look at following logs:

- The ok logs:

```
/cart/?wc-ajax=wc_ppec_update_shipping_costs
Paypal Token Missed

/cart/?startcheckout=true
Paypal Token Missed

/cart/?wc-ajax=wc_ppec_update_shipping_costs
WC Session Saved

/cart/?startcheckout=true
WC Session Saved

/checkout/?woo-paypal-return=true&token=EC-xxxxxxxxxxxxx&PayerID=xxxxxxxxxxxxx
Paypal Token Exists

/checkout/?woo-paypal-return=true&token=EC-xxxxxxxxxxxxx&PayerID=xxxxxxxxxxxxx
WC Session Saved

/checkout/?woo-paypal-return=true&token=EC-xxxxxxxxxxxxx&PayerID=xxxxxxxxxxxxx&wc-ajax=update_order_review
Paypal Token Exists

/checkout/?woo-paypal-return=true&token=EC-xxxxxxxxxxxxx&PayerID=xxxxxxxxxxxxx&wc-ajax=update_order_review
WC Session Saved

/checkout/?woo-paypal-return=true&token=EC-xxxxxxxxxxxxx&PayerID=xxxxxxxxxxxxx&wc-ajax=wc_price_based_country_refresh_cart
Paypal Token Exists

/checkout/?woo-paypal-return=true&token=EC-xxxxxxxxxxxxx&PayerID=xxxxxxxxxxxxx&wc-ajax=wc_price_based_country_refresh_cart
WC Session Saved
```

- The bad logs:

```
/cart/?wc-gateway-ppec-clear-session=1&wc-ajax=wc_ppec_update_shipping_costs
Paypal Token Missed

/cart/?startcheckout=true
Paypal Token Missed

/cart/?startcheckout=true
WC Session Saved

/cart/?wc-gateway-ppec-clear-session=1&wc-ajax=wc_ppec_update_shipping_costs
WC Session Saved

/checkout/?woo-paypal-return=true&token=EC-xxxxxxxxxxxxxxx&PayerID=xxxxxxxxxxxxxxx
Paypal Token Missed

/checkout/?woo-paypal-return=true&token=EC-xxxxxxxxxxxxxxx&PayerID=xxxxxxxxxxxxxxx
WC Session Saved

/checkout/?woo-paypal-return=true&token=EC-xxxxxxxxxxxxxxx&PayerID=xxxxxxxxxxxxxxx&wc-ajax=update_order_review
Paypal Token Missed

/checkout/?woo-paypal-return=true&token=EC-xxxxxxxxxxxxxxx&PayerID=xxxxxxxxxxxxxxx&wc-ajax=update_order_review
WC Session Saved

/checkout/?woo-paypal-return=true&token=EC-xxxxxxxxxxxxxxx&PayerID=xxxxxxxxxxxxxxx&wc-ajax=wc_price_based_country_refresh_cart
Paypal Token Missed

/checkout/?woo-paypal-return=true&token=EC-xxxxxxxxxxxxxxx&PayerID=xxxxxxxxxxxxxxx&wc-ajax=wc_price_based_country_refresh_cart
WC Session Saved
```

Here, forget the `wc-gateway-ppec-clear-session=1`, actually it doesn't make effect on this problem.
The key to this problem is that, the order of ending of requests `/cart/?startcheckout=true` and `/cart/?wc-ajax=wc_ppec_update_shipping_costs`. Like this, 

1. The request `/cart/?startcheckout=true` starts, loading a WC session without paypal token.
2. The request `/cart/?wc-ajax=wc_ppec_update_shipping_costs` starts, loading a WC session without paypal token.
3. The request `/cart/?startcheckout=true` creates the paypal token, and then saves it into WC session.
4. The request `/cart/?wc-ajax=wc_ppec_update_shipping_costs` ends, and then saves the WC session without paypal token.
5. Customer purchases with PPEC and then browser redirect itself back to my site.
6. The request `/checkout/?woo-paypal-return=true&token=EC-xxxxxxxxxxxxxxx&PayerID=xxxxxxxxxxxxxxx`  loads a WC session without paypal token, and thus it fails.

**Yes, the WC session with paypal token is covered by a tokenless session.**

That's all.

**Comment by fenying** [comment]
Is it there any plan to fix this bug?

**Comment by carleyaa** [comment]
Any updates on this "session expired" issue? Does it have anything to do with the Avada theme?
