### ISSUE TITLE
Missing address on express checckout

### ISSUE THREAD

**Issue by kenzinghton** [woocommerce/woocommerce-gateway-paypal-express-checkout#327]
Hello, I'm running 1.4.4 and after upgrading to woocommerce 3.0.1 i'm not able to complete a purchase after logging in through paypal express chechout.  (sanbox mode - woocheckout editor enabled)

It returns an error about the address field is missing, even though the shipping address displays correctly on the page.

Any clues ?

Thanks !
![schermata 2017-10-30 alle 17 45 31](https://user-images.githubusercontent.com/33230411/32183666-33af9dde-bd9a-11e7-9576-c83546ae93cd.png)

**Comment by mattyza** [comment]
@kenzinghton - Thanks for posting this. Do you have the billing address fields enabled on your checkout?

**Comment by kenzinghton** [comment]
@mattyza - Thanks for replying,  I found out the issue was generated by a misconfiguration of the [woocommerce checkout editor ](https://theme.co/apex/forum/t/extension-woo-checkout-editor/93 )extension by Themeco. Resetting the plug-in options did the job, just in case anyone else bumps into this.

**Comment by mattyza** [comment]
Thanks for letting us know, @kenzinghton.
