### ISSUE TITLE
MiniCart Widget – Modal Popup not displaying

### ISSUE THREAD

**Issue by terencenus** [woocommerce/woocommerce-gateway-paypal-express-checkout#328]
Recalling the Issue #53,
on desktop when clicking the button on the mini-cart widget, the Paypal In-Context Checkout modal window doesn’t pop up, instead the checkout continues in the same browser window. Instead the modal iFrame should open and a black layer should overlay the website on background, exactly like if the button is pressed on the cart page.

<img width="405" alt="widget" src="https://user-images.githubusercontent.com/32577218/32361278-a65d72b4-c099-11e7-8dc6-0c1a2b978362.png">
<img width="1268" alt="not correct when checkout from widget" src="https://user-images.githubusercontent.com/32577218/32361279-b23da40a-c099-11e7-99e0-461471efdf24.png">

Tested with StoreFront, other themes, WooCommerce 3.2.x and the Official plugin WooCommerce PayPal Express Checkout Gateway 1.4.4.

- I don't know, I suppose there is some condition not passed correctly when calling https://www.paypalobjects.com/api/checkout.js.

- May it be that in 'class-wc-gateway-ppec-cart-handler.php', the priority must be higher?
`add_action( 'woocommerce_widget_shopping_cart_buttons', array( $this, 'display_mini_paypal_button' ), 20 );`

- Or that something can be corrected here:
```
/* Display paypal button on the cart widget*/
	public function display_mini_paypal_button() {

		$gateways = WC()->payment_gateways->get_available_payment_gateways();
		$settings = wc_gateway_ppec()->settings;

		// billing details on checkout page to calculate shipping costs
		if ( ! isset( $gateways['ppec_paypal'] ) || 'no' === $settings->cart_checkout_enabled ) {
			return;
		}
		?>
		<a href="<?php echo esc_url( add_query_arg( array( 'startcheckout' => 'true' ), wc_get_page_permalink( 'cart' ) ) ); ?>" id="woo_pp_ec_button" class="wcppec-cart-widget-button">
			<img src="<?php echo esc_url( 'https://www.paypalobjects.com/webstatic/en_US/i/btn/png/gold-rect-paypalcheckout-26px.png' ); ?>" alt="<?php _e( 'Check out with PayPal', 'woocommerce-gateway-paypal-express-checkout' ); ?>" style="width: auto; height: auto;">
		</a>
		<?php}
```

- Or in wc-gateway-ppec-frontend-in-context-checkout.js
```
	if ( wc_ppec_context.show_modal ) {
		$wc_ppec.init();
	}
```

**Comment by dechov** [comment]
This is supported in 1.6 by Smart Payment Buttons (if enabled), which adds a JS integration to the mini-cart as well:

<img width="231" alt="screen shot 2018-06-01 at 10 09 32 am" src="https://user-images.githubusercontent.com/1867547/40845183-ea9db706-6583-11e8-868d-c0f7f17292f7.png">

(Can close in favor of https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/436, or keep open while Smart Payment Buttons are optional, to track this for merchants who haven't enabled them.)
