### ISSUE TITLE
Make checkout button translatable value

### ISSUE THREAD

**Issue by lindamork** [woocommerce/woocommerce-gateway-paypal-express-checkout#334]
[Forum Ticket ](https://wordpress.org/support/topic/please-enable-translation-for-checkout-button-image/)

We've had a request, as follows:

Please change the following to a translatable value for WPML and other plugins.

`$express_checkout_img_url = apply_filters( 'woocommerce_paypal_express_checkout_button_img_url', sprintf( 'https://www.paypalobjects.com/webstatic/en_US/i/buttons/checkout-logo-%s.png', $settings->button_size ) );`

It’s in file:
`woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-cart-handler.php`

Thank you!

**Comment by tommyshellberg** [comment]
The display_paypal_button() method also has $express_checkout_img_url and would need to be changed.

However, I'm not sure I totally understand the request. Do we want the URL to be changed based on the geographic location of the visitor?

**Comment by LaurenaRehbein** [comment]
We've had another enquiry about this. Even when the site is translated to French, this image retains the English words: 

![http://cld.wthms.co/xKMDri](http://cld.wthms.co/xKMDri+) 

828104-zen

**Comment by ryelle** [comment]
We've had another user write in requesting this be translatable. My reading of the tickets is that the button should be translated using the core translation functions, for both non-english sites and WPML support. 901159-zen

**Comment by tommyshellberg** [comment]
If I'm reading this correctly, the Express Checkout API has a `locale` parameter which will dynamically change the button output to the requested locale language.

https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/customize-button/

<img width="812" alt="screen shot 2018-01-16 at 12 44 23 pm" src="https://user-images.githubusercontent.com/6723003/34987319-050c04f0-fabb-11e7-8715-fcd0501b5a53.png">

**Comment by ryelle** [comment]
This button isn't be generated using that method though, this is just an image link. Switching to that method be a good way to let users have a locale-specific button though 🙂

**Comment by tommyshellberg** [comment]
Yeah, I haven't dug through the entire code but as far as I can tell that image link is only used for the button generated on product pages anyways.

https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/0d757bc133b6d57af4a426373a164311f90fa86a/includes/class-wc-gateway-ppec-cart-handler.php#L130

**Comment by ryelle** [comment]
It's also used on the checkout page:

https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/0d757bc133b6d57af4a426373a164311f90fa86a/includes/class-wc-gateway-ppec-cart-handler.php#L155

**Comment by dechov** [comment]
This is supported in 1.6 by Smart Payment Buttons (if enabled), which accepts a locale. Can close, or keep open while Smart Payment Buttons are optional, to track this for merchants who haven't enabled them.

**Comment by allendav** [comment]
Removing from 1.6.0 milestone as that has shipped. Under consideration for next milestone.

p73Jol-Ug-p2

**Comment by v18** [comment]
Marking this as low. This can be potentially solved by asking users to use Smart Buttons to get a localized button. If that doesn't work, let's add more details about why in this issue.

**Comment by menakas** [comment]
Because the existing payment options are being deprecated in 1.7 in favour of the Smart Payment Buttons, we're preparing stores for this by requesting that they enable the Smart buttons via [this admin notice](https://user-images.githubusercontent.com/8490476/72951133-1ce21e80-3dd9-11ea-9bfa-608f17c3bbfb.png).

I am closign this because stores can enable the Smart buttons for localized checkout buttons. If there are legitimate reasons for not enabling Smart buttons we can reopen and look at fixing it.
