### ISSUE TITLE
Is the plugin compatible with WooCommerce Subscriptions?

### ISSUE THREAD

**Issue by pawelkmpt** [woocommerce/woocommerce-gateway-paypal-express-checkout#338]
We've been using WooCommerce PayPal Express Checkout Payment Gateway on the client site for a long time and today while doing bug research we discovered that it's marked as not compatible with WooCommerce Subscriptions in the following table: https://docs.woocommerce.com/document/paypal-extension-comparison/#section-2

I didn't find any deprecation note in changelog though. Readme says _PayPal Express allows you to securely sell your products and subscriptions online_ and [FAQ](https://docs.woocommerce.com/document/paypal-express-checkout/#section-13) confirms plugin is compatible with Subscriptions.

So it seems it's compatible but the table confused us.

**Comment by mattyza** [comment]
Hi @pawelkmpt. Yes, this gateway supports WooCommerce Subscriptions.

Happy selling!
