### ISSUE TITLE
Percentage Coupon usage causes PayPal error 10413 : The totals of the cart item amounts do not match order amounts

### ISSUE THREAD

**Issue by gateway-davidtouchette** [woocommerce/woocommerce-gateway-paypal-express-checkout#340]
Usage of a percent off coupon causes discrepancy in cart total and user cannot checkout!  We have had to disable PP checkout while our holiday coupons are active.

I have tried updating our staging env to latest WooCommerce (v3.2.5) + WooCommerce PayPal Express Checkout Gateway (v1.4.5) but the issue is exactly the same.

Probable duplicate of #335 

### PROD Details
WordPress v4.8.3
Divi Theme v3.0.41
WooCommerce v3.0.4
Coupon definition: Percentage Discount: 40% all items in shop, unlimited usage, no restrictions

### Reproduction steps
Add coupon as defined above
Add item to cart
Apply coupon code
Click express paypal checkout button
Receive error message

### Logs from STAGING test
11-27-2017 @ 16:17:32 - WC_Gateway_PPEC_Client::_request: remote request to https://api-3t.sandbox.paypal.com/nvp with params: Array
(
    [LOGOIMG] => 
    [HDRIMG] => 
    [PAGESTYLE] => 
    [BRANDNAME] => To Love, Honor and Vacuum
    [RETURNURL] => https://sheilagregoire.staging.wpengine.com/checkout/?woo-paypal-return=true
    [CANCELURL] => https://sheilagregoire.staging.wpengine.com/cart/?woo-paypal-cancel=true
    [LANDINGPAGE] => Login
    [SOLUTIONTYPE] => Sole
    [PAYMENTREQUEST_0_PAYMENTACTION] => sale
    [PAYMENTREQUEST_0_INSURANCEAMT] => 0
    [PAYMENTREQUEST_0_HANDLINGAMT] => 0
    [PAYMENTREQUEST_0_CUSTOM] => 
    [PAYMENTREQUEST_0_INVNUM] => 
    [PAYMENTREQUEST_0_CURRENCYCODE] => USD
    [PAYMENTREQUEST_0_AMT] => 2.99
    [PAYMENTREQUEST_0_ITEMAMT] => 2.99
    [PAYMENTREQUEST_0_SHIPPINGAMT] => 0
    [PAYMENTREQUEST_0_TAXAMT] => 0
    [PAYMENTREQUEST_0_SHIPDISCAMT] => 0
    [NOSHIPPING] => 1
    [L_PAYMENTREQUEST_0_NAME0] => 31 Days--.pdf Version
    [L_PAYMENTREQUEST_0_DESC0] => Do you yearn to feel truly ..
.. Make this the most fun project you'll ever do together as a couple!
    [L_PAYMENTREQUEST_0_QTY0] => 1
    [L_PAYMENTREQUEST_0_AMT0] => 4.99
    [METHOD] => SetExpressCheckout
    [VERSION] => 120.0
    [USER] => david_api1.XXXXX.tld
    [PWD] => XXXXXXX
    [SIGNATURE] => XXXXXX
)

11-27-2017 @ 16:17:41 - WC_Gateway_PPEC_Client::_process_response: acknowleged response body: Array
(
    [TIMESTAMP] => 2017-11-27T21:17:41Z
    [CORRELATIONID] => 27068704591b8
    [ACK] => FailureWithWarning
    [VERSION] => 120.0
    [BUILD] => 40680762
    [L_ERRORCODE0] => 11812
    [L_ERRORCODE1] => 10413
    [L_SHORTMESSAGE0] => Invalid Data
    [L_SHORTMESSAGE1] => Transaction refused because of an invalid argument. See additional error messages for details.
    [L_LONGMESSAGE0] => The value of Description parameter has been truncated.
    [L_LONGMESSAGE1] => The totals of the cart item amounts do not match order amounts.
    [L_SEVERITYCODE0] => Warning
    [L_SEVERITYCODE1] => Error
)

**Comment by DragosMocrii** [comment]
I created a pull request for fixing this issue https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/341
