### ISSUE TITLE
State Field is not required

### ISSUE THREAD

**Issue by dsmithweb** [woocommerce/woocommerce-gateway-paypal-express-checkout#358]
This holds true even if PayPal Express is not the payment gateway used-- if the PayPal Express plugin is active, the State field is no longer required for U.S. customers.

This means that careful customers can e.g. avoid state-based taxes by filling out all the shipping information except the state field and still place an order:

![image](https://user-images.githubusercontent.com/20285748/34233125-2b3d8e90-e5a9-11e7-8401-38506bacef7f.png)

859885-zen

**Comment by isaaclubow** [comment]
The issue title may be misleading: the State field is not required as long as the plugin is active. Setting a "default customer location" helps mitigate but doesn't solve the problem, because one can still submit the field empty even if it were auto-filled to begin with.

**Comment by tommyshellberg** [comment]
@mattyza this is a pretty big deal for PPEC and is probably an easy win, can we take a look at this again?

**Comment by mattyza** [comment]
@laurendavissmith

**Comment by laurendavissmith** [comment]
@tommyshellberg Added to our triage queue to take a look at on Friday

**Comment by roykho** [comment]
There is no definite ETA at this time however after discussion, this may not be too hard to tackle.

**Comment by roykho** [comment]
Closed in favor of #386
