### ISSUE TITLE
Free Products? Option to display either Woo Checkout or PayPal Express Checkout buttons based on cart total?

### ISSUE THREAD

**Issue by raestanton** [woocommerce/woocommerce-gateway-paypal-express-checkout#359]
I want to be able to "sell" free products using PayPal Express Checkout ... works if there are other products with value, but not if only one free product.

Is it possible to display the regular WooCommerce Checkout button *instead* of the PayPal Express Checkout button if cart total equals $0.00?

Thanks
Rae

**Comment by allendav** [comment]
Sorry, no, PayPal does not support $0 checkout. Closing this issue.
