### ISSUE TITLE
Single product button redirects to empty cart

### ISSUE THREAD

**Issue by iMazed** [woocommerce/woocommerce-gateway-paypal-express-checkout#360]
User: 868331-zd-woothemes

Using a vanilla WooCommerce install with no other plugins active and Storefront as the active theme. 

**What I expected**
I expect the PayPal Express button on a single product page to put the product in the cart and direct me to PayPal's checkout. 

**What happened instead**
When clicking on the PayPal Express button when my cart is empty, the PayPal Express button only redirect to an empty cart page. It does not add a new item to my cart. This is confusing for customers.

![paypal-express](https://user-images.githubusercontent.com/3907432/34379434-919463ce-eafb-11e7-8f7b-6397153a8050.gif)

**Site Stats**
PHP 7.0.4
WooCommerce 3.2.6
PayPal Express Checkout 1.5.0

**Comment by Vmadmax** [comment]
Same issue here

**Comment by roykho** [comment]
I am not able to reproduce this. I see this has been opened a long time ago. Please test against master and if issue persists, re-open the issue.
