### ISSUE TITLE
WooCommerce setup wizard yields broken PPEC checkout button by default

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce-gateway-paypal-express-checkout#361]
When enabling this gateway via the WooCommerce (3.2+) setup wizard's "Payment" step, the PPEC settings are initialized with `enabled` set to "yes". This results in the PPEC checkout button rendering in a broken state, since other necessary settings (such as credentials and button size) are missing.

On top of that, the admin notice (prompting the user to connect a PayPal account) doesn't appear (because the `api_username` setting is [unset instead of empty string](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/adb003e7ad933787f201b5de72901f8be636abb8/includes/class-wc-gateway-ppec-plugin.php#L281-L295)). As far as I can tell, the plugin assumes that if "enabled" was set, all other settings must have been initialized, and if not, it yields a broken state with no indication (in wp-admin) of anything being wrong.

To reproduce:
- On a fresh WP instance (e.g. [poopy.life/create](http://poopy.life/create)), install and activate WooCommerce (3.2+)
- In the Setup Wizard:
  - "Store Setup" step: Select a country other than US to ensure the PPEC option ("PayPal") appears
  - "Payment" step: enable "PayPal"
  - Complete wizard
- Products -> Add New, enter a title and price, and "Publish"
- In the Shop, add the product to cart, "View cart", and a broken image appears: <img width="467" src="https://user-images.githubusercontent.com/1867547/34449154-30492612-ecc3-11e7-9096-a9fb9f1c3903.png">
- Click "Check out with PayPal", and an error appears: <img width="1088" src="https://user-images.githubusercontent.com/1867547/34449159-468280a4-ecc3-11e7-835d-d6b401ad3900.png">

I believe this can be addressed by:
- showing the admin notice so that the store owner is made aware of the incomplete setup (which can also be accomplished in the WC wizard itself, if necessary, just by setting api_username to `''`)

...and/or...
- hiding the button until necessary settings are present, but FYI https://github.com/Automattic/woocommerce-services/pull/1254 currently relies on the button appearing even if all credentials (other than "API Subject") are missing, so if the button were to not appear in this case, the PPEC request proxying functionality (implemented in that PR) would need a way to override it

**Comment by dechov** [comment]
As pointed out by @jeffstieler, this could be fixed — to this extent the issue is specific to the WC setup wizard payment screen opt-out — by installing and activating the PPEC plugin but simply not setting `enabled` (except in the new flow in which WCS is installed and requests are proxied: https://github.com/Automattic/woocommerce-services/pull/1254).

We plan to go ahead with that change, at which point this issue can be closed or reprioritized, since there will no longer be a common case in which a broken button shows up due to "enabled" being set outside of the Settings screen.

**Comment by dechov** [comment]
That change (https://github.com/woocommerce/woocommerce/pull/18497) has now been merged and will ship with WooCommerce 3.3.

**Comment by bor0** [comment]
@dechov in that case is this still an issue?

**Comment by dechov** [comment]
@bor0 Nope — as long as actually saving the settings with incomplete credentials (and with `reroute_requests=no`) is expected to show a broken button, which I'm pretty sure it is, then this issue is fixed 👍
