### ISSUE TITLE
wp_enqueue_media called too early

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-gateway-paypal-express-checkout#362]
#### Affected tickets

876228-zen

Quoting the ticket:

> In the 'Pyapal Express Checkout', there is a call to wp_enqueue_media() in /plugins/woocommerce-gateway-paypal-express-checkout/includes/abstractsabstract-wc-gateway-ppec.php. 
> This call is done in an incorrect order. This function should be called from the 'admin_enqueue_scripts' action hook, or later (see wordpress documentation).

> Because of this, I cannot edit the featured image in my products. It is not causing a problem if I have this plugin activated only, but in combination with other plugins it is causing the problem described. 
> Please correct in alignment with the wordpress documentation.

Indeed, the method is called in gateway constructor: 

https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/includes/abstracts/abstract-wc-gateway-ppec.php#L69

**Comment by mikkamp** [comment]
Another ticket where this same conflict was reported: 883255-zen

It does seem that the wp_enqueue_media is being called too early. In WooCommerce it is loaded after the correct hook, see: https://github.com/woocommerce/woocommerce/blob/3.2.6/includes/admin/class-wc-admin-assets.php#L27

**Comment by vyskoczilova** [comment]
Another bug reported here: https://wordpress.org/support/topic/cant-set-featured-image-due-to-this-plugin/#post-9863688

**Comment by pharmak0n** [comment]
Same problem here, I cannot set thumbnails. When I deactivate the plugin thumbnails starts working again. Please fix it, it's impossible to work with this problem

**Comment by madeincosmos** [comment]
Also reported in 906466-zen. When used in combination with WooCommerce POS Pro, product feature images can't be set. Bumping priority to high as it's affecting more customers.

**Comment by stefanduerrenberger** [comment]
Same problem in combination with the WooCommerce Pay for Payment plugin.

**Comment by madeincosmos** [comment]
One more user reporting this in 934426-zen.

**Comment by yukikatayama** [comment]
Checking in to see if there's any movement? Thanks!

**Comment by laurendavissmith** [comment]
@yukikatayama @madeincosmos We have an open PR for it I just need to test it.

https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/392

Also looks like #376 is a dupe of this one

**Comment by amandasjackson** [comment]
@bor0 just wondering about a milestone, thanks

**Comment by bor0** [comment]
Fixed by #392.

**Comment by Luminus** [comment]
@bor0 do we have an ETA for a new release or a milestone for this to be added to? I see that the fix has been merged to master but a new version is yet to be deployed.

**Comment by zwiesman31** [comment]
@bor0: Following up with Luminus' comment. Is there a potential ETA for this yet release yet?

**Comment by bor0** [comment]
I released 1.5.3 today which contains this fix.

**Comment by Luminus** [comment]
Thanks @bor0
