### ISSUE TITLE
woocommerce_cart_calculate_fees action hook runs multiple times on checkout?

### ISSUE THREAD

**Issue by jpat82792** [woocommerce/woocommerce-gateway-paypal-express-checkout#363]
I am curious why the woocommerce_cart_calculate_fees action hook runs multiple times on checkout? This behaviour seems strange to me as the standard paypal gateway and stripe only run it once.

The reason I noticed this behavior is it is causing issues with a fee calculation that depends on data from the $_POST variable. The first running of the woocommerce_cart_calculate_fees shows the fee calculation as it does in the standard paypal gateway and stripe. However the subsequent calls are showing the the value I retrieve from $_POST as null.

I would greatly appreciate any help with this problem. Thanks for your time.

**Comment by dwainm** [comment]
Hi @jpat82792 

Please get in touch with our support team for assistance with this issue:
Public: https://wordpress.org/support/plugin/express-checkout
Premium: https://woocommerce.com/my-account/create-a-ticket/
