### ISSUE TITLE
Instant Payment Notifications sent to the following URL(s) are failing:

### ISSUE THREAD

**Issue by vestaxpdx** [woocommerce/woocommerce-gateway-paypal-express-checkout#368]
Hi

We suddenly starting getting these emails from PayPal.

Instant Payment Notifications sent to the following URL(s) are failing: https://MY_DOMAIN/wc-api/WC_Gateway_PPEC/

Has anyone experienced this issue before? We have not changed any code recently. So it seems odd for it to start happening.

Cheers

**Comment by dwainm** [comment]
Hi @vestaxpdx 

Please get in touch with our support team for assistance with this issue: 
https://woocommerce.com/my-account/create-a-ticket/
