### ISSUE TITLE
Error submitting to PayPal when a header image is set

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce-gateway-paypal-express-checkout#370]
A user wrote in about [this issue](https://www.paypal-community.com/t5/About-Business/Error-Code-10437/td-p/1227076) – users are encountering this error when a header image is set:

> PayPal error (10437): An error (10437) occurred while processing your PayPal payment. Please contact the store owner for assistance.

It looks like the cause is the length of the image string passed to the API, it should be [a max of 127 char long](https://developer.paypal.com/docs/classic/api/errors/#10437), and the string my test site passed along was 152 characters:

```
<img width="150" height="90" src="https://vagrant.local/content/uploads/2018/01/header-150x90.png" class="attachment-thumbnail size-thumbnail" alt="" />
```

**To replicate**

- Set an image as the header image, use a longer filename to make sure you exceed 127 char
- Try to check out using PayPal Express
- See the error – the exact error that was logged on my site was:

```
    [L_ERRORCODE0] => 10437
    [L_SHORTMESSAGE0] => Transaction refused because of an invalid argument. See additional error messages for details.
    [L_LONGMESSAGE0] => cpp-header-image value exceeds maximum allowable length.
    [L_SEVERITYCODE0] => Error
```

901159-zen

**Comment by allendav** [comment]
Closing as only one ticket in roughly two years. No plan to fix.
