### ISSUE TITLE
Typo in activation hook

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce-gateway-paypal-express-checkout#374]
The condition in the activation hook contains a typo (`setings` rather than `settings`) causing the _if_ block to be executed every time:

https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/371ace32b7792fb4aeabb82834106420ac397d62/includes/class-wc-gateway-ppec-plugin.php#L309-L314

Not sure what circumstances the _else_ clause was intended for, so I'm not sure quite how to validate a fix, or what side effects it could possibly have.

**Comment by bor0** [comment]
We initialize settings:
https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/371ace32b7792fb4aeabb82834106420ac397d62/includes/class-wc-gateway-ppec-plugin.php#L340

This check is supposed to prevent from re-initializing.
