### ISSUE TITLE
Order cancel fail (invalid _wpnonce)

### ISSUE THREAD

**Issue by Mapteg34** [woocommerce/woocommerce-gateway-paypal-express-checkout#377]
Duplicate of https://github.com/woocommerce/woocommerce/issues/18638

WC 3.2.3 + WP 4.8.5

Step to reproduce:

    Got to checkout with unauthorized user
    Select paypal express, fill form, continue to paypal site
    On paypal site change "Cancel and return" link

In that case we go back to site, we is authorized, but order not cancelled because cancel_order() not working (_wpnonce check fail).

In debug i see:
wp_create_nonce with action "woocommerce-cancel_order" call with fresh created and authorized user, but wp_get_session_token return empty val, and token created invalid...

**Comment by coderkevin** [comment]
Tried reproducing this issue with sandbox and live account and seems to operate correctly (takes me back to checkout) with no PHP debug or JS console debug appearing.
