### ISSUE TITLE
'Call to a member function get() on null' when exporting orders

### ISSUE THREAD

**Issue by ablears** [woocommerce/woocommerce-gateway-paypal-express-checkout#378]
I use Store Exporter Deluxe to export orders. My exports have started failing with this error:

> Uncaught Error: Call to a member function get() on null in /var/www/zzz/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-checkout-handler.php:706 Stack trace: #0 /var/www/zzz/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/abstracts/abstract-wc-gateway-ppec.php(63): WC_Gateway_PPEC_Checkout_Handler->is_started_from_checkout_page() #1 /var/www/zzz/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-with-paypal.php(12): WC_Gateway_PPEC->__construct() #2 /var/www/zzz/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(105): WC_Gateway_PPEC_With_PayPal->__construct() #3 /var/www/zzz/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(67): WC_Payment_Gateways->init() #4 /var/www/zzz/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(40): WC_Payment_Gateways->__construct() #5 /var/www/zzz/wp-content/plugins/woocommerce/includes/class-woocommerce.php(665): WC_Payment_Gateways::instance() #6 /var/www/zzz/wp-content/plugins/woocommerce-store-exporter-deluxe/includes/order.php(3115): WooCommerce->payment_gateways() #7 /var/www/zzz/wp-content/plugins/woocommerce-store-exporter-deluxe/includes/order.php(3131): woo_ce_get_order_payment_gateways() #8 /var/www/zzz/wp-content/plugins/woocommerce-store-exporter-deluxe/includes/order.php(1737): woo_ce_format_order_payment_gateway('stripe') #9 /var/www/zzz/wp-content/plugins/woocommerce-store-exporter-deluxe/includes/order.php(2169): woo_ce_get_order_data(1361896, 'order', Array, Array) #10 /var/www/zzz/wp-includes/class-wp-hook.php(286): woo_ce_export_dataset_override_order(NULL, 'order') #11 /var/www/zzz/wp-includes/plugin.php(203): WP_Hook->apply_filters(NULL, Array) #12 /var/www/zzz/wp-content/plugins/woocommerce-store-exporter-deluxe/includes/functions.php(1487): in /var/www/zzz/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-checkout-handler.php on line 706

This is with v1.5.1 of this plugin and WordPress 4.9.2.

Perhaps you could use method_exists() to check get() exists before calling it.

**Comment by nicomollet** [comment]
Same problem on other WooCommerce functions:
With `add_filter( 'woocommerce_defer_transactional_emails', '__return_false' );` the cron events have the same PHP fatal error.

**Comment by iljamm** [comment]
having the same issue

`[09-Feb-2018 04:15:04 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /srv/www/projectname/current/web/app/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-checkout-handler.php:704
Stack trace:
#0 /srv/www/projectname/current/web/app/plugins/woocommerce-gateway-paypal-express-checkout/includes/abstracts/abstract-wc-gateway-ppec.php(63): WC_Gateway_PPEC_Checkout_Handler->is_started_from_checkout_page()
#1 /srv/www/projectname/current/web/app/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-with-paypal.php(12): WC_Gateway_PPEC->__construct()
#2 /srv/www/projectname/current/web/app/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-with-paypal-addons.php(10): WC_Gateway_PPEC_With_PayPal->__construct()
#3 /srv/www/projectname/current/web/app/plugins/woocommerce/includes/class-wc-payment-gateways.php(105): WC_Gateway_PPEC_With_PayPal_Addons->__construct()
#4 /srv/www/projectname/current/web/app/plugins/woocommerce/includes/class-wc-payment-gateways.php(67) in /srv/www/innate/current/web/app/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-checkout-handler.php on line 704
`

**Comment by rmuthukrishnan** [comment]
Thank you for this plugin.

I also saw this stack trace.  I am unable to reproduce it. But the fix appears to be check the session. It is not tested as I could not reproduce it. 

[12-Feb-2018 07:15:05 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /var/www/html/efs/wordpress/store/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-checkout-handler.php:704
Stack trace:
#0 /var/www/html/efs/wordpress/store/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/abstracts/abstract-wc-gateway-ppec.php(63): WC_Gateway_PPEC_Checkout_Handler->is_started_from_checkout_page()
#1 /var/www/html/efs/wordpress/store/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-with-paypal.php(12): WC_Gateway_PPEC->__construct()
#2 /var/www/html/efs/wordpress/store/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(105): WC_Gateway_PPEC_With_PayPal->__construct()
#3 /var/www/html/efs/wordpress/store/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(67): WC_Payment_Gateways->init()
#4 /var/www/html/efs/wordpress/store/wp-content/plugins/woocommerce/includes/class-wc-payment-gateway in /var/www/html/efs/wordpress/store/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-checkout-handler.php on line 704

Possible fix:
```
    /**
     * Checks whether buyer checkout from checkout page.
     *
     * @since 1.2.0
     *
     * @return bool Returns true if buyer checkout from checkout page
     */
    public function is_started_from_checkout_page() {
        if (! $this->has_active_session() )
            return true;

        $session = WC()->session->get( 'paypal' );

        return ( ! $session->checkout_completed);
    }
```

**Comment by jrick1229** [comment]
We (Prospress) are receiving this error as well from customers whose renewal orders are not occurring:

`unexpected shutdown: PHP Fatal error Uncaught Error: Call to a member function get() on null in /home/weebox11/public_html/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-checkout-handler.php:704
Stack trace:
#0 /home/weebox11/public_html/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/abstracts/abstract-wc-gateway-ppec.php(63): WC_Gateway_PPEC_Checkout_Handler->is_started_from_checkout_page()
#1 /home/weebox11/public_html/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-with-paypal.php(12): WC_Gateway_PPEC->__construct()
#2 /home/weebox11/public_html/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-with-paypal-addons.php(10): WC_Gateway_PPEC_With_PayPal->__construct()
#3 /home/weebox11/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(105): WC_Gateway_PPEC_With_PayPal_Addons->__construct()
#4 /home/weebox11/public_html/wp-content/plugins/woocommerce/includ in /home/weebox11/public_html/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-checkout-handler.php on line 704`

This seems to affect the checkout process for our renewal orders, regardless of if the PPEC payment gateway is being used. The scheduled actions are all failing when attempting to run.

**Comment by jrick1229** [comment]
We're still getting man tickets rolling in regarding this error, so it seems like it is affecting quite a few sites. We would appreciate urgency on this problem.
