### ISSUE TITLE
Plugin conflict: Product image and post featured image cannot be set

### ISSUE THREAD

**Issue by InoPlugs** [woocommerce/woocommerce-gateway-paypal-express-checkout#380]
Plugin https://github.com/woocommerce/woocommerce-additional-fees

Bug reported by 2 users and can be reproduced when the 2 plugins are active but not when activated seperatly:

- Create a new product
- Publish it
- Click "Set Product Image"
- The media selector popup opens with   **"Featured Image"** instead of "Product image"
- On my install an additional white image appears in the popup already before the ajax media query is started (can be exactly seen when adding a breakpoint in php)
- You can select an existing image
- Saving the image does nothing

Same can be seen on normal post pages

All with the latest version (WC 3.2.6, 1.5.1 and 3.1.2)

I have absolutely no idea what could cause the problen or how to fix it.

Maybe you can help to solve the problem.

**Comment by johndcoy** [comment]
@InoPlugs Thanks for the report. This issue has been fixed from #376  . Closing for now as update ( post today ) or current master fixed the issue.
