### ISSUE TITLE
Slow queries

### ISSUE THREAD

**Issue by ahmed-sigmalux** [woocommerce/woocommerce-gateway-paypal-express-checkout#381]
Per Query Monitor, I'm seeing the following slow queries on every single admin page:

```
SELECT autoload FROM wp_options WHERE option_name = 'wc_gateway_ppce_bootstrap_warning_message' delete_option 0.2785
SELECT autoload FROM wp_options WHERE option_name = 'wc_gateway_ppce_prompt_to_connect'	 delete_option 0.2784
```

Are these queries necessary on every page? Is there any way to disable them?

**Comment by bor0** [comment]
If these queries are slow I think there's a bigger problem with that instance. It's perfectly normal for a WordPress plugin to do queries against `wp_options`.

In any case, you can delete them as follows:

```
remove_action( 'admin_notices', array( wc_gateway_ppec(), 'show_bootstrap_warning' ) );
```
