### ISSUE TITLE
Review step in communication, but skipped

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-paypal-express-checkout#382]
When checking out using PayPal Express, the customer is shown the message: 

`you'll be able to review your order before you can complete your purchase`

Example: 

![PayPal](http://cld.wthms.co/WpPlQ1+)

We've been able to reproduce this on the customer's site, both live and in PayPal sandbox mode, as well as on multiple sandbox sites. 

The customer reached out to PayPal and received the following message back:

```
In case you don't want to show the label "Review your oder before the payment" under the pay button you need to pass in your API call the variable

USERACTION = COMMIT

Please consult as well our guide at this link: 
https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECCustomizing/
```

**Impact choice:**

It's an enhancement, as checkout does work. However, it makes the checkout more jarring and reflects badly on the shop, PayPal, and ultimately WooCommerce for providing incorrect information.

Ticket: zd-921644

**Comment by zwiesman31** [comment]
@bor0: Is there a way we can prioritize this fix?
