### ISSUE TITLE
Woocommerce Subscriptions Support for Switching Payments Failing on $0 order.

### ISSUE THREAD

**Issue by steven-klein** [woocommerce/woocommerce-gateway-paypal-express-checkout#383]
This plugin registers support for woocommerce subscriptions payment method change with the ``subscription_payment_method_change_customer`` flag.  According to [woocommerce subscriptions documentation](https://docs.woocommerce.com/document/subscriptions/develop/payment-gateway-integration/#section-17) just needs to support a $0 initial total.

Im currently expecting switching from one payment method like stripe to paypal express to work, but the PayPal api response is ``This transaction cannot be processed. The amount to be charged is zero.`` resulting in a filed payment method change.

Looking for insight on whether I may have a configuration issue or if this is a known problem.  I'm working on a local hosted site for testing integration with the plugin so I don't have a url to share.

**Comment by allendav** [comment]
Hi @steven-klein - sorry for the long wait on this - the PayPal API this extension uses requires a minimum purchase of $0.01
