### ISSUE TITLE
Products not returned to inventory after order cancelled

### ISSUE THREAD

**Issue by shirokoweb** [woocommerce/woocommerce-gateway-paypal-express-checkout#384]
## Description:
Customers shopping from Android and trying to pay via Paypal

## Issue:
- They are unable finalize transaction on Paypal (either with their ppl account or with CC).
- Transaction times out, basket is abandonned.
- Items from that basket are not returned in inventory.

## Steps to reproduce:
1. Add item to basket (inventory go down from z to y)
2. Try paying using Paypal (Session times out due to unability to pay either with ppl account or CC)
3. Transaction is cancelled, customer abandons his purchase
4. Transaction shows as UNPAID on BO with status cancelled.
5. Inventory doesn't go back from y to z

**Comment by coderkevin** [comment]
I tried reproducing this issue on both the cart PayPal purchase flow and the checkout PayPal purchase flow and couldn't get this to occur. In both cases when I cancelled, I was brought back to the cart/checkout screen respectively as expected.

**Comment by shirokoweb** [comment]
@coderkevin better later than ever. Issue reported on 10 Feb 2018...
I didn't say customer wasn't taken back to cart/checkout.
I Paypal session EXPIRES and customer doesn't take any further action on website (shop), then:

- Transaction shows as UNPAID on BO with status cancelled.
- Inventory doesn't go back from y to z

Can't recall on what WC version issue occurred. It was almost a year back x_x
I noticed this on a product with 1 item in stock while testing from Android phone to make a purchase with invalid CC number and simply closing browser (on mobile).

I then had a look at the BO and found out the product was out of stock.
