### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function load() on  /var/www/html/wp-content/plugins/woocommerce-services/classes/class-wc-connect-paypal-ec.php on line 233

### ISSUE THREAD

**Issue by danass** [woocommerce/woocommerce-gateway-paypal-express-checkout#395]
Starting from a brand new install, i just installed WooCommerce on a fresh wordpress and 
activated paypal. It then crashed.

Notice: Undefined index: ppec_paypal in /var/www/html/wp-content/plugins/woocommerce-services/classes/class-wc-connect-paypal-ec.php on line 223

Notice: Trying to get property of non-object in /var/www/html/wp-content/plugins/woocommerce-services/classes/class-wc-connect-paypal-ec.php on line 225

Warning: Invalid argument supplied for foreach() in /var/www/html/wp-content/plugins/woocommerce-services/classes/class-wc-connect-paypal-ec.php on line 225

Fatal error: Uncaught Error: Call to a member function load() on null in /var/www/html/wp-content/plugins/woocommerce-services/classes/class-wc-connect-paypal-ec.php:233 Stack trace: #0 /var/www/html/wp-content/plugins/woocommerce-services/classes/class-wc-connect-paypal-ec.php(44): WC_Connect_PayPal_EC->initialize_settings() #1 /var/www/html/wp-content/plugins/woocommerce-services/woocommerce-services.php(665): WC_Connect_PayPal_EC->init() #2 /var/www/html/wp-content/plugins/woocommerce-services/woocommerce-services.php(550): WC_Connect_Loader->attach_hooks() #3 /var/www/html/wp-includes/class-wp-hook.php(286): WC_Connect_Loader->after_wc_init('') #4 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #5 /var/www/html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #6 /var/www/html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(486): do_action('woocommerce_ini...') #7 /var/www/html/wp-includes/class-wp-hook.php(286): WooCommerce->init('') #8 /var/www/html/wp-includes/ in /var/www/html/wp-content/plugins/woocommerce-services/classes/class-wc-connect-paypal-ec.php on line 233

**Comment by bor0** [comment]
Not a PPEC issue it seems, linked it to a woocommerce-services one.
