### ISSUE TITLE
PAYMENTSTATUS not checked

### ISSUE THREAD

**Issue by LandiLuca** [woocommerce/woocommerce-gateway-paypal-express-checkout#396]
In your function capture_payment don't check the var PAYMENTSTATUS that comes from PayPal response. 
My scenario:
Checkout type: authorisation and after capture
All works fine, PayPal is well update in authorisation that in capture.
But I've take a look at function caputre_payment in class-wc-gateway-ppec-admind-handler.php because a my script check the post_metavalue _paypal_status (that you save in capture_payment function) and the result is Pending, not completed. But the script not check the $trans_details['PAYMENTSTATUS']

The only error is in is_wp_error( $result ).

My doubt is, what happens if PAYMENTSTATUS is really in 'error', my order status is completed, but I've an error from PayPal response, that is not checked....or is it checked in is_wp_error?

**Comment by bor0** [comment]
We do this check in `is_authorized_only`.
