### ISSUE TITLE
Only enqueue CSS on required pages

### ISSUE THREAD

**Issue by jkohlbach** [woocommerce/woocommerce-gateway-paypal-express-checkout#397]
Currently the front end CSS file is enqueued on all pages. This is overkill and results in another resource request for something that isn't actually used.

**Comment by allendav** [comment]
Good find. Unfortunately, we rely on the CSS being present on most pages (products, checkout, cart, mini-cart, my-account) and will continue to enqueue it broadly. No plan to fix.
