### ISSUE TITLE
Calling payment_gateways() on init action causes issues

### ISSUE THREAD

**Issue by shadimanna** [woocommerce/woocommerce-gateway-paypal-express-checkout#405]
I am the author of the DHL plugin https://wordpress.org/plugins/dhl-for-woocommerce/ and the plugin makes a call to this function, "WC()->payment_gateways()->payment_gateways()", on "init" action.  This conflicts with WooCommerce PayPal Express plugin for some reason (but no other payment gateway plugin) which does not allow featured images to be added in any post type due to this.

Please suggest a fix as this is causing many issues for users of DHL plugin and PayPal Express users.

**Comment by roykho** [comment]
This should have already been fixed in 1.5.3 on this commit https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/commit/eb3edfb2e12e8dae8e2cde365537de1f2da3ed8a Are you on 1.5.3?

**Comment by shadimanna** [comment]
Roy, thank you for the quick response.  I am only see v1.5.1 on WP.org and WC sites, has this been released to the public yet?

**Comment by roykho** [comment]
It should be. But if not, you can download it from master. Or from the release branch.
