### ISSUE TITLE
Single Product:  Quantity being duplicated due to multiple AJAX calls

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/woocommerce-gateway-paypal-express-checkout#408]
Problem:  When you add a product from the single-product page, the quantity is doubled in PayPal.

1. Go to a Single Product
2. Make sure your cart is empty
3. Click "Check out with PayPal"

I add a $5 product:
![screen shot 2018-05-02 at 12 45 25 pm](https://user-images.githubusercontent.com/3220162/39545746-fd329182-4e06-11e8-8144-d7b19dfc0c04.png)
PayPal shows me this:
![screen shot 2018-05-02 at 12 47 57 pm](https://user-images.githubusercontent.com/3220162/39545783-14d890a2-4e07-11e8-90e2-7489c858a1ca.png)

Reason:
There are 2 AJAX calls going on here.  One of them is added here:
https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/985bb5404e8524905c4c04fdf2c505430bf8c7c4/includes/class-wc-gateway-ppec-cart-handler.php#L29

The other one is being fired off in JS here:
https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/assets/js/wc-gateway-ppec-generate-cart.js#L81-L87

If you remove one of those two AJAX calls, the problem is fixed.

**Comment by laurendavissmith** [comment]
@bor0 will you take a look at this, would be good to get this in before our release next week if necessary

**Comment by bor0** [comment]
@mikeyarce can you give #410 a try? Thanks!

**Comment by amandasjackson** [comment]
Another report came in via chat. Moved to 1138351-zen
