### ISSUE TITLE
PayPal express availability in the UK

### ISSUE THREAD

**Issue by spraveenitpro** [woocommerce/woocommerce-gateway-paypal-express-checkout#411]
As per the Product page: https://woocommerce.com/products/woocommerce-gateway-paypal-express-checkout/ credit cards can be accepted only for US based customers: `Accept PayPal Credit (U.S. only): You get paid up front; customers get time to pay..`

Apparently, PayPal has made the express checkout available for UK customers now as per https://www.paypal.com/uk/webapps/mpp/get-started-express-checkout

Any way this can be implemented for the WooCommerce PayPal express extension?

@bor0

**Comment by bor0** [comment]
cc @laurendavissmith. This should be an enhancement, right?

**Comment by laurendavissmith** [comment]
Yeah sounds like this would be an enhancement, just updated the label

**Comment by dsmithweb** [comment]
https://wooteamconnect.wordpress.com/2018/11/16/adding-paypal-credit-support-in-paypal-checkout-for-the-united-kingdom/#comment-2861

More details forthcoming but: 
"essentially a UK merchant needs to get broker license to offer credit in UK, standard threshold for qualification in $10M in annual TPV; which means the merchant should be working with a PayPal account manager they can’t just apply or enable credit like in the US."
