### ISSUE TITLE
"PayPal Express Checkout" option missing from checkout page when "PayPal Credit" is enabled

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce-gateway-paypal-express-checkout#413]
On the checkout page, the "PayPal Express Checkout" payment option only appears if the "Enable PayPal Credit" setting is not checked.

_Edit:_ This only applies when Smart Payment Buttons are disabled.

Disabled | Enabled
-- | --
<img width="340" alt="screen shot 2018-05-16 at 11 01 36 am" src="https://user-images.githubusercontent.com/1867547/40131919-4e75789a-5909-11e8-8e07-3a66924bd6e1.png"> | <img width="342" alt="screen shot 2018-05-16 at 1 01 10 pm" src="https://user-images.githubusercontent.com/1867547/40131925-5133d1ee-5909-11e8-96df-94f6643457d7.png">

_(All available payment methods are shown.)_

This is because the "PayPal Credit" gateway [inherits its `id`](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/includes/class-wc-gateway-ppec-with-paypal-credit.php#L11) from the "PayPal Express Checkout" gateway, at which point it is not unique. Note that at one point in its history, the "PayPal Credit" gateway a) [did have its own ID](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/c614592983f65c18beafa36ddade36abf60a8704/includes/class-wc-gateway-ppec-with-paypal-credit.php#L10), and b) [inherited from an abstract class](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/c614592983f65c18beafa36ddade36abf60a8704/includes/class-wc-gateway-ppec-with-paypal-credit.php#L7) that didn't have its own ID.

**Comment by dechov** [comment]
@laurendavissmith Not by the current WIP, but yes (depending on scoping discussion at bottom of p7bbVw-2vt-p2 and possibly on unknown constraints), an in-context / smart button enhancement to the checkout page would – I believe – replace the gateways with a single gateway option which, when selected, would render the separate options dynamically.

**Comment by dechov** [comment]
I believe this can be fixed by simply setting a different ID – `$this->id = 'ppec_paypal_credit';` – but if not, then we can just consider it fixed by the Smart Payment Buttons update.

**Comment by allendav** [comment]
@dechov - is this still an issue?

**Comment by dechov** [comment]
Yes I believe it's still an issue, but only when Smart Payment Buttons are disabled [clarified above] – as the PayPal Credit gateway class [[code](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/includes/class-wc-gateway-ppec-with-paypal-credit.php)] still doesn't have its own ID.

**Comment by james-allan** [comment]
> Yes I believe it's still an issue, but only when Smart Payment Buttons are disabled

Because the existing payment options are being deprecated in 1.7 in favour of the Smart Payment Buttons, we're preparing stores for this by requesting that they enable the Smart buttons via [this admin notice](https://user-images.githubusercontent.com/8490476/72951133-1ce21e80-3dd9-11ea-9bfa-608f17c3bbfb.png), and this bug only affects non-smart-button-enabled sites, I'm going to close this one.

To fix this issue stores can enable the Smart buttons. If there are legitimate reasons for not enabling Smart buttons we can reopen and look at fixing it. 

For more details and discussion about a possible fix, see this p2 thread: https://wp.me/pb0GrA-nB
