### ISSUE TITLE
Header image not showing at full width

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-paypal-express-checkout#416]
Somewhat related to this issue: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/371

When you set the PayPal header image to an image of 750x90:

![PayPal Settings](http://cld.wthms.co/kBwXCt+)
Full size: http://cld.wthms.co/kBwXCt

It does show up on the PayPal screen, but cropped as if it were the 190x60 image instead.

![PayPal checkout](http://cld.wthms.co/xHFQZB+)
Full size: http://cld.wthms.co/xHFQZB

**Comment by coderkevin** [comment]
I couldn't get the image to show up at the top of the paypal checkout at all, maybe they don't do that anymore or maybe it's a page style issue?

However, on the admin page, it looks like nothing has changed here.

![WooCommerce_settings_‹_paypal-express_—_WordPress](https://user-images.githubusercontent.com/945228/68423071-04ae1c00-0167-11ea-9b1a-44b6f56a33d2.png)

**Comment by v18** [comment]
I'm able to repro this:

<img width="656" alt="Screen Shot 2019-11-12 at 12 19 49 AM" src="https://user-images.githubusercontent.com/11487924/68644197-3a922e00-04e2-11ea-9082-cf91fcebb981.png">
