### ISSUE TITLE
Button shape: change "rect" to "rectangle"

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-paypal-express-checkout#422]
I'm not sure where to find this in the code, so here's a very small issue.  "Rect" should be written full out as "rectangle" in this dropdown:

![Shape](http://cld.wthms.co/F54K1E+)
Full size: http://cld.wthms.co/F54K1E

**Comment by dechov** [comment]
Fixed in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/409/commits/ab3b032f739e54b88ba1922f0983fb46c25c7751 – thanks!
