### ISSUE TITLE
system status report doesn't show update available

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-paypal-express-checkout#431]
in ticket: 1201341-zen we noticed that the user's system status report did not show that an update to PayPal Express Checkout is available. This is reproducible locally.

1. Install PayPal Express Checkout version 1.5.2
2. Plugins screen shows an update available:
![see screen shot](http://cld.wthms.co/LfHvgI+)
3. system status report does not
![see screen shot](http://cld.wthms.co/d155FE+)

We probably need to keep an eye on this after the next release.

**Comment by mikkamp** [comment]
Reported this here as well: https://github.com/woocommerce/woocommerce/issues/20694

**Comment by thenbrent** [comment]
This has been addressed with https://github.com/woocommerce/woocommerce/pull/21073
