### ISSUE TITLE
[GDPR] Fatal error exporting user data when they have PPEC subscriptions

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-gateway-paypal-express-checkout#432]
#### Affected tickets

1243162-zen

#### What I expected

To export all data of my customer, as required by GDPR

#### What happened instead

I'm getting the following error when trying to export the data of a user that has subscriptions:

```
2018-06-27T13:39:00+00:00 CRITICAL Uncaught Error: Call to a member function get_id() on null in /woostore/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-privacy.php:146
Stack trace:
#0 /wordpress/core/4.9.6/wp-admin/includes/ajax-actions.php(4138): WC_Gateway_PPEC_Privacy->subscriptions_data_exporter('maria-buyer@mad...', 1)
#1 /wordpress/core/4.9.6/wp-includes/class-wp-hook.php(286): wp_ajax_wp_privacy_export_personal_data('')
#2 /wordpress/core/4.9.6/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 /wordpress/core/4.9.6/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /wordpress/core/4.9.6/wp-admin/admin-ajax.php(99): do_action('wp_ajax_wp-priv...')
#5 {main}
  thrown
```

Depending on how the server handles fatal errors, there can either be a `Download has failed` message, or `Internal Server Error` shown in the export table:

![Screenshot](http://cld.wthms.co/dirsVE+)
Screenshot: http://cld.wthms.co/dirsVE

#### Steps to reproduce

1. Install & activate WooCommerce Subscriptions
2. Create a subscription product and purchase it with PPEC
3. Go to **Tools > Export personal data** and enter the email address of the user who just purchased the subscription,
4. Click **Download Personal Data** and observe the download has failed.

The problem seems to come from this line - `$order` is not initialised anywhere in this function:

https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/includes/class-wc-gateway-ppec-privacy.php#L146

**Comment by bor0** [comment]
Fixed in #435.
