### ISSUE TITLE
Smart Payment Buttons not working on mobile product pages

### ISSUE THREAD

**Issue by bondimedical3** [woocommerce/woocommerce-gateway-paypal-express-checkout#438]
Steps to reproduce: 
Notes: Bug is only present on mobiles

1. Clear cache in mobile browser 
2. Navigate to a product page with a Smart Payment Button 
3. Click button

What happens:
A second screen opens and begins to load but then abruptly closes.

Expected result: 
Second screen opens redirecting customer to PayPal

Other Notes:
Smart buttons on Cart and Checkout pages of mobile site work correctly.

**Comment by bondimedical3** [comment]
Hi @dechov - I updated to 1.6.1 but the issue is still present. The PayPal page starts to load and then abruptly closes.

**Comment by bondimedical3** [comment]
You are correct in that this bug is not restricted to mobiles but for cases where no session has been created. I tested the desktop version of my website in a incognito window and the PayPal window does not open.

**Comment by dechov** [comment]
@bondimedical3 Thank you for following up. https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/455 is meant to take care of this once and for all. Can you confirm whether 1.6.3 fixes the problem for you?

**Comment by bondimedical3** [comment]
Hello Sir. Yes, it appears to be working correctly now. Thank you for your help.

**Comment by dechov** [comment]
Thanks for verifying @bondimedical3 

Fixed by https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/455
