### ISSUE TITLE
"Smart Payments" allows orders to go through without accepting Terms

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/woocommerce-gateway-paypal-express-checkout#451]
If you enable the "Smart Payment buttons" option in the extension, you can make the payment even if you don't accept the Terms of Service.

![http://cld.wthms.co/JrkBnt](http://cld.wthms.co/JrkBnt+)
Direct link: http://cld.wthms.co/JrkBnt

Tested on a site with only the latest versions of [Storefront](https://woocommerce.com/products/storefront/), [WooCommerce](https://wordpress.org/plugins/woocommerce/) and [PayPal Checkout](https://woocommerce.com/products/woocommerce-gateway-paypal-checkout/) enabled.

This is only an issue when "Smart Payments" is enabled.

Ticket: 1264383-zen

**Comment by yukikatayama** [comment]
1267580-zen reported here as well

**Comment by dechov** [comment]
As far as I could tell, you weren't able to actually complete the payment – just the PayPal portion of it, after which it would show you an error – will be fixed in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/454. (Please correct me if you saw different behavior.)

**Comment by TATIYA** [comment]
Hello
Same thing if a required field is empty you still can make a payment

**Comment by bondimedical3** [comment]
Updated to 1.6.3 today and this issue is still present?

**Comment by TATIYA** [comment]
Yes it still present

**Comment by juliaamosova** [comment]
Hi @dechov pinging you here to see if you can provide an update here. Thanks!

**Comment by madeincosmos** [comment]
Just tested this with 1.6.3 and indeed after confirming the payment with PayPal, I'm taken back to the checkout page with an error on the top:

![Screenshot](http://cld.wthms.co/IngRdo+)
Screenshot: http://cld.wthms.co/IngRdo

Still worth fixing the user flow though, cause it's quite confusing

**Comment by dechov** [comment]
Hi @juliaamosova, @madeincosmos – sorry I had missed the earlier ping – we are working on this in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/475 and it should be merged and released soon.

**Comment by dechov** [comment]
This fix is now in the latest release – thank you all for reporting and for your patience.
