### ISSUE TITLE
API Signature - Can it be used on Multiple Sites?

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/woocommerce-gateway-paypal-express-checkout#452]
If a PayPal user is using the same API Signature on multiple sites, will the signature work for setup?

Multiple users are reporting the "Error: The API credentials you provided are not valid. Please double-check that you entered them correctly and try again." message.

Wanting to clarify if that's an issue with this plugin itself, or a limitation from PayPal's end? Thanks!

cc: @dechov

**Comment by laurendavissmith** [comment]
From the Slack discussion here, https://a8c.slack.com/archives/C0D9EC4H0/p1531328342000431
