### ISSUE TITLE
Make title and description translatable

### ISSUE THREAD

**Issue by hpalma** [woocommerce/woocommerce-gateway-paypal-express-checkout#457]
Both title and description should be translatable.
From i could gather in includes/abstracts/abstract-wc-gateway-ppec.php line 64 and 65 should be:

```
$this->title = __($this->get_option( 'title' ), 'woocommerce-gateway-paypal-express-checkout');
$this->description = __($this->get_option( 'description' ), 'woocommerce-gateway-paypal-express-checkout');
```

and not:

```
$this->title = $this->get_option( 'title' );
$this->description = $this->get_option( 'description' );
```

**Comment by jeffstieler** [comment]
Hello @hpalma.

Can you describe your use case? Are you wanting to display the payment gateway title in multiple languages?

If so, do the [`woocommerce_gateway_title `](https://docs.woocommerce.com/wc-apidocs/source-class-WC_Payment_Gateway.html#259) and [`woocommerce_gateway_description `](https://docs.woocommerce.com/wc-apidocs/source-class-WC_Payment_Gateway.html#268) filters suffice?

**Comment by hpalma** [comment]
Hi @jeffstieler,
thanks for replying.

That's right, i want to display the payment gateway title and description in multiple languages.

Those filter do work, but i see them as an ugly workaround. This is a easy and safe change which, at least in my eyes, makes sense.

**Comment by jeffstieler** [comment]
I really think the filters are the way to go here.

It's [bad practice to translate variable strings](https://developer.wordpress.org/themes/functionality/internationalization/#variables) - the translation system is effectively a direct string substitution mechanism.

In order for your proposal to work, every possible value would need to be part of the all of the language packs. (You'd effectively be passing user input to the translation mechanism)

**Comment by hpalma** [comment]
Ok, fair enough. I'll use the filters.
Thanks for your help.
