### ISSUE TITLE
PayPal button should not display if product in cart is External/Affiliate.

### ISSUE THREAD

**Issue by seanreloaded** [woocommerce/woocommerce-gateway-paypal-express-checkout#460]
I tested this with the current versions of PPEC and WooCommerce. If you have the Checkout on Single Product option enabled in PPEC, and go to the product page that's External/Affiliate, it will let you purchase the product. However, it doesn't purchase THAT product, it seems to purchase the product that's listed first in alphabetical order on the Products page. (In my test it kept purchasing "Album").

**Comment by johndcoy** [comment]
Another request 1512712
