### ISSUE TITLE
checkout.js loaded when not needed.

### ISSUE THREAD

**Issue by geeklore** [woocommerce/woocommerce-gateway-paypal-express-checkout#462]
Even with option unchecked `**Checkout on Single Product** - `https://www.paypalobjects.com/api/checkout.js` is being loaded on every page of the site.

Customer reported this because their users are all on a G3 network and every file loaded counts.

Can we make it so that it's conditionally loaded?

I feel this is more of a question, but making it a bug so it gets some attention.

**Comment by geeklore** [comment]
zen-1319182

**Comment by SiR-DanieL** [comment]
hi @bor0 any idea when you'll be able to look at this? I see this is focus extension this week

**Comment by bor0** [comment]
You need to disable `Smart Payment Buttons` if you want to not load this JS file, as SPB needs it.

**Comment by juliaamosova** [comment]
Pinging @woocommerce/extendables here so this issue can be looked at and triaged.

**Comment by lkraav** [comment]
> You need to disable Smart Payment Buttons if you want to not load this JS file, as SPB needs it (but it looks like it will enqueue anyway for the cart page).

Is it not possible to detect whether there's any SPB-s actually on the page, and only enqueue then?

**Comment by treibalen** [comment]
@woocommerce/extendables pinging as it seems that the previous reply needs dev's attention :)

**Comment by jessepearson** [comment]
@woocommerce/hydra Since this is now yours. It appears that the js files are loaded regardless if they are needed or not, is there any way around this?

**Comment by DanReyLop** [comment]
@jessepearson We've just released version 1.6.5 of the extension, it includes a fix for this issue.
