### ISSUE TITLE
Causes login via WooCommerce MY Account page to fail

### ISSUE THREAD

**Issue by jkenzer** [woocommerce/woocommerce-gateway-paypal-express-checkout#463]
On the previous two versions of WooCommerce (3.4.3 & 3.4.4) and WooCommerce PayPal Checkout Payment Gateway (1.6.1), it won’t allow you to log into your site at /my-account/ (or whatever page you have set to use the [woocommerce_my_account] shortcode).

Disabling the "Use Smart Payment Buttons" option does fix the issue.

I have disabled all my plugins except woocommerce and this plugin to confirm it's not a different plugin causing the conflict. I have also disabled my theme and tried it with the default themes. Same issue.

This is also been reported by quite a few other users here:
https://wordpress.org/support/topic/causes-login-via-woocommerce-account-page-to-fail/#post-10552316

**Comment by dechov** [comment]
Hi @jkenzer – this should be fixed in the 1.6.3 release. Please re-open if you find it to still be an issue.

**Comment by jkenzer** [comment]
Thanks.
