### ISSUE TITLE
When selecting pay pal express as payment method order details are not passed correctly

### ISSUE THREAD

**Issue by leomano** [woocommerce/woocommerce-gateway-paypal-express-checkout#465]
When using the Paypal express tool, not all information is received correctly from Paypal, for example billing Title (Mr or Mrs), and the user doesn't have the option to enter it with the consequence that the purchase can not be finished.

The issue happens when using both a PC or a Mobile phone

![whatsapp image 2018-08-13 at 16 51 18](https://user-images.githubusercontent.com/36211971/44039614-becef976-9f19-11e8-93e8-04f977534bd5.jpeg)
![whatsapp image 2018-08-06 at 17 51 08](https://user-images.githubusercontent.com/36211971/44039616-befe6026-9f19-11e8-8c23-8dead4f6bd6d.jpeg)

**Comment by allendav** [comment]
Unable to reproduce. What WooCommerce required fields were/are missing when this happens for you?
