### ISSUE TITLE
With require Product Addons, can checkout from product page without selecting the required addons

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce-gateway-paypal-express-checkout#467]
1350691-zen

Tested this on 2.1.3 and Product Addons 2.9.6

Whether it is with Smart Payments button or not, if you have a required field in Product Addons on product and if you do not select/enter info for the required field and checkout via product page, no error messaging shows:

![](http://cld.wthms.co/Iuiqha+)
Link to screenshot: http://cld.wthms.co/Iuiqha

Would expect to have similar behavior as if selecting Add to Cart button:

![](http://cld.wthms.co/PqxvWr+)
Link to screenshot: http://cld.wthms.co/PqxvWr

**Comment by taoball** [comment]
We have experienced the same issue.  Customers can checkout without filling in product options.
