### ISSUE TITLE
Define the default country in PayPal Guest Checkout

### ISSUE THREAD

**Issue by johndcoy-zz** [woocommerce/woocommerce-gateway-paypal-express-checkout#468]
Currently, the country within PayPal Guest Checkout is determined by the Site Language under **Settings > General** in the WP Admin. ( [#](http://cld.wthms.co/ThEoxW) )

Ideally, it would be best for language to be based on Store Address under **WooCommerce > Settings > General** or defined within the PayPal Checkout settings page.

**Comment by KoolPal** [comment]
I disagree. It should select the country from the order checkout customer's country.

**Comment by aalkz** [comment]
I have an installation with es-mx (es_MX) set as locale, and it still defaults to en_US when clicking the PayPal buttons. I agree that this should be an explicit option for the admin to choose separately , as I would like Spanish  + Mexico to be de default combination for my users.

**Comment by xuechaow** [comment]
+1

**Comment by strarsis** [comment]
A preferred language/language fallback plugin could also be used https://wordpress.org/plugins/preferred-languages/ - though it doesn't support this plugin yet.

**Comment by strarsis** [comment]
This PR (https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/624) adds mapping for some WordPress locales to PayPal locales, like locales with `_formal`.
The current WordPress locales are listed here: https://make.wordpress.org/polyglots/teams/
The current PayPal locales are listed here: https://developer.paypal.com/docs/api/reference/locale-codes/#supported-locale-codes

**Comment by menakas** [comment]
There are two issues here: One is the locale code, which determines the language and the other is the default country. For the locale, please track progress at #658 and for the default country, please track progress at #611
