### ISSUE TITLE
Venmo missing as a payment option while cookied

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce-gateway-paypal-express-checkout#471]
Using [Smart Payment Buttons](https://developer.paypal.com/docs/checkout/#smart-payment-buttons), Venmo does not show as a payment option while cookied in Venmo.

![Screenshot](http://cld.wthms.co/42Zhy3+)
Image Link: http://cld.wthms.co/42Zhy3

I also tested on Android while logged into the Venmo app. The Venmo option does not show.

**Comment by EGS2** [comment]
Hi John!  This isn't a bug in the plugin.  I had also asked on WooCommerce.  Joel Williams showed me how the Venmo App has to be connected to browsers (enable mobile purchases on my Android app).  Once I did that, the Venmo button appeared.

You can see his full explanation on ticket ID 1382171

**Comment by johndcoy** [comment]
Closed due to improper Venmo setup.
