### ISSUE TITLE
Save live and sandbox environment credentials separately

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce-gateway-paypal-express-checkout#472]
Currently, the API for Live and Sandbox setting under **WooCommerce > Settings >Payments > PayPal Checkout > Environment** share the same credentials after the fields have been verified.

It would be beneficial to easily toggle between Live and Staging without having to login into PayPal to obtain credentials each time a switch is made.

**Comment by dechov** [comment]
I can't seem to reproduce a scenario in which they share the same credentials:

![paypal-credentials-not-shared-between-environments](https://user-images.githubusercontent.com/1867547/44920891-126c4400-ad0f-11e8-8da5-744185443c68.gif)

After linking a Sandbox account, the Live credentials are untouched and can be restored just be switching the environment back. Are you seeing a different behavior?

**Comment by johndcoy** [comment]
I swear I replicated something different. Likely cache, closing
