### ISSUE TITLE
Add de_De_formal to locale list

### ISSUE THREAD

**Issue by johndcoy-zz** [woocommerce/woocommerce-gateway-paypal-express-checkout#480]
Currently de_De formal is missing from the supported locales

https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/1ef80595138d580c41b2deefe6f6d597196e3757/includes/class-wc-gateway-ppec-settings.php#L24

Could we specify that de_De should be used for PayPal when de_DE_formal is used?

**Comment by AndBaetz** [comment]
I got the same problem. It took me ages to figure out why all PayPal buttons show English... please fix this!

@johndcoy - did you find any workaround? Thx in advance.

**Comment by strarsis** [comment]
PayPal doesn't differentiate between non-formal and formal variations, it only got the `de_DE` locale, see https://developer.paypal.com/docs/api/reference/locale-codes/#supported-locale-codes.
Hence the solution to this issue would be to map some locales, notably the ones that end with `formal` to the ones PayPall supports.

This also seems to be an use case for https://wordpress.org/plugins/preferred-languages/,
but it doesn't support the plugin yet.

**Comment by strarsis** [comment]
This PR (https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/624) adds mapping for some WordPress locales to PayPal locales, like locales with `_formal`.
The current WordPress locales are listed here: https://make.wordpress.org/polyglots/teams/
The current PayPal locales are listed here: https://developer.paypal.com/docs/api/reference/locale-codes/#supported-locale-codes

**Comment by AndBaetz** [comment]
I do not know why it is so hard to have a mapping for "_formal" here. This issue was opened 1,5 years ago and it is still missing.

The problem is that withouth the mapping there are one-click buttons for that specific country in the cart missing...

Instead of fixing this first let us talk about all the other languages that are in the world - maybe we can add them too? (#658)

**Comment by LCmry** [comment]
See #658
