### ISSUE TITLE
Add missing translation for two strings

### ISSUE THREAD

**Issue by johndcoy-zz** [woocommerce/woocommerce-gateway-paypal-express-checkout#484]
The text `Create an account?` is missing a translation string on the order confirmation page.

https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/8b78661276f7ee3b8b6eb27a7e9d1f83f28416d3/includes/class-wc-gateway-ppec-checkout-handler.php#L296

http://cld.wthms.co/g44J0d

Same for line 305 containing `Create an account by entering the information below. If you are a returning customer please login at the top of the page.`

https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/1e0997a591ff3fedf2fdadfc6f9335b51b665226/includes/class-wc-gateway-ppec-checkout-handler.php#L305

**Comment by menakas** [comment]
Via #610
