### ISSUE TITLE
Confusing calculation of coupon code on PayPal order confirmation

### ISSUE THREAD

**Issue by vivulazi** [woocommerce/woocommerce-gateway-paypal-express-checkout#485]
The coupon discount is first added on PayPal once and than subtracted twice. This is confusing.

Order
![woocommerce_20181004_order](https://user-images.githubusercontent.com/43813858/46462047-a0c95f00-c7c0-11e8-9964-6a1fb5e9e3fc.PNG)

PayPal confirmation
![woocommerce_20181004_paypal](https://user-images.githubusercontent.com/43813858/46462075-b474c580-c7c0-11e8-9695-3e7e339e5a1d.PNG)

Woocommerce 3.4.5
WooCommerce PayPal Checkout Gateway 1.6.4

**Comment by FritzHerbers** [comment]
We did a Halloween sale with about 15% off today and got every time a shock when I saw the PayPal Payments with about 30% off.
Hope this gets fixed soon, as other sales are planned this year.

**Comment by FreshPhil** [comment]
2455805-zen as well

![Screen Shot 2019-10-29 at 14 49 15](https://user-images.githubusercontent.com/20049225/67799206-55cd5a00-fa5b-11e9-8176-4ced02884306.png)
![Screen Shot 2019-10-29 at 14 48 51](https://user-images.githubusercontent.com/20049225/67799208-55cd5a00-fa5b-11e9-8030-68da6b6497a8.png)

**Comment by menakas** [comment]
via #677
