### ISSUE TITLE
Shipping costs are not sent over to PayPal 

### ISSUE THREAD

**Issue by fhaps** [woocommerce/woocommerce-gateway-paypal-express-checkout#486]
On the checkout page, shipping costs are calculated correctly. But when you proceed to make the payment in PayPal, the total there does not include shipping costs.

It includes Product Price + Tax, but it doesn't add the shipping costs.

![](http://cld.wthms.co/KjfeOR+)
Image Link: http://cld.wthms.co/KjfeOR

Some numbers above might be hard to see, so here's a clearer screenshot of the shipping costs plus order total:

![](http://cld.wthms.co/aJHVi9+)
Image Link: http://cld.wthms.co/aJHVi9

Tested this on both AT and self-hosted.

Affecting 1484712-zed.

**Comment by mcaiazzo23** [comment]
Having the same issue. Temporary fix was commenting this filter out

`add_filter( 'woocommerce_cart_needs_shipping', '__return_false' );`

on line 129 of /includes/class-wc-gateway-ppec-cart-handler.php

**Comment by fhaps** [comment]
**New findings:** The issue appears when the `Smart Payment Buttons` are enabled. If these are disabled, the issue is gone and shipping costs are correctly carried over to PayPal.

With Smart Payment Buttons _enabled_:

![](http://cld.wthms.co/tKJDCR+)
Image Link: http://cld.wthms.co/tKJDCR

With Smart Payment Buttons _disabled_:

![](http://cld.wthms.co/y40erJ+)
Image Link: http://cld.wthms.co/y40erJ

**Comment by zwiesman31** [comment]
Here's another 1501259-zen

CC: @dechov

**Comment by yukikatayama** [comment]
1502710-zen another report

**Comment by luistcode** [comment]
waiting a solution for this. Thanks.

**Comment by MrNghia123** [comment]
Same problem.

**Comment by bnovina** [comment]
The issue appears when the Smart Payment Buttons are enabled only. Anyway, the shipping costs will appear in Activity of PayPal account.
However, there is additional issue when the Smart Payment Buttons are enabled. PayPal does not recognize the country specified in the checkout billing form and return completely different country.
No shipping costs, and wrong country. UK instead of Germany.
![example](https://user-images.githubusercontent.com/44400200/47359377-e3e66600-d6cc-11e8-93ef-0588fe133be9.png)

**Comment by AashikP** [comment]
Hello @woocommerce/hydra pinging here to update that the ticket 1484712-zen is back on top of the queue. Since this already has a PR that is ready to be merged, is there an ETA we can provide to the user?

**Comment by DanReyLop** [comment]
@AashikP We've just released version `1.6.5` of the extension, it includes a fix for this issue.

**Comment by AashikP** [comment]
Thank you @DanReyLop. I've forwarded the master copy to the user :)
