### ISSUE TITLE
[Question] Changing position of button on product page and checkout.

### ISSUE THREAD

**Issue by YHSX88** [woocommerce/woocommerce-gateway-paypal-express-checkout#488]
I'm wondering how to change (permanently so on page refresh does not revert) the position of PayPal button on Checkout & Product pages
**What I want/need:**
product page:
![screenshot 2018-10-20 at 11 28 25](https://user-images.githubusercontent.com/16823745/47253516-9bc10c80-d45c-11e8-869e-b0969480013e.png)
checkout page:
![screenshot 2018-10-20 at 11 29 28](https://user-images.githubusercontent.com/16823745/47253523-aed3dc80-d45c-11e8-905f-1d69833c463a.png)
**What I do:**
product page
![screenshot 2018-10-20 at 11 35 22](https://user-images.githubusercontent.com/16823745/47253529-bbf0cb80-d45c-11e8-8f64-38cceaf41451.png)
checkout page
![screenshot 2018-10-20 at 11 33 19](https://user-images.githubusercontent.com/16823745/47253528-bbf0cb80-d45c-11e8-8478-abcba4b62064.png)

**Software used:**
woocommerce :version 3.4.5 
wordpress : 4.9.8.
theme: avada

**Comment by YHSX88** [comment]
UPDATE: the paypal button on product page has changed it's place which is amazing, now I just need to figure out how where is located the CSS for the checkout button. Please someone help ?

**Comment by YHSX88** [comment]
Yes, Daniel it's working like a charm, thank you so much for the quick and accurate response. God Bless !!!

**Comment by DanReyLop** [comment]
Glad it worked :)

Closing this, please open a new issue if you have any more trouble with the extension.
