### ISSUE TITLE
woocommerce_after_checkout_validation is running twice

### ISSUE THREAD

**Issue by nathanhannig** [woocommerce/woocommerce-gateway-paypal-express-checkout#495]
I have a ReCaptcha v2 [plugin](https://codecanyon.net/item/woocommerce-checkout-recaptcha/17346203) that hooks into `woocommerce_after_checkout_validation`

When starting the Paypal pop-up it appears the `woocommerce_after_checkout_validation` action runs and when you complete your payment details in Paypal and the pop-up closes the  `woocommerce_after_checkout_validation` action runs a second time.

This is causing issues for the ReCaptcha plugin, because the ReCaptcha token is only good for one verification check and will fail any subsequent verification. (Attempt #1: success -> Attempt #2: failure -> Result: failure)

So customer orders are unable to process. The ReCaptcha is required because of "carding" issues and Paypal has asked for a Captcha to be installed on the website.

My assumption is that the action should only run when the Paypal pop-up is closing.

Running on the latest versions of WooCommerce and this plugin.

**Comment by allendav** [comment]
This is a core WooCommerce hook. Does this repeated call only happen for this PayPal specific plugin?

**Comment by menakas** [comment]
Closing as the original issue is more than a year old, it is a very custom requirement  and there has been no response for the last question.
