### ISSUE TITLE
PayPal credit button showing in Australia

### ISSUE THREAD

**Issue by bondimedical3** [woocommerce/woocommerce-gateway-paypal-express-checkout#496]
If I view my website incognito I am seeing a PayPal credit button next to the Paypal button despite the fact it is disabled in the Admin - view screenshot
![paypal](https://user-images.githubusercontent.com/10808588/48047954-d6150280-e1ed-11e8-94b0-5902326b7e50.jpg)

**Comment by EspoTek** [comment]
I have the same issue.
A workaround is to untick the box "Configure settings specific to Single Product view".
This means that you cannot set the button layout or size to anything but the default, however the credit button won't appear.

Devs, reproducible steps to show this bug:
 - Enable PayPal Express Gateway on WordPress
 - Enter credentials from account based in Australia (may be reproducible with all non-US accounts).
 - Enable "Checkout on Single Product"
 - Enable "Configure settings specific to Single Product view"
 - Save changes.
The "Enable PayPal Credit" button will be unticked with an option stating "This option is disabled. Currently PayPal Credit only available for U.S. merchants using USD currency."  However, the PayPal Credit button will show on the Single Product view (see screenshot from Bondi Medical above - I see something similar on my page).  The website administrator is unable to disable this behaviour without disabling all Single Product view configurations.

G'day, by the way.  :)

**Comment by treibalen** [comment]
I see some weird PayPal Credit behavior on my test site as well. 

In my case, it's a US sandbox account, however, I disabled PayPal Credit in the settings (after enabling it):

![https://cld.wthms.co/KQf3wD](https://cld.wthms.co/KQf3wD+) 
Full Size: https://cld.wthms.co/KQf3wD

It still shows on the checkout page:

![https://cld.wthms.co/Zk16o1](https://cld.wthms.co/Zk16o1+) 
Full Size: https://cld.wthms.co/Zk16o1

Also reported in https://wordpress.org/support/topic/paypal-credit-shows-even-though-its-unchecked/

**Comment by jcimb** [comment]
Also tried deactivating the WooCommerce PayPal Checkout Gateway plugin, deleting it, and re-installing it, but it didn't help.

**Comment by jcimb** [comment]
I solved it! There is another option called Hide Funding Methods higher up on that same screen.
Click into that box and one of the options is Paypal Credit. I chose that option, Saved, and now Paypal Credit doesn't appear on the frontend anymore!

**Comment by allendav** [comment]
Let's not show this button in unsupported regions. Opening to 1.7.1

**Comment by mattallan** [comment]
Closed with #668. 

With the updated Javascript SDK, PayPal will only display the PayPal Credit option to customers from supported countries.

From the [PayPal docs](https://developer.paypal.com/docs/checkout/reference/customize-sdk/#buyer-country):

> The buyer country determines which funding sources are eligible for a given buyer. Defaults to the buyer's IP geolocation.
