### ISSUE TITLE
PayPal button not shown on shortcode product_page 

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-paypal-express-checkout#497]
The PayPal button shows up on single product pages, but not on pages displaying products using the shortcode `product_page`.

Example of normal single product page:

![Single product page](http://cld.wthms.co/EjkA0C+)
Full size: http://cld.wthms.co/EjkA0C

Example of product displayed using shortcode:

![Shortcode](http://cld.wthms.co/yrBFer+)
Full size: http://cld.wthms.co/yrBFer

**Comment by menakas** [comment]
via #665

**Comment by re7consultingDE** [comment]
The problem appears again with the newest version 1.6.20
I checked the source code and the part, which was added before, isn't there.

**Comment by menakas** [comment]
@re7consultingDE 
This fix will be released in v1.7.0
