### ISSUE TITLE
[P2][4.3] Add PayPal Credit only for US

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce-gateway-paypal-express-checkout#50]
PayPal Credit has been seen to increase merchant and buyer conversion rates, by giving them access to a very affordable additional line of credit at checkout itself.
## Details
- Provides option (checkbox) to enable PayPal Credit Second button show up on the shopping cart as well as the main checkout page.
- Display PayPal credit button on cart and checkout pages if enabled.

**Comment by gedex** [comment]
@mikaey I assume we only need to pass `USERSELECTEDFUNDINGSOURCE` with value `CreditCard` in [`SetExpressCheckout`](https://developer.paypal.com/docs/classic/api/merchant/SetExpressCheckout_API_Operation_NVP/) call?

Previously (in which it was commented before initial release), field `USERSELECTEDFUNDINGSOURCE` was set to `Finance`. Not sure where this `Finance` comes from as I couldn't find it in https://developer.paypal.com/docs/classic/api/merchant/SetExpressCheckout_API_Operation_NVP/.

**Comment by mikaey** [comment]
Nope, `Finance` is the correct value to pass.  If the buyer chooses to pay by PayPal Credit, you'd pass `USERSELECTEDFUNDINGSOURCE=Finance`; if the buyer just wants to pay by PayPal, you'd leave this parameter off altogether.  As far as I know, `CreditCard` is not a valid value for this field.
