### ISSUE TITLE
Error Billing Province is not valid for some customers

### ISSUE THREAD

**Issue by xgiovio** [woocommerce/woocommerce-gateway-paypal-express-checkout#501]
Hello, on the checkout page, returning from paypal, some customers can't complete the order with the error: Billing Province is not valid. 

A client from Spain sent us this:
Please enter one of the following: A Coruña, Araba/Álava, Albacete, Alicante, Almería, Asturias, Ávila, Badajoz, Baleares, Barcelona, Burgos, Cáceres, Cádiz, Cantabria, Castellón, Ceuta, Ciudad Real, Córdoba, Cuenca, Girona, Granada, Guadalajara, Gipuzkoa, Huelva, Huesca, Jaén, La Rioja, Las Palmas, León, Lleida, Lugo, Madrid, Málaga, Melilla, Murcia, Navarra, Ourense, Palencia, Pontevedra, Salamanca, Santa Cruz de Tenerife, Segovia, Sevilla, Soria, Tarragona, Teruel, Toledo, Valencia, Valladolid, Bizkaia, Zamora, Zaragoza.

Similar issues comes from other clients in Spain.

Any advice? Is it a bug in Paypal or woocomerce?
Thank you

**Comment by zsinryu** [comment]
Guys, any update for this? I have similar issue for China.

**Comment by menakas** [comment]
PayPal does not list the provinces or their codes for Spain in their API reference: https://developer.paypal.com/docs/api/reference/state-codes/

For China, it has been added at #659. Please track progress there.

**Comment by menakas** [comment]
A workaround has been found for Spain too. Please track progress at #659.

**Comment by abelbascu** [comment]
In my case I found that my google pay account had 'Lérida' as the province name but woocommerce had 'Lleida' (Catalan name for the Spanish spelling 'Lérida'). 

For my workaround please check https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/659#issuecomment-757376067

This can also be useful: https://www.terrytsang.com/tutorial/woocommerce/add-modify-states-for-woocommerce-checkout-form/

Thanks for putting me on the good track guys.
