### ISSUE TITLE
Cannot void "authorize" transactions

### ISSUE THREAD

**Issue by creativeround** [woocommerce/woocommerce-gateway-paypal-express-checkout#508]
Void for authorization only transactions is missing in the process_refund function.

**Comment by creativeround** [comment]
#509

**Comment by dechov** [comment]
Void for authorizations is implemented in [a different function](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/e786f368291ca236829dea09f9095b474760d765/includes/class-wc-gateway-ppec-admin-handler.php#L199-L226), triggered by status change to "Refunded" or "Cancelled". I've commented on the PR as well (https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/509#issuecomment-446459415). Please feel free to re-open and elaborate if that is inadequate.
