### ISSUE TITLE
Billing Prefecture is not valid when using a Japanese Address.

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce-gateway-paypal-express-checkout#513]
When going to PayPal from the cart page and selecting a Japanese address in PayPal. We get redirected back to the "Confirm your PayPal order" page in WooCommerce with the following address:

```
151-0053
TOKYO-TO City Street
Test Japan
Japan
```

When we click the place order button we get the following error:

```
Billing Prefecture is not valid. Please enter one of the following: Hokkaido, Aomori, Iwate, Miyagi, Akita, Yamagata, Fukushima, Ibaraki, Tochigi, Gunma, Saitama, Chiba, Tokyo, Kanagawa, Niigata, Toyama, Ishikawa, Fukui, Yamanashi, Nagano, Gifu, Shizuoka, Aichi, Mie, Shiga, Kyoto, Osaka, Hyogo, Nara, Wakayama, Tottori, Shimane, Okayama, Hiroshima, Yamaguchi, Tokushima, Kagawa, Ehime, Kochi, Fukuoka, Saga, Nagasaki, Kumamoto, Oita, Miyazaki, Kagoshima, Okinawa
```

This is because the prefecture/state `TOKYO-TO` doesn't match with the WooCommerce state Tokyo.

PayPal uses the following values for prefecture/state:

```
HOKKAIDO = Hokkaido
AOMORI-KEN = Aomori
IWATE-KEN = Iwate
MIYAGI-KEN = Miyagi
AKITA-KEN = Akita
YAMAGATA-KEN = Yamagata
FUKUSHIMA-KEN = Fukushima
IBARAKI-KEN = Ibaraki
TOCHIGI-KEN = Tochigi
GUNMA-KEN = Gunma
SAITAMA-KEN = Saitama
CHIBA-KEN = Chiba
TOKYO-TO = Tokyo
KANAGAWA-KEN = Kanagawa
NIIGATA-KEN = Niigata
TOYAMA-KEN = Toyama
ISHIKAWA-KEN = Ishikawa
FUKUI-KEN = Fukui
YAMANASHI-KEN = Yamanashi
NAGANO-KEN = Nagano
GIFU-KEN = Gifu
SHIZUOKA-KEN = Shizuoka
AICHI-KEN = Aichi
MIE-KEN = Mie
SHIGA-KEN = Shiga
KYOTO-FU = Kyoto
OSAKA-FU = Osaka
HYOGO-KEN = Hyogo
NARA-KEN = Nara
WAKAYAMA-KEN = Wakayama
TOTTORI-KEN = Tottori
SHIMANE-KEN = Shimane
OKAYAMA-KEN = Okayama
HIROSHIMA-KEN = Hiroshima
YAMAGUCHI-KEN = Yamaguchi
TOKUSHIMA-KEN = Tokushima
KAGAWA-KEN = Kagawa
EHIME-KEN = Ehime
KOCHI-KEN = Kochi
FUKUOKA-KEN = Fukuoka
SAGA-KEN = Saga
NAGASAKI-KEN = Nagasaki
KUMAMOTO-KEN = Kumamoto
OITA-KEN = Oita
MIYAZAKI-KEN = Miyazaki
KAGOSHIMA-KEN = Kagoshima
OKINAWA-KEN = Okinawa
```

In WooCommerce we use the states as defined here: https://github.com/woocommerce/woocommerce/blob/master/i18n/states/JP.php

For other countries there is  a function to normalize the state to get around this mapping. See: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/1.6.5/includes/class-wc-gateway-ppec-address.php#L345

To match the two up it looks like an array of something like this is needed (to convert between the PayPal value and WooCommerce):

```
'tokyo-to' => 'JP13'
```

**Comment by C1T7** [comment]
Customer having the exact same issue ordering from Japan today as shown above.
Is there any expectation of when this issue will be resolved?

**Comment by menakas** [comment]
@mikkamp 
>When going to PayPal from the cart page and selecting a Japanese address in PayPal. We get redirected back to the "Confirm your PayPal order" page in WooCommerce with the following address:

I am unable to reproduce this as the language changes to Japanese when I choose Japan as the country and I am not sure how to proceed further. Would you have a set of steps to reproduce this issue?

**Comment by mikkamp** [comment]
It switches the language if you haven't logged in. To reproduce it you can also just log in with a sandbox account (which will stay in English) and then just choose to ship to an address in Japan (the example address above can be used for this).

**Comment by menakas** [comment]
Thanks @mikkamp 
I can reproduce it now.

**Comment by dsmithweb** [comment]
Reported in 2830959-zen

**Comment by menakas** [comment]
via #659
