### ISSUE TITLE
When required addon is not selected for a product, mimic add to cart button behaviour

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-paypal-express-checkout#515]
When an addon field is required for a product (using Product Addons Extension), when trying to click 'Add to Cart' a popup shows up explaining that the addon field must be selected.

Here's a gif showing that:

![product-add-on-required-before-adding-to-cart](https://user-images.githubusercontent.com/11487924/50102921-65053980-01f4-11e9-98c4-47e7bd8867d1.gif)

The PayPal buttons are disabled. Instead they should mimic this behaviour.

Initially reported in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/507#issue-233410175

**Comment by mattallan** [comment]
Closed with #707
