### ISSUE TITLE
Variation data removed when checking out from single product page

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-gateway-paypal-express-checkout#522]
Using v1.6.6, if checking out from a Single Product Page with a variable product, the variation data is removed once the user is returned to the cart to complete the transaction. This means the data is also not passed to the order. 

Reported in chat: 9750926-hc

1. Create a variable product
1. Check out from single product page
1. Complete PP info and get directed back to cart
1. Variation data is no longer present on item

**Comment by RadoslavGeorgiev** [comment]
Hi @jessepearson!

I tried this with a couple of dummy products, but could not reproduce it. My colleagues recently added the necessary functionality through https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/507 and it seems to work.

Have you tried diagnosing the issue yourself? It could be related to other WooCommerce extensions or some product specifics. Do you have a staging environment where you can disable all possible WC extensions and give it a try again?

**Comment by jessepearson** [comment]
@RadoslavGeorgiev I just tested again on a different site that I wipe frequently. It appears to happen when the variation is an "any" variation, like this:

![](http://cld.wthms.co/VCpFIM+)
Image Link: http://cld.wthms.co/VCpFIM

When I had variations created for each attribute, the data was sent through, but once I removed the specific variations and used a generic one, just the product name was sent. 

```
    [L_PAYMENTREQUEST_0_NAME0] => Variable product with a longer name - green, medium
...
    [L_PAYMENTREQUEST_0_NAME0] => Variable product with a longer name
```

**Comment by RadoslavGeorgiev** [comment]
@jessepearson amazing find! And the fix is quite easy too: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/523/files

We will try to include this in the next version of the plugin, which should be released this week.
