### ISSUE TITLE
version 1.6.7 brakes woocommerce product pages

### ISSUE THREAD

**Issue by cristianocasella** [woocommerce/woocommerce-gateway-paypal-express-checkout#524]
Hi guys,
after the updates I can't see the woocommerce product pages, getting this error:

` [php7:error] [pid 2351] [client xxxxxxxx:xxxx] PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function WC_Gateway_PPEC_Cart_Handler::maybe_enqueue_checkout_js(), 2 passed and exactly 3 expected in /nas/content/live/fermentnetwork/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-cart-handler.php:367\nStack trace:\n#0 [internal function]: WC_Gateway_PPEC_Cart_Handler->maybe_enqueue_checkout_js('Price filter', Array)\n#1 /nas/content/live/fermentnetwork/wp-includes/class-wp-hook.php(286): call_user_func_array(Array, Array)\n#2 /nas/content/live/fermentnetwork/wp-includes/plugin.php(203): WP_Hook->apply_filters('Price filter', Array)\n#3 /nas/content/live/fermentnetwork/wp-content/themes/basel/inc/widgets/class-widget-price-filter.php(70): apply_filters('widget_title', 'Price filter', Array)\n#4 /nas/content/live/fermentnetwork/wp-includes/widgets.php(1098): BASEL_Widget_Price_Filter->widget(Array, Array)\n#5 /nas/content/live/fermentnetwork/wp-content/themes/basel/inc/woocommerce.php(1460): the_widget('BASEL_Widget_Pr in /nas/content/live/fermentnetwork/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-cart-handler.php on line 367, referer: https://www.xxxxxxxxxxx.com/`

Can you help me?

Best Regards
Cristiano

**Comment by dechov** [comment]
Hi @cristianocasella, thank you for reporting this.

It appears to be a conflict with the Basel theme, which is applying the `widget_title` filter with only two arguments (rather than the three documented [here](https://developer.wordpress.org/reference/hooks/widget_title/)).

You'll need to make sure you are running a recent version of that theme and/or contact the theme developer. Hope that helps!

**Comment by cristianocasella** [comment]
Hi @dechov, really thanks for your support and debug.

Regards
Cristiano

**Comment by dechov** [comment]
There appears to be a similar issue with other themes as well, so we have just released a fix in version 1.6.8 that should solve it.

Let us know if there's still an issue, and thanks again for reporting!

**Comment by allendav** [comment]
Fixed in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/releases/tag/1.6.8 with #525 
Props @dechov
