### ISSUE TITLE
Explore bundling or locking the checkout.js dependency version

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce-gateway-paypal-express-checkout#529]
In light of https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/527, which affected all 1.6.x releases as a result of incompatibility with an unexpected (and unfortunately timed) change in PayPal's checkout.js library [[PR](https://github.com/paypal/paypal-checkout/pull/1001), [release](https://github.com/paypal/paypal-checkout/commit/02ed6dd17915189e42a62a9252918d0089ce07e7)]:

We should consider the advisability of bundling the checkout.js script with the plugin, rather than loading the remote script (or at least checking if there is a way to load a specific version), so as to keep such possible breakages in the plugin under the purview of our release cadence.

**Comment by davias1368** [comment]
Hello,
This plugin has problems when select “Landing Page” with “Billing (Non-paypal account)”
When i click on paypal button or credit card icon. It has error. 
“We’re sorry
Things don’t appear to be working at the moment.”

**Comment by jorgeatorres** [comment]
I believe this is no longer possible now that we're using the new [SDK API](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/668).
Feel free to re-open if that's not the case and this is still relevant 🙂.
