### ISSUE TITLE
[CSS UI QUESTION] Aligning of terms & conditions checkbox to right on checkout.

### ISSUE THREAD

**Issue by YHSX88** [woocommerce/woocommerce-gateway-paypal-express-checkout#530]
Hey Guys

I'm looking for some CSS magic so I can move the  terms & conditions to right on checkout.
Please any help is greatly appreciated.
![pp_t c_right](https://user-images.githubusercontent.com/16823745/52237871-50c7e980-28d3-11e9-96ab-e58082c9b2e2.jpg)

**Comment by allendav** [comment]
Try

`.woocommerce-terms-and-conditions-wrapper .woocommerce-form__label-for-checkbox { text-align: right }`
