### ISSUE TITLE
The name of the paypal button hook

### ISSUE THREAD

**Issue by errand** [woocommerce/woocommerce-gateway-paypal-express-checkout#533]
Hello, i need to change the order of the buttons on the cart page and i'm stuck searching for the name of the action i should implement.
Please help

**Comment by errand** [comment]
IDK what goes instead of $this in 
add_action( 'woocommerce_proceed_to_checkout', array( $this, 'display_paypal_button' ), 20 );
tried $WC_Gateway_PPEC_Cart_Handler but didn't work

**Comment by allendav** [comment]
Hi @errand - exactly how would you like to re-order them? It may not be possible without us changing the plugin to expose the WC_Gateway_PPEC_Cart_Handler somewhere

**Comment by DavePodosyan** [comment]
Any update on this?

**Comment by james-allan** [comment]
As the OP discovered, the PayPal buttons are added to the cart page using the `woocommerce_proceed_to_checkout` hook. 

To change the order of the buttons you'll need to reorder the functions hooked onto that. In place of `$this` @errand, you should use `wc_gateway_ppec()->cart->display_paypal_button()`.
