### ISSUE TITLE
Order Itemmeta data for variations displaying (it shouldn't)

### ISSUE THREAD

**Issue by bighippo999** [woocommerce/woocommerce-gateway-paypal-express-checkout#534]
Having a problem after recent updates where some order item variation meta data is being displayed. If it were displaying just in the Admin side we'd ignore it, but we use a plugin to create and print PDF packing slips and the same info is being output on these, turning a single line into a 1/4 of a page of useless data. I could look to remove it from the packingslip output but it seems better to fix the root cause.
I think I've narrowed it down to this plugin (which is difficult as it doesn't appear to affect every order) 
The meta keys output are:
nonce
quantity
ppec-add-to-cart
product_id
variation_id

You can see the additional info using the order quick view screen (as attached, top is an order (with 2 items) how it should look and the bottom (single item) is showing the additional info. I blanked out some potentially identifiable data on both).

I dont know where to go from here to diagnose further. I can't turn off all other plugins, it's a live site! As above, it's not affecting every order and I cant replicate the problem when I place orders or on our test system but somehow customers are managing to do something I'm unable to do :) and we keep seeing this on packingslips.
I found this recent change https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/523/files but no idea if it's related, the timing is about right but that's as much as I know.

Any help to diagnose further appreciated.

![image](https://user-images.githubusercontent.com/14914293/52907752-b87d1d80-325f-11e9-9110-02be026fb32c.png)

**Comment by ChrisStanyon** [comment]
Experiencing exactly the same problem.

For me, it only happens when using the Buy Now button on a Single Product with variations. If I first add the product to the Basket and then checkout normally, it works fine.

Seems to be an issue with the Single Product - Buy Now button!
