### ISSUE TITLE
Line Item Amount Offset and Discount Applied Twice in Paypal Invoice - Continuation of Issue #335

### ISSUE THREAD

**Issue by codingwithchris** [woocommerce/woocommerce-gateway-paypal-express-checkout#538]
## Overview
I am having the exact same issue as discussed in #335 (Order detail not match in Paypal after apply coupon). Esentially the Paypal invoice line items do NOT match the WooCommerce applied discounts, even though the total is the same. The main issue is, this is creating a great deal of confusion for our clients, who see the invoices come through. To them, is seems like people are getting HUGE discounts. They aren't able to see what is really going on.

@dougaitken Please see below.

I can confirm the user took the following steps as outlined by @treibalen in the referenced ticket (above):

1. Add an item to cart
2. Apply a discount code
3. Click on the yellow 'PayPal' button
4. See the correct price, including the discount
5. Pay with PayPal
6. See that the order went through with the discount correctly.

The end result of this test can be seen below.

## Environment System Setup
PHP Version: 7.2
WP Version: 5.1
WC Version: 3.5.5 
WooCommerce Paypal Express Checkout Version: 1.6.9

## Snapshot of Order in WooCommerce Admin
![screen shot 2019-03-05 at 9 51 26 am](https://user-images.githubusercontent.com/17693193/53813792-65c48680-3f2c-11e9-92d3-000465961ab3.png)

## Generated Paypal Invoice
![screen shot 2019-03-05 at 9 51 36 am](https://user-images.githubusercontent.com/17693193/53813801-69f0a400-3f2c-11e9-8214-e72b7758c9d0.png)

### More Info
You can see that the TOTAL is correct,  but the invoice generated by Paypal is duplicating *Line Item Amount Offset* and doubling the *Discount*.

This is still a real and present issue, unfortunately.

**Comment by dougaitken** [comment]
Hey @codingwithchris - can you update the WooCommerce PayPal Checkout Payment Gateway plugin to version `1.6.10` and then confirm you have tested this with no other plugins active aside from those you listed and the [Storefront](https://woocommerce.com/products/storefront/) theme, please? 

If you can open a ticket with support about this, we can take a closer look.

Thanks,

**Comment by codingwithchris** [comment]
@dougaitken Updated to latest... unfortunately, timing-wise we are on the verge of a site launch so you'll have to allow me a few days to get everything set up on the new server before I can test a clone with plugins deactivated and Storefront theme installed.

**Comment by dougaitken** [comment]
Thanks @codingwithchris - best wishes for the launch!

Closing now until we can replicate this fully.

**Comment by chris-torrence** [comment]
I see the same issue. I just set up a woocommerce+printful, and added a $5 fixed product discount. You can see in the PayPal that when I bought 2 shirts, it added an extra $10 "charge", and then took $20 off. The final total is correct, but it is very confusing to customers. Should I open up a new issue? Thanks!
![bug](https://user-images.githubusercontent.com/5461379/55600997-c73e6780-571b-11e9-93e2-4c82dcdeabb1.jpg)

**Comment by madeincosmos** [comment]
Reopening as I'm still seeing the same problem with PPEC 1.6.10 and WooCommerce 3.5.7:

![Screenshot](https://cld.wthms.co/i7eYnO+)
Screenshot: https://cld.wthms.co/i7eYnO

**Comment by pvel3** [comment]
April 5, 2019.
I had this same issue this weekend. All WordPress/WooCommerce up to date. Was directed to this page from support ticket to track update progress.

**Comment by chris-torrence** [comment]
I wonder if this is related to the "Subtotal Mismatch Behavior" setting on WooCommerce. I just changed that setting to "Do not send line items to PayPal", and then did a new order with a coupon, and the extra "Line Item Offset Amount" lines are gone.

**Comment by corsonr** [comment]
reported in hc-7262716 as well

**Comment by xboxhacker** [comment]
If I set my "Subtotal Mismatch Behavior" to "Do not send line items to PayPal". My Line Mismatch are gone on PayPal. **But also so are _all_ other lines!!**

Please see images.

![Screenshot 2019-09-05 12 54 14](https://user-images.githubusercontent.com/15465932/64363165-e77d9580-cfdd-11e9-8232-04ace8a25a2a.png)

![Screenshot 2019-09-05 12 54 55](https://user-images.githubusercontent.com/15465932/64363265-27dd1380-cfde-11e9-991f-681b1c09d63e.png)

WP Ver5.2.3
WC Ver3.7.0
WC_PayPal_gateway Ver1.6.17

**Comment by Hastibe** [comment]
I am also encountering this issue. Are there any solutions, yet?

**Comment by ganeshsu100** [comment]
I am also having the same issue.

**Comment by megann42** [comment]
Having an identical issue as @xboxhacker. Any solutions?

**Comment by nsnooze** [comment]
Also having the same issue, with multiple line items and double discount applied.  Total is correct, but does not give a great customer experience when they can't understand the invoice generated by PayPal.  Has anyone got a solution to this?

**Comment by syhip12** [comment]
I'm having the same issue when customers use points (woocoomerce points and rewards) as a discount.

Customer selects to use points (example in screenshot is £2.74).
Shows as adding (instead of minus) this amount twice (2 x line items) and then removing once in top section of paypal. So at this moment the customer is shown as paying 2 times the discount amount over the price of the item. 

In bottom section to get the correct amount it then shows a delivery discount of £5.48.

The figure ends up being correct after this minus but this is very confusing for us and customers. ANy update on the fix? 



![github](https://user-images.githubusercontent.com/60095440/72719673-2fa5ea80-3b70-11ea-9b6f-101aa8a1a1c9.jpg)

**Comment by menakas** [comment]
Duplicate. Closing this. Please track progress at #485
