### ISSUE TITLE
Add all locale codes to $_supported_locales array

### ISSUE THREAD

**Issue by beamkiller** [woocommerce/woocommerce-gateway-paypal-express-checkout#541]
Hi,

I have a hungarian webshop and I wanted to appear the Paypal checkout page in Hungarian language. But it is not defined in supported locales array so it defaults all the time to en_US.

File: \woocommerce-gateway-paypal-express-checkout\includes\class-wc-gateway-ppec-settings.php
Line: 24

The supported locale codes by PayPal are much more extended:
https://developer.paypal.com/docs/classic/api/locale_codes/#

I have solved it with the hook provided for now:
```
add_filter('woocommerce_paypal_express_checkout_paypal_locale','set_default_language_paypal_express');

function set_default_language_paypal_express()
{
	return 'hu_HU';
}
```

**Comment by aalkz** [comment]
Your solution worked for me, thank you so much for sharing this.

An explicit option in the plugin settings UI for changing this behavior would be great, though as proposed in #468

**Comment by allendav** [comment]
Yes, let's add this filter

**Comment by menakas** [comment]
Via #446
