### ISSUE TITLE
PayPal marks not displaying on Cart page, updated image path needed

### ISSUE THREAD

**Issue by amyschan** [woocommerce/woocommerce-gateway-paypal-express-checkout#546]
Hello, I noticed the PayPal marks on the cart page are not displaying and need to be fixed:

https://www.paypalobjects.com/webstatic/en_US/i/buttons/checkout-logo-.png
https://www.paypalobjects.com/webstatic/en_US/i/buttons/ppcredit-logo-.png

![image](https://user-images.githubusercontent.com/900909/54785898-a4249b80-4be4-11e9-937d-56286ea2b5c4.png)

![image](https://user-images.githubusercontent.com/900909/54783939-daabe780-4bdf-11e9-897f-904cb4a74681.png)

![image](https://user-images.githubusercontent.com/900909/54785682-15178380-4be4-11e9-9336-a58f4c82de73.png)

Here's what I'm running:

WordPress 5.1
WooCommerce 3.5.6
WooCommerce PayPal Checkout Gateway 1.6.10

**Comment by aaburlaka** [comment]
Image url still wrong on:

WordPress 5.2
WooCommerce 3.6.2
WooCommerce PayPal Checkout Gateway 1.6.11

**Comment by jobthomas** [comment]
Another case to add: 2077490-zen

I've inspected my site vs. the one of the customer and I can see that something on the site is overriding the default structure: 

![Url comparsion](https://cld.wthms.co/uZdNmJ+)
Link to image here: https://cld.wthms.co/uZdNmJ.

@aaburlaka - what I'm suspecting is that this PR by @gedex didn't work as expected: #162. Could you try in the settings to change the size of your button manually? 

![try changing the size](https://cld.wthms.co/MmBT1X+)
Link to image here: https://cld.wthms.co/MmBT1X.

**Comment by jobthomas** [comment]
In the case mentioned above, the solution I suggested worked. Could you try that @amyschan and @aaburlaka? I'll close this issue now.
