### ISSUE TITLE
Should not be declaring support for payment method changes for Subscriptions

### ISSUE THREAD

**Issue by jrick1229** [woocommerce/woocommerce-gateway-paypal-express-checkout#551]
### Issue

When attempting to 'Change payment' on a subscription, the following error is received: "The payment method cannot be changed for this subscription."
This is a default error message that we add in for instances like, but not including, this one.

### Steps to Replicate

1. Create a subscription using PayPal Checkout.
2. Navigate to the subscription in the My Account page.
3. Click 'Change payment'.
4. Receive the error: *The payment method cannot be changed for this subscription.*

### Logs

This is the error that is logged in the PPEC logs after attempting to make the change:

```
WC_Gateway_PPEC_Client::_process_response: acknowleged response body: Array
(
    [TIMESTAMP] => 2019-04-01T06:29:19Z
    [CORRELATIONID] => 97b1d8f0c963c
    [ACK] => Failure
    [VERSION] => 120.0
    [BUILD] => 000000
    [L_ERRORCODE0] => 10525
    [L_SHORTMESSAGE0] => Invalid Data
    [L_LONGMESSAGE0] => This transaction cannot be processed. The amount to be charged is zero.
    [L_SEVERITYCODE0] => Error
)
```

### How to Fix

PayPal Checkout will need to somehow allow an amount of zero for payment method changes.

**OR**

Remove the declaration that PayPal Checkout supports payment method changes, as it seems to no longer do so.

**Comment by RadoslavGeorgiev** [comment]
Hi @jrick1229,

thanks for reporting this! it seems like we are hitting the `DoExpressCheckoutPayment` endpoint instead of `CreateBillingAgreement`.

I will check why/when this happened and try to give you an update ASAP.

**Comment by jrick1229** [comment]
Thanks @RadoslavGeorgiev! Please let me know when you've found something out. We have a few customers interested in why this is happening.

**Comment by NickGreen** [comment]
I'm getting further customer issues with stores that have free trials on subscription products, but PayPal Checkout is unable to process $0 payments.

With the PayPal Standard integration, we fudge this by charging $0.01 for $0 payments, but it appears that this hasn't been dealt with in the PayPal Checkout plugin.

**Comment by rtddev** [comment]
Is this issue related to this issue:
https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/367

**Comment by NickGreen** [comment]
@rtddev This is related to, but different from, the issue you linked. Related to it, because PayPal Checkout isn't supporting $0 payments. The heart of the matter is the same in that PayPal Checkout shouldn't be declaring support for something that requires the ability to handle $0 payments.

Different from, because this is a case of being able to change payment methods to PayPal Checkout, but then getting an error from PayPal because of the requested $0 charge, so it's a different part of the process, and actually results in an error, rather than just not showing up at checkout.

**Comment by rtddev** [comment]
@NickGreen - Ok, thanks.
