### ISSUE TITLE
[Name Your Price compatibility] Filter to hide PayPal buttons for specific products

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce-gateway-paypal-express-checkout#554]
The quick pay buttons on a single product page don't work well with name your price products as they don't send the inputted price value.

In the short term, it's necessary to hide the buttons and force a user to use the cart/checkout in order to pay.

Could use a filter in the `WC_Gateway_PPEC_Cart_Handler::display_paypal_button_product()` method to disable the buttons on a per-product basis.

**Comment by helgatheviking** [comment]
Another thought would be to use `$product->supports()` ? Then it could perhaps even be made consistent with the Stripe gateway's payment request buttons so dynamically priced products, Name Your Price, Mix and Match, anything with Product Addons, can all disable ALL the buttons uniformly with a single filter.

Long term, it would be cool to figure out a way to make them work together... hide the PayPal buttons until the price is entered and then the entered price to PayPal.

**Comment by allendav** [comment]
@bmccotter - would you provide a recommended priority for this enhancement?

**Comment by bmccotter** [comment]
Hi @allendav this is a low priority.

**Comment by helgatheviking** [comment]
Noticed this today in another context, definitely need to remove these buttons from Mix and Match product types.. and I'd guess Product Bundles and Composite Products too, but have't confirmed.

**Comment by allendav** [comment]
Thank you @bmccotter and @helgatheviking.

> Noticed this today in another context, definitely need to remove these buttons from Mix and Match product types

I think I misclassified this as an enhancement. @helgatheviking  - so the wrong price is charged the buyer for name-your-price products if they use the PayPal button on those pages?

**Comment by helgatheviking** [comment]
After testing, I'm seeing that NYP seems to work ok with the buttons. So yay for that! This should stay active for a day or so (and it's using the PayPal sandbox if you want to test it)
https://wp5-helgatheviking.c9users.io/product/simple-nyp/

Seems to work with Mix and Match too!
https://wp5-helgatheviking.c9users.io/product/t-shirt-12-pack/

I expected it not to based on past experience with Stripe request buttons, so I may have jumped to conclusions. Based on the tests I just did, I think this can stay as a minor enhancement.
