### ISSUE TITLE
In out-of-stock single product pages: Uncaught TypeError 

### ISSUE THREAD

**Issue by htdat** [woocommerce/woocommerce-gateway-paypal-express-checkout#558]
This error does not affect the operation but it should be fixed. 

### Steps to replicate the issue 

1. Create an out-of-stock product.
2. Visit its single product page.
3. Check the browser console, this JS error displays: 

```
Uncaught TypeError: Cannot read property 'checkValidity' of undefined
    at validate_form (wc-gateway-ppec-generate-cart.js?ver=1.6.11:46)
    at wc-gateway-ppec-generate-cart.js?ver=1.6.11:70
    at wc-gateway-ppec-generate-cart.js?ver=1.6.11:126
```

![Screen Shot 2019-04-18 at 13 47 29](https://user-images.githubusercontent.com/10045087/56342199-8a757480-61e1-11e9-9560-0698e8ca8a44.png)

### What expected

No error in the browser console. 

### Environment 

* Default WP theme.
* WooCommerce PayPal Checkout Gateway 1.6.11 and WooCommerce 3.6.1

### Addtional context 

https://wordpress.org/support/topic/uncaught-typeerror-checkvalidity-when-product-is-out-of-stock/

**Comment by sknzl** [comment]
Having the same issue here. Since we have a newsletter sign up form in the footer it won't show up on product pages that are out of stock.

**Comment by vencreative** [comment]
Same issue is happening with us, however, all products are having this error.

**Comment by JakePT** [comment]
When using a plugin like Autoptimize to concatenate JavaScript, this can cause all scripts to fail. Adding wc-gateway-ppec-generate-cart.js to the exclusions list will resolve that issue, but the error still appears in the console.

**Comment by pjrfigueiredo** [comment]
I had a minification plugin (Asset CleanUp: Page Speed Booster) and it was causing this issue.
Disabling it salved my problem.
