### ISSUE TITLE
SCA: Ensure PSD2 / SCA / 3D Secure 2.0 Readiness

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-paypal-express-checkout#560]
At a minimum, we need to validate that this extension works properly when EEA buyers present cards which require 3D Secure 2.0 as part of getting ready for PSD2 / SCA (which takes effect on September 14, 2019.)

It is possible this extension will require no remediation to be ready for SCA.

See also https://www.braintreepayments.com/blog/getting-up-to-speed-on-psd2-regulation-2/

**Comment by GeekPress** [comment]
Hi there!

Do you know if this extension needs any updates to be SCA ready? If so, do you have any ETA, September 14 is very soon ;)

**Comment by whpcreative** [comment]
Hi,
Any news on this yet?

**Comment by enoch85** [comment]
I'm also wondering...

**Comment by allendav** [comment]
We believe all the changes needed for this plugin to accept 3D Secure 2 payments are on PayPal's server side. We are working with PayPal to determine when those changes will be live.

cc @bmccotter

**Comment by jorgeatorres** [comment]
As mentioned by Allen, 3DS should be already supported on PayPal's side. Looking at the developer docs, only ["hosted fields"](https://developer.paypal.com/docs/business/checkout/add-capabilities/3d-secure/#enable-in-card-integration) requires some configuration, but we don't support this integration in PayPal Checkout.
I believe it should be safe to close this issue, but feel free to re-open if I've missed something.
