### ISSUE TITLE
If certificate is entered, there's no way to remove it

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-gateway-paypal-express-checkout#565]
If certificate is entered, there's no way to remove it without manually removing the entry for `woocommerce_ppec_paypal_settings` in the database. 

### Reported in: 
1988758-zen

### Replication steps

1. Upload an image as a cert in the settings and save
1. PPEC will no longer work and there's no way to remove the "cert"

**Comment by menakas** [comment]
@jessepearson 
Do you see this behaviour now? 
I see that the cert file is not uploaded or saved at all. Saving and refreshing the page shows the "Choose file" button with not attached file.

**Comment by jessepearson** [comment]
@menakas Yes, I still see the same issue. I click the button to choose a file, I choose a local image, then save the page. When the page refreshes I get `Error: The API certificate is not valid.` at the top. Checking the db entry for `woocommerce_ppec_paypal_settings` shows there's a cert in the settings. 

If you try to use PP Checkout from a single product page you get: 

![](https://d.pr/i/ELHN3C+)
Image Link: https://d.pr/i/ELHN3C

Logs show:

```
01-31-2020 @ 08:07:57 - WC_Gateway_PPEC_Client::_request: returns error: Array
(
    [ACK] => Failure
    [L_ERRORCODE0] => 3
    [L_SHORTMESSAGE0] => Error in WC_Gateway_PPEC_Client::_request
    [L_LONGMESSAGE0] => An error occurred while trying to connect to PayPal: cURL error 58: could not load PEM client certificate, OpenSSL error error:0906D06C:PEM routines:PEM_read_bio:no start line, (no key found, wrong pass phrase, or wrong file format?)
    [L_SEVERITYCODE0] => Error
)
```

Image used: ![tron](https://user-images.githubusercontent.com/4634416/73538466-1d8e3c80-43f9-11ea-841c-2e1307194adb.jpg)

Do I believe customers will upload images instead of certificates, no, but it shows the wrong type of file can be uploaded. It also shows that once the file is uploaded there's no way to clear it without deleting the entry from the db. 😄

**Comment by menakas** [comment]
Thanks @jessepearson for the detailed info.
I can reproduce it and see the same behaviour.

**Comment by amandasjackson** [comment]
another user with this issue here 19685989-hc
