### ISSUE TITLE
Inconsistent usage of the Smart Button Label

### ISSUE THREAD

**Issue by justlevine** [woocommerce/woocommerce-gateway-paypal-express-checkout#572]
Hi.
For some reason, the Smart Button `Label` only appears when the button layout is set to horizontal. Also, the label used seems to always be 'Pay Now& and not the label you define in the settings for PayPal.

Using latest versions of WordPress (5.2), Woocommerce (3.6.2), and WPEC (1.6.14). All other plugins are disabled, and twentyninteen is theme.

**Comment by treibalen** [comment]
Originally posted here - https://wordpress.org/support/topic/change-smart-button-text/#post-11542343

There is no setting within the plugin to change the `Buy Now` label text:

![https://cld.wthms.co/MgPpkV](https://cld.wthms.co/MgPpkV+) 
Full Size: https://cld.wthms.co/MgPpkV

Not even in the plugin’s code – https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/search – so it looks like it's pulling the label from PayPal itself. 

Are there any plans to make it adjustable with a hook/plugin setting in the future?

**Comment by justlevine** [comment]
@Treibalen - thanks for adding context.

To clarify (because my WordPress post is slightly different than this issue, even if they all over lap), there's several things going on.

1. The Button Label shows up on horizontal but not on vertical. This is inconsistent behavior, and I believe should be considered a bug.

2. The Smart Button label (when shown) is set as 'Pay Now', and not to the name you set in the plugin, which is the standard procedure before the transition to Smart Buttons / if Smart Buttons are disabled. This is also inconsistent behavior, and I believe should be considered a bug.

3. It would be nice to be able to override whatever (consistent) default behavior is set for the Smart Buttons via hooks and settings. E.g. Show/Hiding the logo and the label text (if on a certain page, you don't want it to be the same as the name you already set in the plugin). **This** is a feature request, although offering it as a settings option would provide backwards-compability with the fact that many users are probably already used to the inconsistent behavior in 1 and 2.

**Comment by dechov** [comment]
At the time this integration was done, the `label` didn't apply for vertical layout – this must have been changed later, as I see it showing up the same way for horizontal and vertical now.

The button text cannot be arbitrarily customized but there are a few options for what the `label` could be (as documented [here](https://developer.paypal.com/docs/checkout/integration-features/customize-button/#label)) though this isn't currently exposed in the plugin.

A change on both counts should be considered. Thank you for raising this!

**Comment by menakas** [comment]
Via #666
