### ISSUE TITLE
Custom order status not handled correctly when Authorizing payment

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce-gateway-paypal-express-checkout#573]
I think the issue raised in https://github.com/woocommerce/woocommerce/issues/23626 applies here as well? 

Please see related PR for an inspiration for a fix: https://github.com/woocommerce/woocommerce/pull/23634

**Comment by DanReyLop** [comment]
Thanks for the heads-up! I applied the same fix to the PayPal extension in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/574 and the Stripe extension in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/870
