### ISSUE TITLE
Coupon email restriction is bypassed

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce-gateway-paypal-express-checkout#575]
When setting-up an email restriction for a coupon, the restriction isn't taken into account by PayPal since the coupon is applied before the check is done.

To replicate:
1. Create a coupon restricted to a mail or a domain
2. add a product to cart
3. Apply the coupon
4. got the checkout page and use another email
5. Hit the PayPal button
6. you'll be prompt to pay and the discount will be applied while it should not

The following message should be displayed but isn't:

![](https://cld.wthms.co/zq1Lqz+)

**Comment by menakas** [comment]
@corsonr 
I tested this and found that the error message is displayed: https://d.pr/i/O9qSBm
I am closing this as this has been fixed perhaps with an earlier PR.

If you can still see this issue, please feel free to reopen it.
