### ISSUE TITLE
Warn users that legacy payment buttons will be phased out in lieu of Smart Payment buttons

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-paypal-express-checkout#578]
If a user has Smart Payment Buttons not enabled, display a notice warning that support for legacy payment buttons will be removed in an upcoming release.

<img width="640" alt="Screen Shot 2019-06-05 at 12 32 55 PM" src="https://user-images.githubusercontent.com/1595739/58984525-222d2300-878e-11e9-854e-97a7d6c1cc51.png">

**Comment by v18** [comment]
Show an admin notice, make it re-appear if a store owner is not using the smart buttons.
