### ISSUE TITLE
Remove Smart Payment button setting, treat as enabled, allow filtering to enable legacy buttons

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-paypal-express-checkout#579]
See also #578

- Remove the Smart Payment button from settings
- Update the code depending on the former setting to treat it as enabled
- Allow a filter to disable Smart Payment buttons and revert to the legacy approach

**Comment by v18** [comment]
@allendav in issue #578 you mention that you'd like to warn users that legacy payment buttons will be phased. Should we handle that in this release, and move this issue to another (major) release?

**Comment by james-allan** [comment]
Closed via #660
