### ISSUE TITLE
Error: Call to a member function has_session() on null / class-wc-gateway-ppec-cart-handler.php:514

### ISSUE THREAD

**Issue by portalzine** [woocommerce/woocommerce-gateway-paypal-express-checkout#580]
This error has been showing up for the last 2 releases.

/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-cart-handler.php:514

**Comment by dechov** [comment]
My impression was that the session was always set, but it looks like [this condition](https://github.com/woocommerce/woocommerce/blob/7222f982e23e95c69edb4c4d2d5dbbdd0f092d37/includes/class-woocommerce.php#L756) added in WC 3.6.4 may have changed this.

Should add a check for WC()->session to the beginning of [this condition](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/includes/class-wc-gateway-ppec-cart-handler.php#L518). (Props @bor0 for calling that out in the original review [[#](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/445#discussion_r200102174)].)

cc @reykjalin

**Comment by v18** [comment]
I'm not sure how to repro, but I have seen this sort of thing happen with Stripe where folks are using the public functions available in a non-cart context.

**Comment by v18** [comment]
@portalzine are you still seeing this issue with version 1.6.17? If so, could you please copy and paste the entire error stack? It will include information about where the error originated from, including the previous functions that were called and in which files.

If you also happen to know what triggers this error, could you let us know? Thanks! :)
