### ISSUE TITLE
Unable to connect to PayPal using certificate file

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce-gateway-paypal-express-checkout#584]
When uploading a certificate file to connect to PayPal we get the following message:
`Error: The API certificate is not valid.`

The reason it's not valid is because the certificate file is base64 encoded before it's being saved in the database, see: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/1.6.15/includes/abstracts/abstract-wc-gateway-ppec.php#L231

And the same code for the sandbox certificate: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/1.6.15/includes/abstracts/abstract-wc-gateway-ppec.php#L243

However any action where the certificate is read / processed it's used directly without passing it through base64 decode first. For example here: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/1.6.15/includes/abstracts/abstract-wc-gateway-ppec.php#L289

Since that fails it returns the error that the certificate is invalid. Since the certificate is already base64 encoded it seems unnecessary to do this again. I tested by removing the `base64_encode` function when saving the certificate. 

After doing so I was able to connect to PayPal and successfully complete a payment using a certificate file.

The workaround to using a certificate is to switching to a signature instead. However each PayPal account can only use either a signature or a certificate (not both). So when the same PayPal account is also connected to a different platform (such as Shopify which requires a certificate), we are unable to connect.

Affected ticket: 2124119-zen

**Comment by mikkamp** [comment]
Another thing I noticed is that when we revisit the settings page after having uploaded a certificate, the certificate info is added in the description, see: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/1.6.15/includes/settings/settings-ppec.php#L326

We have to hover over the `?` to see that description so at initial glance we don't see that a certificate is already uploaded.

For the Sandbox mode it doesn't show any feedback when a certificate file has been uploaded. It would be nice to at the very least have the same description.

**Comment by MarkCanada** [comment]
I would suggest to just use decode on getting the certificate for starters.
This would keep the encoding working just in case there's a bad file uploaded that could break something.?
And maybe a checkmark or some text showing behind the file upload path to indicate a certificate is saved.
But definitely the decode first to get the functionality fixed right away.

**Comment by allendav** [comment]
Changing to low priority since most merchants do not use certificates to my knowledge

**Comment by MarkCanada** [comment]
Very disappointing to have it downgraded to low since merchants who use certificates are blocked from using their account and need to set up a second one while the proposed bugfix should be easy to implement for someone who knows/works the plugins code.
Also very disappointed that nobody from PayPal takes the time to fix this.

**Comment by Vikilator** [comment]
Hello,
Do you mind telling me how do I remove the base64_encode function. I created a website with wordpress using woocommerce hosted at hostgator. I didn't notice until today the shopping cart is not working. I have been searching for an answer and the closest to my problem I believe is the situation mentioned here. Thanks.
