### ISSUE TITLE
Cancelling an order should NOT run a refund

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-paypal-express-checkout#585]
A recent [change](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/574/files), automatically refunds an order when the Cancelled status is set in the order.

The core functionality of an order being “Cancelled” was there was no refund, the stock was just changed.

Store owners who are used to just cancelling orders will now start seeing refunds happen where previously they wouldn’t have

Same as https://github.com/woocommerce/woocommerce-gateway-stripe/issues/900

cc @dougaitken

**Comment by DanReyLop** [comment]
PayPal just fails silently when you try to call `cancel_payment` on a captured payment. See here: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/includes/class-wc-gateway-ppec-admin-handler.php#L214

As such, I don't think this presents a real issue in the PayPal extension, at least not a "High Priority" one.

**Comment by dechov** [comment]
So this can be fixed by modifying that function summary from "Cancel authorization" to "Cancel authorization if one is present" (and similar for `capture_payment`), is that correct?

**Comment by DanReyLop** [comment]
I think changing the `cancel_payment` function name to `cancel_authorization` should be enough to clarify things. The comment is correct: "Cancel authorization" implies it will cancel an authorized payment but do nothing otherwise. On the other hand, it wouldn't hurt to be more explicit in the comment :)
