### ISSUE TITLE
Missing email when checking out without PayPal Account

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce-gateway-paypal-express-checkout#587]
When paying using the Express Checkout method, such as through the Smart Payment Buttons or from the Cart. We get an option to login to a PayPal account or pay directly filling in all the card/billing details.

When we choose the later options and fill in all the fields including "Email" and then select the option not to create a PayPal account. When we are redirected back to the WooCommerce site to complete the payment the Billing Email address is missing. When we try to complete the checkout we get the error:

```
Billing Email address is a required field.
```

Here is the test with a digital product, in this case we don't need a shipping address, so only the name is passed on from PayPal.

![image](https://user-images.githubusercontent.com/11388669/60275236-835d9780-98f1-11e9-8144-e15c0b1467db.png)

And here is the same with a physical product (here we selected the option in PayPal to ship to billing address):

![image](https://user-images.githubusercontent.com/11388669/60275992-a5a3e500-98f2-11e9-85c6-95a86b62263b.png)

If we pay with a PayPal account in either of these two cases then the Email address is passed.

In each of these two cases only the name is passed to WooCommerce, if we look at the log files we can confirm this and see the Email address is not passed in the response from PayPal:

```
06-27-2019 @ 14:21:09 - WC_Gateway_PPEC_Client::_process_response: acknowleged response body: Array
(
    [TOKEN] => EC-AAA620914D243364Y
    [BILLINGAGREEMENTACCEPTEDSTATUS] => 0
    [CHECKOUTSTATUS] => PaymentActionNotInitiated
    [TIMESTAMP] => 2019-06-27T14:21:09Z
    [CORRELATIONID] => 999b59aa66fc
    [ACK] => Success
    [VERSION] => 120.0
    [BUILD] => 53072421
    [PAYERID] => AAA5JZAN8GGH4
    [PAYERSTATUS] => unverified
    [FIRSTNAME] => Woo
    [LASTNAME] => Test
    [COUNTRYCODE] => US
    [ADDRESSSTATUS] => Confirmed
    [CURRENCYCODE] => USD
    [AMT] => 10.55
    [ITEMAMT] => 10.00
    [SHIPPINGAMT] => 0.00
    [HANDLINGAMT] => 0.00
    [TAXAMT] => 0.55
    [INSURANCEAMT] => 0.00
    [SHIPDISCAMT] => 0.00
    [INSURANCEOPTIONOFFERED] => false
    [L_NAME0] => Digital
    [L_QTY0] => 1
    [L_TAXAMT0] => 0.00
    [L_AMT0] => 10.00
    [PAYMENTREQUEST_0_CURRENCYCODE] => USD
    [PAYMENTREQUEST_0_AMT] => 10.55
    [PAYMENTREQUEST_0_ITEMAMT] => 10.00
    [PAYMENTREQUEST_0_SHIPPINGAMT] => 0.00
    [PAYMENTREQUEST_0_HANDLINGAMT] => 0.00
    [PAYMENTREQUEST_0_TAXAMT] => 0.55
    [PAYMENTREQUEST_0_INSURANCEAMT] => 0.00
    [PAYMENTREQUEST_0_SHIPDISCAMT] => 0.00
    [PAYMENTREQUEST_0_SELLERPAYPALACCOUNTID] => seller@email.test
    [PAYMENTREQUEST_0_INSURANCEOPTIONOFFERED] => false
    [L_PAYMENTREQUEST_0_NAME0] => Digital
    [L_PAYMENTREQUEST_0_QTY0] => 1
    [L_PAYMENTREQUEST_0_TAXAMT0] => 0.00
    [L_PAYMENTREQUEST_0_AMT0] => 10.00
    [PAYMENTREQUESTINFO_0_ERRORCODE] => 0
)
```

I'm able to reproduce this scenario in Sandbox mode. The user that reported the issue said they were only experiencing it in Sandbox mode and not in live mode (we still need to confirm that in live mode they didn't use a PayPal account login instead).

I'm not sure what would be the best way to resolve this issue if PayPal isn't passing the email address which the user entered. But as it is now it prevents checkout from being completed unless the user uses a PayPal account.

Affected ticket: 2110792-zen

**Comment by dechov** [comment]
I was able to reproduce this last week, but no longer can – it may have been fixed on PayPal's end.

Can you confirm @mikkamp?

**Comment by mikkamp** [comment]
Thanks for looking into this issue. I tested this again today, and was unable to reproduce when using identical steps. So it does look like it has been adjusted by PayPal. Closing for now.
