### ISSUE TITLE
Synchronise Renewals Not Supported ATM

### ISSUE THREAD

**Issue by chrisspiegl** [woocommerce/woocommerce-gateway-paypal-express-checkout#592]
Hello,

I am delighted to see that PayPal Subscriptions for download/virtual products are now supported. However, I noticed that apparently Synchronise renewals are not a thing with PayPal? Is this something that can be added?

I tried this with the same product and switching the setting to sync to 1st of the months and not sync at all and in the checkout process, it offered PayPal only when Sync Renewals were turned off for the subscription I was trying to make.

PayPal CHeckout Version: 1.6.16
WooCommerce Version: 3.6.5
WooCommerce Subscriptions Version: 2.5.7

Thanks to all putting in the effort for the Subscription support in the first place,

Chris

**Comment by chrisspiegl** [comment]
Hello, is there some way to test this?  Gather more information? To support progress on this?
Thank you ❤.

**Comment by allendav** [comment]
@LCmry - is this likely more a Subscriptions issue than a PayPal Express Checkout issue?

**Comment by LCmry** [comment]
@allendav it looks like this is the same as #367 . This looks like a gateway issue, it is being unset because the cart total is $0. https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/includes/class-wc-gateway-ppec-checkout-handler.php#L554

**Comment by chrisspiegl** [comment]
Agreed, I am closing this in favor of #367 . The issue seems to be the exact same.
