### ISSUE TITLE
Double stock reduce when IPN and PDT notifications are enable

### ISSUE THREAD

**Issue by miguelfspinto** [woocommerce/woocommerce-gateway-paypal-express-checkout#595]
When IPN and PDT notifications are enabled , the stock is reduced twice.

Stock levels reduced: High-waist wide leg trousers – S (1904LAG60240154B) 0→-1, Fringes short sleeve t-shirt – S (1904SIX58760129B) 1→0
July 28, 2019 at 9:28 am	Delete note

Stock levels reduced: High-waist wide leg trousers – S (1904LAG60240154B) 1→0, Fringes short sleeve t-shirt – S (1904SIX58760129B) 2→1
July 28, 2019 at 9:28 am	Delete note

PDT payment completed
July 28, 2019 at 9:27 am	Delete note

IPN payment completed
July 28, 2019 at 9:27 am	Delete note

**Comment by menakas** [comment]
@miguelfspinto 
Do you still see this behaviour? I tried replicating this issue, but I could not.

Steps I followed:
1. Login into merchant PayPal account
1. Go to Settings icon on top right-> Account Settings-> Website Payments-> Website Preferences->Update
1. Turn Auto return on and save the return URL
1. Turn Payment Data Transfer On.
1. Try purchasing a product via PayPal and check for notifications and stock reduction.
1. Go to Settings icon on top right-> Account Settings-> Website Payments-> Instant Payment Notifications->Update
1. Set the Notification URL and choose "Receive IPN Messages(Enabled)"
1. Now purchase the same product.
1. The stock is reduced by 1.

Is this happening in any specific scenario?

**Comment by miguelfspinto** [comment]
This was already solved in this issue: https://github.com/woocommerce/woocommerce/pull/24249
Best regards,
Miguel Pinto
