### ISSUE TITLE
Improve the plugin description, lose the odd link perhaps

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-paypal-express-checkout#605]
The plugin description displayed in Plugins is sad and has an odd unlinked link. Let's do better

<img width="1416" alt="Screen Shot 2019-08-08 at 10 23 00 AM" src="https://user-images.githubusercontent.com/1595739/62725146-71c7df00-b9c9-11e9-826a-fb31da04769e.png">

cc @bmccotter

**Comment by allendav** [comment]
@bmccotter or @californiakat - could you suggest better copy for this?

**Comment by bmccotter** [comment]
How's this? "PayPal Checkout now adapts to consumer shopping habits by presenting their most relevant payment buttons during checkout."

**Comment by californiakat** [comment]
@allendav Sorry for the delay. After having a look at how we present other PayPal descriptions, and reviewing what's unique about PayPal Checkout via the docs and product page, I suggest:

Accept all major credit and debit cards, plus Venmo and PayPal Credit in the US, presenting options in a customizable stack of payment buttons. Fast, seamless, and flexible.
