### ISSUE TITLE
Remove unnecessary PayPal API hits

### ISSUE THREAD

**Issue by MezMerrit** [woocommerce/woocommerce-gateway-paypal-express-checkout#627]
**Is your feature request related to a problem? Please describe.**
Non Woo Commerce pages don't need to do a round trip to the API server. It slows down page loads and I'm sure PayPal would appreciate tens of thousands fewer unnecessary API hits from Wordpress websites.

**Describe the solution you'd like**
I'm not sure how others prefer to use the PayPal gateway on their websites, so I'm not sure if writing the feature into the plugin is necessary. Personally, I'd just like a code snippet to limit which pages the PayPal gateway is loaded on. 

**Describe alternatives you've considered**
I've searched high and low for the hooks to use, but nothing appears to work. Either I'm calling it too early or too late or perhaps there's more than one hook?

**Additional context**
Adding requested code snippet to the docs so it can be easily found by others might be a huge time saver for both users and developers.

**Comment by allendav** [comment]
Hi @MezMerrit - thanks for raising the concern - a few questions:

- what non-woo-commerce pages for example? like blog posts? is it possible a cart with PayPal buttons is present on those pages?
- what requests are you seeing? A screengrab showing the Network tab of the JavaScript console would help

**Comment by allendav** [comment]
Scoring as low for now until feedback warrants higher severity.

**Comment by jorgeatorres** [comment]
Closing (after > 1y of inactivity). @MezMerrit: Feel free to re-open if you have additional details that could help us better diagnose this.
