### ISSUE TITLE
Add other (APM's) in EU specifically (Bancontact, EPS, Giropay, iDeal, MyBank, Przelewy24, Sofort)

### ISSUE THREAD

**Issue by bmccotter** [woocommerce/woocommerce-gateway-paypal-express-checkout#632]
Per PayPal's Request:

Update integration to enable Alternate payment methods in EU specifically (Bancontact, EPS, Giropay, iDeal, MyBank, Przelewy24, Sofort)

p7bbVw-3rk-p2

**Comment by mattallan** [comment]
These payment methods were added as part of upgrading the javascript SDK. Closed with #668
