### ISSUE TITLE
Update deprecated SDK: Store `client-id` and use it to load the new JavaScript SDK

### ISSUE THREAD

**Issue by reykjalin** [woocommerce/woocommerce-gateway-paypal-express-checkout#645]
Child issue of #626. 

We need to store a [`client-id`](https://developer.paypal.com/docs/subscriptions/reference/customize-the-sdk/#client-id) to be able to [load in the new JavaScript SDK](https://developer.paypal.com/docs/checkout/integrate/#2-add-the-paypal-javascript-sdk-to-your-web-page).

We may also need — or want — to use a [`merchant-id`](https://developer.paypal.com/docs/subscriptions/reference/customize-the-sdk/#merchant-id) to identify the merchant.

Master thread: p7bbVw-3xH-p2.

#### Issues that have to be resolved before this one

- [ ] Figure out what sort of implications storing and using the necessary data will have (#646).

**Comment by reykjalin** [comment]
I think we want to include the `merchant-id` parameter. From the docs (emphasis mine):

>Use the this parameter [merchant-id] only for partner, marketplaces, **and cart solutions**, when you are acting on behalf of another merchant to facilitate their PayPal transactions.
>
><cite>[PayPal merchant-id Docs](https://developer.paypal.com/docs/subscriptions/reference/customize-the-sdk/#merchant-id)</cite>

**Comment by mattallan** [comment]
Closed withe #668
