### ISSUE TITLE
Understand how `client-id` and `merchant-id` can and will be used

### ISSUE THREAD

**Issue by reykjalin** [woocommerce/woocommerce-gateway-paypal-express-checkout#646]
Child issue of #645. 

This is more of an exploratory issue mostly meant for documentation purposes. We need to understand what the `client-id` and `merchant-id` parameters are, when and how we can store them, and how much we'll need to restructure our code to accommodate the change.

We may need to include some data migration when updating the plugin from versions not using the new JavaScript SDK.

**Comment by mattallan** [comment]
Closed with #668
