### ISSUE TITLE
Update deprecated SDK: Pass correct `disable-funding` and `disable-card` options to new JavaScript SDK

### ISSUE THREAD

**Issue by reykjalin** [woocommerce/woocommerce-gateway-paypal-express-checkout#647]
Child issue of #626. 

Instead of passing the `funding.allowed` and `funding.disallowed` options to the `paypal.Button.render()` function we should now pass [`disable-funding`](https://developer.paypal.com/docs/checkout/reference/customize-sdk/#disable-funding) and [`disable-card`](https://developer.paypal.com/docs/checkout/reference/customize-sdk/#disable-card) as query parameters when [loading the SDK](https://developer.paypal.com/docs/checkout/integrate/#2-add-the-paypal-javascript-sdk-to-your-web-page) from PayPal.

Since we're moving from allowed/disallowed funding options to disabled funding and disabled card options it seems we may need to design some additional UX around this in the settings — i.e. have options available to disable specific cards or specific funding options.

**Comment by mattallan** [comment]
Closed with #668
