### ISSUE TITLE
Update deprecated SDK: Show order confirmation dialog at appropriate times

### ISSUE THREAD

**Issue by reykjalin** [woocommerce/woocommerce-gateway-paypal-express-checkout#648]
Child issue of #626. 

In the current implementation we show a confirmation page whenever the customer clicks the PayPal buttons and one of two conditions is fulfilled:

1. The customer isn't on the checkout page.
1. The customer is in the mini cart.

https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/a6b4b195cdc41b5b94202d7acc63ad3e8abd4606/assets/js/wc-gateway-ppec-smart-payment-buttons.js#L63

https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/a6b4b195cdc41b5b94202d7acc63ad3e8abd4606/assets/js/wc-gateway-ppec-smart-payment-buttons.js#L73

Instead of deciding whether to show the confirmation page or not when rendering the buttons, we now have to [pass the correct parameter](https://developer.paypal.com/docs/checkout/integration-features/confirmation-page/) when [loading the new JavaScript SDK](https://developer.paypal.com/docs/checkout/integrate/#2-add-the-paypal-javascript-sdk-to-your-web-page).

**Comment by mattallan** [comment]
Closed with #668
