### ISSUE TITLE
Update deprecated SDK: Add polyfills for built-in browser fetch and Promise

### ISSUE THREAD

**Issue by reykjalin** [woocommerce/woocommerce-gateway-paypal-express-checkout#649]
Child issue of #626. 

PayPal is [deprecating `paypal.request` and `paypal.Promise`](https://developer.paypal.com/docs/checkout/reference/upgrade-integration/#6-fix-deprecations) in favor of using the built-in browser equivalents — `fetch` and `Promise`.

We plan on supporting all major browsers, including IE11 (p7bbVw-3nP-p2). Since IE11 will be supported for the [foreseeable future](https://href.li/?https://support.microsoft.com/en-us/help/17454/lifecycle-faq-internet-explorer) and it supports neither `fetch` nor `Promise` we will have to add polyfills for those built-ins.

**Comment by mattallan** [comment]
Closed #668

See related commits: dec9b7d, 32ccf60, d128be4
