### ISSUE TITLE
Update deprecated SDK: Show cancellation page when appropriate

### ISSUE THREAD

**Issue by reykjalin** [woocommerce/woocommerce-gateway-paypal-express-checkout#650]
Child issue of #626. 

Redirect to the appropriate page in the [`onCancel` method](https://developer.paypal.com/docs/checkout/integration-features/cancellation-page/) passed to the `paypal.Buttons()` using `actions.redirect( '/cancel-page-url' );`.

**Comment by jorgeatorres** [comment]
Handled in #668.
