### ISSUE TITLE
Update deprecated SDK: Catch and handle errors during checkout flow

### ISSUE THREAD

**Issue by reykjalin** [woocommerce/woocommerce-gateway-paypal-express-checkout#651]
Child issue of #626. 

Catch and handle any errors that may happen during the checkout flow, preventing customers from completing the flow, by implementing the [`onError()` function](https://developer.paypal.com/docs/checkout/integration-features/handle-errors/) passed to `paypal.Buttons()`.

Note:

>This error handler [`onError()`] is a catch-all. Errors at this point are not expected to be handled beyond showing a generic error message or page.

**Comment by jorgeatorres** [comment]
Handled in #668.
