### ISSUE TITLE
PayPal Checkout causing fatal error in AutomateWoo

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/woocommerce-gateway-paypal-express-checkout#652]
**Describe the bug**
PP Checkout causing fatal error when used alongside:

* AutomateWoo
* AutomateWoo - Subscription Addon (https://github.com/Prospress/automatewoo-subscriptions/ --> Developed by Prospress)

The error in question is as follows:

```
2019-12-20T05:31:57+00:00 CRITICAL Uncaught Error: Call to a member function get_id() on bool in /nas/content/live/seventhrstage/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-admin-handler.php:44
Stack trace:
#0 /nas/content/live/seventhrstage/wp-includes/class-wp-hook.php(288): WC_Gateway_PPEC_Admin_Handler->add_capture_charge_order_action(Array)
#1 /nas/content/live/seventhrstage/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)
#2 /nas/content/live/seventhrstage/wp-content/plugins/automatewoo/includes/actions/order-trigger-action.php(31): apply_filters('woocommerce_ord...', Array)
#3 /nas/content/live/seventhrstage/wp-content/plugins/automatewoo/includes/abstracts/action.php(239): AutomateWoo\Action_Order_Trigger_Action->load_fields()
#4 /nas/content/live/seventhrstage/wp-content/plugins/automatewoo/includes/abstracts/action.php(222): AutomateWoo\Action->get_fields()
#5 /nas/content/live/seventhrstage/wp-content/plugins/automatewoo/includes/workflow.php(970): AutomateWoo\Action in /nas/content/live/seventhrstage/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-admin-handler.php on line 44
```

And relates to the following line:

https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/includes/class-wc-gateway-ppec-admin-handler.php#L44

@madeincosmos also outlined the following line in AW for reference:

https://github.com/Prospress/automatewoo/blob/develop/includes/actions/order-trigger-action.php#L30:L32

> So PayPal is trying to pull order id from POST parameters
> but AutomateWoo is calling the same filter outside the context of a specific order, so there’s no order ID
> if that’s the case, PayPal should fail silently 

**To Reproduce**
Steps to reproduce the behaviour:
1. Install AutomateWoo
2. Install Subscriptions
3. Install AutomateWoo -- Subscriptions Addon
4. Ensure PP Checkout is active
5. Create a new Workflow in AutomateWoo
  * Trigger: Subscription Order Paid
  * Subscription Order type: Parent
  * Action: Trigger Order Action
  * Order Action: Generate download permissions
6. Click "Save" to save the workflow. 
7. Once the page loads again, notice the error message.

**Expected behaviour**

I expected PP Checkout to not cause fatal errors. 

**Screenshots**

![https://d.pr/i/a5VTVQ](https://d.pr/i/a5VTVQ+)
Full Image: https://d.pr/i/a5VTVQ

![https://d.pr/i/t3Bb8e](https://d.pr/i/t3Bb8e+)
Full Image: https://d.pr/i/t3Bb8e

**Additional context**
2555678-zen

**Comment by madeincosmos** [comment]
@RiaanKnoetze I've added a PR, let me know if it solves the problem for you.
