### ISSUE TITLE
`woocommerce_default_address_fields` not checking if cart is available

### ISSUE THREAD

**Issue by jrick1229** [woocommerce/woocommerce-gateway-paypal-express-checkout#655]
**Forum link:** https://wordpress.org/support/topic/error-in-admin-order-display-due-to-wc-cart-null/

**Describe the bug**
A compatibility issue was found between PayPal Checkout and a third-party plugin, [Checkout Field Editor (Checkout Manager) for WooCommerce](https://wordpress.org/plugins/woo-checkout-field-editor-pro/).
Support was reached for the third-party plugin and we were given this feedback:

> The issue is due to the calling of cart content in the hook “woocommerce_default_address_fields“ directly without checking whether the cart is available or not. It is required to check whether the cart content is available or not.
> 
> The default address field hook (woocommerce_default_address_fields) is used in the get_address_fields() function. In WooCommerce, this function is used to get all the fields available in the billing and shipping section.
> 
> In our plugin, we are also calling the above function to get the all the fields available (default + custom) in the each section (billing and shipping).
> 
> We suggest you to contact the PayPal plugin support inorder to check this issue further. We hope they will be able to help you.

**Additional context**
I'm unsure if there is an actual issue with what support suggested from ThemeHigh, but I wanted to bring attention to this in case there is.

Let me know if I can request any additional details!

**Comment by james-allan** [comment]
I believe this is fixed by https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/654. 

Looking at the forum thread the specific error is that we're not checking that the cart object exists before trying to access it. 

```
Notice: Trying to get property of non-object in public_html/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-plugin.php on line 459
```

This is because that third-party plugin gets all the checkout fields, outside of the cart context.
