### ISSUE TITLE
Billing address fields not validating correctly

### ISSUE THREAD

**Issue by thelar** [woocommerce/woocommerce-gateway-paypal-express-checkout#667]
**Describe the bug**
I'm getting an issue with the plugin claiming that Billing address fields are 'required' even though they are filled in. 

There is some customisation on my checkout page because I am validating UK customers addresses and disabling the address fields to prevent tampering, I believe that this plugin is unable to validate the Address line 1, The town/city and the postcode because the fields are disabled.

**To Reproduce**
1. Go to https://4x4tyres.chapterserver2.co.uk
2. Add some products to your basket
3. Go to the Checkout page and complete all required fields selecting a UK address
4. Click on Paypal and place the order 
5. You will see that it says Street Address, Town and Postcode are required fields even though they were complete 

**Expected behavior**
Expected behaviour is for values from disabled fields to be read correctly and not to display an error message about missing address fields

**Screenshots**
<img width="1264" alt="Screenshot 2020-01-30 at 13 41 22" src="https://user-images.githubusercontent.com/2960524/73454630-5b8e5080-4366-11ea-81a5-01bd90547246.png">

**Environment (please complete the following information):**
 - WordPress Version - 5.2.2
 - WooCommerce Version - 3.8.1
 - PayPal Express Checkout Plugin Version - 1.6.18
 - Browser [e.g. chrome, safari] and Version - All browsers
 - Any other plugins installed - Yes lots, Sagepay, Deko, Klarna

**Additional context**
The reason for the customisation on my Checkout page is so to detect commercial or residential customers via integration with PCA api - I'm then applying different shipping rates accordingly, whilst I appreciate that you will probably say that the fact the fields are disables is the root cause of this problem, this is necessary in order to stop customers accessing the wrong (cheaper) shipping rates and is a vital part of the sites functionality

**Comment by LCmry** [comment]
Hi @thelar, I followed the steps to reproduce, but have been successfully directed to PayPal and not encountered any errors. Please let me know if there are any other steps to reproduce.

**Comment by LCmry** [comment]
Hi @thelar, I'm going to close this. If this is still an issue, please reopen.
