### ISSUE TITLE
How to update Paypal Express Checkout settings through Woocommerce REST API?

### ISSUE THREAD

**Issue by phamvietloi** [woocommerce/woocommerce-gateway-paypal-express-checkout#672]
i found in the Woocommerce REST API document that payment gateways can be updated through WC API (http://woocommerce.github.io/woocommerce-rest-api-docs/?python#update-a-payment-gateway)

I want to update Paypal Email in settings by below Python code: 
data = {
    'enabled': True,
    'settings': {
        'api_subject': {
            'id': 'api_subject',
            'value': 'example@example.com'
        }
    }
}

print(wcapi.put('payment_gateways/ppec_paypal', data=data).json())

![image](https://user-images.githubusercontent.com/43338839/73605164-60a10900-45cd-11ea-9293-36899d07aac0.png)

But it turned blank after run the code. What should I do now?

**Comment by james-allan** [comment]
Hey @phamvietloi 

I've run some tests on my local environment and the format should look something like this:

```
{
	"enabled": true,
	"settings":{
		"api_subject":"example@example.com"
	}
}
```

Basically where I think it's going wrong for you is inside the settings level object, it's just key-value pairs, not further objects. 

Let me know if that fixes it for you. In the meantime, I'll close this issue.
