### ISSUE TITLE
Make description of "Enable PayPal Mark" clearer

### ISSUE THREAD

**Issue by jorgeatorres** [woocommerce/woocommerce-gateway-paypal-express-checkout#675]
Via `p1580974407184800-slack-lambda`:

> Hi team :wave:
> I’m a bit confused with PayPal Checkout behaviour and wondering if you can help. So even if PayPal Checkout is enabled as a gateway and properly configured, it won’t show up on checkout until "Enable the PayPal Mark on regular checkout" is checked.
> [Our docs say](https://docs.woocommerce.com/document/paypal-express-checkout/#section-7) that this setting only adds a logo to the checkout page, not enable/disable PayPal Checkout at all:
>
> > 6. Tick the checkbox to Enable PayPal Mark if you would like to display the PayPal name during checkout on your site, which can give customers assurance.
>
> [...]
> If that’s indeed by design, we need to at least update the docs and the ? wording in wp-admin. > [...]
>
>![image](https://user-images.githubusercontent.com/184724/73948744-2474ed80-48d8-11ea-9234-dd9287ae1f57.png)

----

While on the settings screen the "Enable the PayPal Mark on regular checkout" checkbox is checked by default, maybe we should make it clear that it controls whether PayPal EC appears as an option during checkout or not.

As suggested, we can achieve this by adjusting our docs and/or the on-screen setting description.

**Comment by codestor4** [comment]
My understanding Paypal Mark option is that it controls whether the Paypal Checkout option is displayed on the regular checkout page. 

If so, we can change the plugin option description from `Enable the PayPal Mark on regular checkout` to `Show PayPal Checkout payment option on the regular checkout page`. This should be much clearer than the previous description.

Currently "PayPal Mark" is not mentioned in our [documentation](https://docs.woocommerce.com/document/paypal-express-checkout/). We can add it there as well.

I'll make a quick PR for this change.

**Comment by treibalen** [comment]
@codestor4 Just stumbled into another ticket where it wasn't clear what this setting does. I submitted a doc update request here: p1602516209122700-slack-CSP74N77C
