### ISSUE TITLE
Updates ran before dependency check results in undefined constant warning

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-gateway-paypal-express-checkout#680]
**Describe the bug**
[Customers in the forums](https://wordpress.org/support/topic/woocommerce-update-error/) are getting this warning:

> Warning: Use of undefined constant WC_VERSION – assumed ‘WC_VERSION’ (this will throw an Error in a future version of PHP) in .../wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-plugin.php on line 138

I looked into this, and it appears that `run_updater` is run before `bootstrap`, which runs `_check_dependencies`. 

I am not sure if putting `run_updater` after the `_check_dependencies` will completely resolve this, though, as `WC_VERSION` should already be defined if WooCommerce core is active. 

**To Reproduce**
I was only able to reproduce by deactivating WooCommerce, then editing code to make some checks to evaluate as false to get to line 138.

**Comment by jorgeatorres** [comment]
Fixed with #682.
