### ISSUE TITLE
1.6.19 plugin seems to contain `trunk` directory

### ISSUE THREAD

**Issue by jenkoian** [woocommerce/woocommerce-gateway-paypal-express-checkout#681]
We use [wpackagist](https://wpackagist.org/search?q=woocommerce-gateway-paypal-express-checkout&type=any&search=) to install and update our plugins and upon upgrading to the 1.6.19 version of this plugin there is a `trunk` directory being included which seems to just be a duplication of the top level file structure. 

This only seems to occur for this version of this plugin, although it doesn't seem to be a case with this github repo.

Not sure if something has changed in the way you package up the plugin to send to WP plugin repo but would be great if you could remove this superfluous directory?

**Comment by jenkoian** [comment]
You can see here that `1.6.19` contains a `trunk` directory https://plugins.trac.wordpress.org/browser/woocommerce-gateway-paypal-express-checkout/tags/1.6.19 where as this doesn't exist for `1.6.18` https://plugins.trac.wordpress.org/browser/woocommerce-gateway-paypal-express-checkout/tags/1.6.18

**Comment by james-allan** [comment]
Hi @jenkoian. 

Thanks for the report. There must have been an error in the way we deployed 1.6.19. We'll look into it and get that fixed up.

**Comment by LCmry** [comment]
A fix was deployed with 1.6.20.
