### ISSUE TITLE
Cheatin' huh? generated at class-wc-gateway-ppec-cart-handler.php, line 154

### ISSUE THREAD

**Issue by AljosaK** [woocommerce/woocommerce-gateway-paypal-express-checkout#687]
I am getting Express checkout error when using PayPal checkout button. I have tried to debug it and found out that error is thrown at: 
/woocommerce-gateway-paypal-express-checkout/assets/js/wc-gateway-ppec-smart-payment-buttons.js

It basically throws: **response.data is undefined** at line 128.			
Code that throws an erorr:
```
						if ( ! response.success ) {
							var messageItems = response.data.messages.map( function( message ) {
								return '<li>' + message + '</li>';
							} ).join( '' );

							showError( '<ul class="woocommerce-error" role="alert">' + messageItems + '</ul>', selector );
							return null;
						}
```

Full error: 
```
ppxo_unhandled_error 
Object { stack: "response.data is undefined\npayment/</<@https://mysite.com/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/assets/js/wc-gateway-ppec-smart-payment-buttons.js?ver=1.6.20:129:27\ndispatch@https://www.paypalobjects.com/api/checkout.js:1073:34\nresolve@https://www.paypalobjects.com/api/checkout.js:995:10\nZalgoPromise/<@https://www.paypalobjects.com/api/checkout.js:949:19\nxhrLoad@https://www.paypalobjects.com/api/checkout.js:1825:14\n\n_RECEIVE_MESSAGE_TYPE[conf.b.POST_MESSAGE_TYPE.RESPONSE]@https://www.paypalobjects.com/api/checkout.js:8027:15\nreceiveMessage@https://www.paypalobjects.com/api/checkout.js:8132:38\nmessageListener@https://www.paypalobjects.com/api/checkout.js:8156:17\n", errtype: "[object Error]", timestamp: 1582564304153, windowID: "092225c078", pageID: "620597dd78", prev_corr_ids: "3a72c78ac9ba6", referer: "https://mysite.com", host: "www.sandbox.paypal.com", path: "/smart/button", env: "sandbox", … }
logger.js:63:34
Error: response.data is undefined
payment/</<@https://mysite.com/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/assets/js/wc-gateway-ppec-smart-payment-buttons.js?ver=1.6.20:129:27
dispatch@https://www.paypalobjects.com/api/checkout.js:1073:34
resolve@https://www.paypalobjects.com/api/checkout.js:995:10
ZalgoPromise/<@https://www.paypalobjects.com/api/checkout.js:949:19
xhrLoad@https://www.paypalobjects.com/api/checkout.js:1825:14

_RECEIVE_MESSAGE_TYPE[conf.b.POST_MESSAGE_TYPE.RESPONSE]@https://www.paypalobjects.com/api/checkout.js:8027:15
receiveMessage@https://www.paypalobjects.com/api/checkout.js:8132:38
messageListener@https://www.paypalobjects.com/api/checkout.js:8156:17
serialize.js:175:14
Error: response.data is undefined
payment/</<@https://mysite.com/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/assets/js/wc-gateway-ppec-smart-payment-buttons.js?ver=1.6.20:129:27
dispatch@https://www.paypalobjects.com/api/checkout.js:1073:34
resolve@https://www.paypalobjects.com/api/checkout.js:995:10
ZalgoPromise/<@https://www.paypalobjects.com/api/checkout.js:949:19
xhrLoad@https://www.paypalobjects.com/api/checkout.js:1825:14
```
After debugging a bit response is "Cheatin&#8217; huh?" . Debugging further I found out that public method wc_ajax_start_checkout() is called and there is where wp_die( __( 'Cheatin&#8217; huh?', 'woocommerce-gateway-paypal-express-checkout' ) ); is generated. I did a bit more debugging and found out that no $_POST data is sent to this function ($_POST is empty) and that's the reason it happens, but couldn't get why it happens and how to fix it.

I have tested it with and without plugins and with and without default theme. Same thing happens when WP-Rocket's caching is off and on. 

Verison of WordPress: 5.3.2
Version of plugin: 1.6.20

Could you please help me out with this case, how to overcome error and make button work again as expected.

Thanks in advance

**Comment by LCmry** [comment]
Hi @AljosaK , thanks for the report.

Could you provide the steps that you are following to reproduce this error? Including the WooCommerce version and from which page the PayPal button is being clicked (Cart, Checkout, etc).

**Comment by AljosaK** [comment]
Hey @LCmry , thank you for the prompt answer.

It happens on each PayPal checkout button (Cart, checkout, on each product).

Basically I go to products (one of scenarios) and click "PayPal buy now" button and get this error. Same thing happens if I add multiple products and go to Cart.

WoCommerce version that is currently installed is **Version 3.9.2**

**Comment by james-allan** [comment]
Hi @AljosaK, 

I haven't been able to replicate this issue. 

>  I did a bit more debugging and found out that no $_POST data is sent to this function ($_POST is empty) and that's the reason it happens, but couldn't get why it happens and how to fix it.

This is definitely the cause of the issue. `$_POST` shouldn't be empty and in all my tests, it's not empty. 

Could you try deductive troubleshooting steps by deactivating all plugins except for the essential ones (WooCommerce, PayPal Checkout), activate a default theme and try to see if the issue still happens? 

If that doesn't fix it then there might be something bigger at play like server security that's stripping out the `$_POST` data. 

If you want to continue debugging, you could also console log, the `data` variable on line 118 in wc-gateway-ppec-smart-payment-buttons.js. 

You should see something like this in the console log (`nonce=5ea9abc1234&from_checkout=no`), if you click the PayPal button on a product page.

**Comment by AljosaK** [comment]
Hey @james-allan , sorry for responding a bit late.

Yes, I have tried by deactivating both plugins and themes (activating default one) but nothing has changed.

When I console log data I get nonce=3eac23dfw1&from_checkout=no (as you have mentioned) but

**Comment by james-allan** [comment]
Hi @AljosaK.

So if the `nonce` and `from_checkout` params are present there and are being sent via the ajax request and you're not getting any `POST` data where the `cheatin' huh?` error is coming from, some other process must be stripping out those params between when they are sent to the server and the `wc_ajax_start_checkout()` function is called. 

I'm not sure if that's a host-related security thing or some third-party code elsewhere, in any case, it's not something I can replicate and it's not something that can be attributed to an issue in the plugin itself. 

The only further debugging suggestion I can make is to look further into the ajax request when it leaves the JS, when it hits the server and narrow down when the `$_POST` data is cleared.
