### ISSUE TITLE
PayPal Credit option should be allowed for PR as it's part of the US

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-paypal-express-checkout#691]
**Describe the bug**

With the following set of circumstances, the PayPal Credit option is greyed out:

- They are based in Puerto Rico
- Have PayPal Business account
- Currency USD

This is because the PayPal credit option checks specifically if the country is set to US.

Further background:

Puerto Rico has a two digit ISO 3166-1 code so it is seen as a “country”. There is a long history of PR and WooCommerce so we’d need to add it that way rather than as part of the US, but in short, my guess is we need to add PR to this:
https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/e57d5c1ad057d922de9f4c25d3d3d09229c1804e/includes/functions.php#L80 [[Slack discussion](https://a8c.slack.com/archives/C100MSW86/p1583434164017600)]

**Screenshots**

![image](https://user-images.githubusercontent.com/17844465/76193147-aa3fcd80-61e3-11ea-8101-6fe535eeeeb1.png)

Related ticket: 2765618-zen

**Comment by menakas** [comment]
Via #693
