### ISSUE TITLE
Can I hide the Paypal button when there are no shipping options?

### ISSUE THREAD

**Issue by thelar** [woocommerce/woocommerce-gateway-paypal-express-checkout#699]
Hi,

I am trying to stop customers placing orders when there are no shipping options available on my shop. The way I'm tackling this for my other payment gateways is via the 'woocommerce_order_button_html' filter, for example:

`$selected_shipping = WC()->session->get('chosen_shipping_methods');
    if(in_array(false, $selected_shipping)){
        return '';
    }`

This effectively returns an empty string when there are no available shipping methods, resulting in no button and therefore no ability to place an order.

But I need to do the same thing with Paypal - if there is no available shipping option, then do not show the PayPal button. 

Is there a filter I could use for this?

**Comment by menakas** [comment]
Hi @thelar 

You can use `woocommerce_paypal_express_checkout_hide_button_on_product_page` to hide the smart payment buttons on product page based on shipping options.

Together with `woocommerce_order_button_html` on the checkout page, this should help in hiding the buttons.

Does that help?

**Comment by thelar** [comment]
@menakas Hi, thanks for the reply! I need to hide the Paypal button specifically on the Checkout page, will this filter do that or is there something similar for the Checkout page?

**Comment by menakas** [comment]
Well, I think I understood the requirement wrong. The above filter hides the smart payment button only on product page. 

We could consider adding a similar filter for the checkout page as well, but that would work only in the case of Smart Payment buttons. If you are not using spb, then that filter would not work. 

Have you considered filtering using 'woocommerce_available_payment_gateways' ?

**Comment by james-allan** [comment]
@thelar you could also use the `woocommerce_after_checkout_validation` filter. This filter runs when WC validates the checkout before it processes the checkout request.

An example use: 

```php
add_action( 'woocommerce_after_checkout_validation', function( $data, $errors ) {
	if ( true ) { // Change this to your condition which checks if there are shipping options.
		$errors->add( 'invalid shipping', 'No shipping methods available.' ); // You can change this message to anything you'd like.
	}
}, 10, 2 );
```

**Comment by turn289** [comment]
Hi All , 

I would be very thankful if some one can help with the same situation -There is no effect of the code on paypal button how to edit this to the one you suggested in this post above ? https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/699

This code works for me. It hides the "checkout" button on checkout page if there are no available shipping methods. Goes into your child theme's functions.php.

//Hide checkout button if no shipping is available
add_filter('woocommerce_order_button_html', 'hide_checkout_button__no_shipping_html' );
function hide_checkout_button__no_shipping_html( $button ) {

    $package_counts = array();
    $packages = WC()->shipping->get_packages();
    foreach( $packages as $key => $pkg ) {
        $package_counts[ $key ] = count( $pkg[ 'rates' ] );
    }

    if( in_array( 0, $package_counts ) ) { //no available shipping method
        $button = '';
    }
