### ISSUE TITLE
Subscriptions with $0 initial payment don't redirect to "Confirm your PayPal Order" page

### ISSUE THREAD

**Issue by mattallan** [woocommerce/woocommerce-gateway-paypal-express-checkout#700]
### Describe the bug
While testing https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/698 I noticed a slight difference in behaviour when you purchase a non $0 product using the PayPal Smart Buttons found on the Product or Cart Pages compared to a $0 Subscriptions (i.e. one with a trial)

When purchasing a product > $0 (can be simple or subscription product) the usual flow is you are redirected to PayPal to authenticate a future payment (with a token and payerID given by PayPal), and then return back to a "Confirm your PayPal Order" page to finalise/confirm payment.

Notice the URL contains a `Token` and a `PayerID`.

![](https://d.pr/i/JPxupI+)

When you purchase a Subscription with $0 upfront cost (trial or synced), the customer properly goes to PayPal to authorize payment, but when they return, they go back to the checkout page and then have to select PayPal Checkout again and fill in their card details or login a second time.

Here's a screencast of the two different cases starting with the non-zero purchase: https://d.pr/v/5DL48y

---

The tl;dr version is $0 purchases don't have a `PayerID`. I think this is causing the [`has_active_session()`](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/07041bb6142ca39eb0e6267a268d2a2b5923f784/includes/class-wc-gateway-ppec-checkout-handler.php#L652-L659) function to return false which leads to the "Confirm your PayPal Order" page never being used even though we have a payment token.

### To reproduce

1. Enable Smart Buttons setting
1. Enable Smart Buttons on either Cart or Product pages
1. Add a subscription with a free trial to your cart
1. Click on the PayPal Smart button on the cart page
1. Complete the PayPal payment form
1. Notice you're redirected to the regular checkout page even though we have a `token` in the URL from PayPal
1. Notice the checkout still has every other gateway options listed (FYI Stripe shouldn't be there)
1. Choose PayPal Checkout and notice you need to enter your card details again

### Expected behavior

Because we have authorized the payment and authenticated with PayPal and have a token present, we should be redirected straight to the "Confirm your PayPal Order" page to finalise payment.

I think this is because the `has_active_session()` function requires a `PayerID` to exist.

We may also need to update `maybe_return_from_paypal()` to make sure it's handling orders with $0 payment, similarly to what is being done in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/698

**Environment (please complete the following information):**
 - WordPress Version 5.3.2
 - WooCommerce Version 4.0

**Comment by james-allan** [comment]
> I think this is because the has_active_session() function requires a PayerID to exist.

I can confirm that. When I return from PayPal there is a session, however no PayerID. For example this my session:

```
WC_Gateway_PPEC_Session_Data Object
(
    [source] => cart
    [order_id] => 
    [checkout_completed] => 
    [token] => EC-8C653152AU1234567
    [payer_id] => 
    [expiry_time] => 1584608097
    [use_paypal_credit] => 
)
```

> We may also need to update maybe_return_from_paypal() to make sure it's handling orders with $0 payment, similarly to what is being done in #698

By this do you mean when they return from PayPal, skipping that extra payment step and just processing the payment right then and there?

**Comment by mattallan** [comment]
> however no PayerID

Cool. I wonder if we even need to check for `PayerID` in order to verify it's an active session. Looking for a token may be safer, but maybe even just simplifying it to check the expiry 🤔 

> We may also need to update maybe_return_from_paypal() to make sure it's handling orders with $0 payment, similarly to what is being done in #698
>> By this do you mean when they return from PayPal, skipping that extra payment step and just processing the payment right then and there?

Yeah we might need to look more into what `maybe_return_from_paypal()` it's doing and when it's used. I might be misunderstanding the function

I noticed it's exiting early when [there's no `payerID`](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/07041bb6142ca39eb0e6267a268d2a2b5923f784/includes/class-wc-gateway-ppec-checkout-handler.php#L433) and also calling `do_payment()` without checking the order total, so I wanted to flag it in this issue.

After a second look, it looks like the function does the following:
 - when the customer returns from PayPal, update the customer billing details with the address they entered at PayPal
 - process payment if an orderID is found in the PayPal session (could this be for when they're paying for a failed order?)

Given this function is exiting early for $0 payments (no payerID), it sounds like customer addresses aren't updated? Definitely worth looking into
