### ISSUE TITLE
Upgrade 'Tested up to WooCommerce version'

### ISSUE THREAD

**Issue by rolandog** [woocommerce/woocommerce-gateway-paypal-express-checkout#701]
### Describe the bug
When trying to upgrade from WooCommerce 3.9.2 to 4.0.1, I'm greeted with a warning that _WooCommerce PayPal Checkout Payment Gateway_ has only been tested up to WooCommerce 3.9.

### To reproduce
1. Visit `https://example.com/wp-admin/plugins.php` (with similar setup as described below)
1. Scroll to 'WooCommerce'
1. View following information:

> Heads up! The versions of the following plugins you're running haven't been tested with WooCommerce 4.0. Please update them or confirm compatibility before updating WooCommerce, or you may experience issues:
> Plugin | Tested up to WooCommerce version
> -- | --
> WooCommerce PayPal Checkout Gateway | 3.9

**Screenshots**
N/A

### Expected behavior
Able to upgrade without uncertainty of compatibility.

**Environment (please complete the following information):**
 - WordPress Version: 5.3.2
 - WooCommerce Version: 3.9.2
 - PayPal (Express) Checkout Plugin Version: 1.6.20
 - Browser [e.g. chrome, safari] and Version: Firefox 75.0b6 (64-bit)
 - Any other plugins installed: N/A (but if needed, I'll list them)

### Additional details
N/A

**Comment by dougaitken** [comment]
Can we bump `Tested up to` for WordPress as well on the next release, please @mattallan @LCmry ?
