### ISSUE TITLE
Check out without a PayPal account is not working.

### ISSUE THREAD

**Issue by dmhirschfeld** [woocommerce/woocommerce-gateway-paypal-express-checkout#716]
Pay with PayPal button works fine.  My problem is regarding "Allow customers to checkout without a PayPal Account." setting:

I am getting an error when I or a customer does the following:

Click on a credit card icon:
![image](https://user-images.githubusercontent.com/11728650/79610574-a427f100-80ad-11ea-99b2-cc90a440dac9.png)

Fill in this form CORRECTLY with a perfectly good credit card:
![image](https://user-images.githubusercontent.com/11728650/79610703-e8b38c80-80ad-11ea-9bce-4979a474ef9c.png)

I have done this several time with several credit cards.  It is absolutely not the cards or the data entry.  I get this error:

![image](https://user-images.githubusercontent.com/11728650/79610928-519b0480-80ae-11ea-9935-7e8032c143cb.png)

Clicking "Try Again" opens this popup

![image](https://user-images.githubusercontent.com/11728650/79611339-3aa8e200-80af-11ea-919c-5e8c9819cc3b.png)

Which results in this:
![image](https://user-images.githubusercontent.com/11728650/79611116-b5253200-80ae-11ea-90b3-bb68b0ec4dfc.png)

This was first reported by a customer who was the first to use this feature.

**Comment by jrick1229** [comment]
@dmhirschfeld - this repo isn't for support, so please either fill out a ticket in your [WooCommerce account dashboard](https://woocommerce.com/my-account/create-a-ticket/) or create a thread in the [PayPal Checkout support forum](https://wordpress.org/plugins/woocommerce-gateway-paypal-express-checkout/).
