### ISSUE TITLE
Wrong locale function 'get_paypal_locale()'

### ISSUE THREAD

**Issue by AmeenJalali** [woocommerce/woocommerce-gateway-paypal-express-checkout#721]
### Describe the bug
Our website is based in Australia. When we changed the landing page from login (PayPal account) to billing (Non-PayPal account), after clicking on PayPal smart button on the checkout page, we redirect to PayPal link like:

sandbox.paypal.com/checkoutnow?locale.x=en_US&fundingSource=paypal&sessionID=f542d1d07e_mdsdjy6mzm&buttonSessionID=83529fa81e_msd26mjc6mja&env=sandbox&fundingOffered=paypal&logLevel=warn&sdkMeta=eyJ1cmwiOiJod2Rwczo123123asdaxxvYmplY3RzLfNvbS9hcGkvY2hs2tvdXQuan23D&uid=f0e347a45a&version=4&token=EC-9S631129131J&xcomponent=1#/checkout/guest

If you see, you can find out the `locale.x` set to en_US. This causes the default country on the PayPal website set to the USA and not Australia. Because [get_paypal_locale()](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/49416711ebd4fcc3f945853d2856e71b528a4392/includes/class-wc-gateway-ppec-settings.php#L304) function always returns US country as locale parameter in the URL and it's very bad for customers. They are forced to change the country.

### To reproduce

1. Change your woocommerce store location
1. Add products to cart, go to checkout and try to pay with PayPal
1. You can see the default country set to the USA and local.x parameter in the URL set to en_US

### Expected behavior

I expected when our store based in Australia, after clicking on the PayPal button, the default location on the PayPal website set to Australia, not the USA.

**Environment (please complete the following information):**
 - WordPress Version: 5.4
 - WooCommerce Version: 3.9.3
 - PayPal (Express) Checkout Plugin Version: 1.6.21

**Comment by james-allan** [comment]
Hi there @AmeenJalali.

What is your site's language set to in your WordPress settings?

That function you linked to, `get_paypal_locale()` only returns `en_US` if your store is based in the US, which doesn't apply to you, or your site's language isn't one that PayPal supports. 

When I checked on my local site, I found that if I set it to English (Australia), then `en_AU` is sent to PayPal. 

<img width="1108" alt="Screen Shot 2020-05-01 at 4 44 28 pm" src="https://user-images.githubusercontent.com/8490476/80787984-4d510a00-8bcb-11ea-88a0-59e8fe73117d.png">

Could you confirm what your site language is set to? You can find that setting in **Settings > General** from your WordPress dashboard.

**Comment by AmeenJalali** [comment]
Thanks for helping @james-allan, it works properly!

**Comment by mattallan** [comment]
Thanks @AmeenJalali, glad to hear it's working now :) Closing this out
