### ISSUE TITLE
Payment button disappears 

### ISSUE THREAD

**Issue by likellindil** [woocommerce/woocommerce-gateway-paypal-express-checkout#743]
### Describe the bug
The PayPal payment button disappears on both the cart page and the checkout page.
![1](https://user-images.githubusercontent.com/62890839/82885902-55a52680-9f78-11ea-8629-176b56dd6bc6.png)
![2](https://user-images.githubusercontent.com/62890839/82885907-56d65380-9f78-11ea-9bfb-587f520b4801.png)

**Environment (please complete the following information):**
WordPress Version 5.4.1
WooCommerce Version 4.1.1
WooCommerce PayPal Checkout Gateway Version 2.0.1
Browser [e.g. chrome, safari] Microsoft Edge 83.0.478.37 64bits

### Additional details
We noticed that the last update said it had been fixed.
However, it doesn't seem to work things out in our environment. 
All the cache has been purged after the update.

**Comment by mattallan** [comment]
Hey @likellindil, thanks for opening an issue for this and sorry about the trouble.

I'm unable to reproduce this on my own site so we'll need some more information to help diagnose why your PayPal buttons aren't loading.

Could you please go to the cart/checkout page where you expect to see the PayPal buttons and look in your browser console for any Javascript errors.

If you'd like us to take a look, please send us the URL of your store.

**Comment by likellindil** [comment]
Hello Matt,

Thanks for your response.
After visiting the website from several other devices, we found that only the one with VPN running had this issue.
After changing the VPN site, it works perfectly.

Sorry for wasting your time, thank you again for the great plugin.

Best regards,
Ken



Hey @likellindil<https://github.com/likellindil>, thanks for opening an issue for this and sorry about the trouble.

I'm unable to reproduce this on my own site so we'll need some more information to help diagnose why your PayPal buttons aren't loading.

Could you please go to the cart/checkout page where you expect to see the PayPal buttons and look in your browser console for any Javascript errors.

If you'd like us to take a look, please send us the URL of your store.
