### ISSUE TITLE
Button Size setting for Smart buttons on single product pages doesn't work

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce-gateway-paypal-express-checkout#748]
### Describe the bug

PayPal button size on single product pages is not changed according to Button Size setting.

### To reproduce

1. Enable Checkout on Single Product and change Button Size setting:

![https://d.pr/i/ihXFvX](https://d.pr/i/ihXFvX+) 
Full Size: https://d.pr/i/ihXFvX

2. PayPal button stays the same size for Small, Medium, Large.

This is Small button on my test site:

![https://d.pr/i/px5KYL](https://d.pr/i/px5KYL+) 
Full Size: https://d.pr/i/px5KYL

### Expected behavior

PayPal button on single product page to be changed according to the Button Size setting.

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - PayPal (Express) Checkout Plugin Version: 2.0.1
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

Setting priority to High since it affects single product page layouts.

**Comment by james-allan** [comment]
Thanks @treibalen. 

I've been able to replicate this. From this [line in the code](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/2.0.1/assets/js/wc-gateway-ppec-smart-payment-buttons.js#L197), the new SDK buttons don't support custom button sizes. In the [PayPal doc that is linked there](https://developer.paypal.com/docs/checkout/integration-features/customize-button/#size), they recommend styling the container with css instead. 

So we will need to do that to be backwards compatible.
