### ISSUE TITLE
Debit or Credit Card payments - Mobile number is required

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce-gateway-paypal-express-checkout#770]
### Describe the bug

**Unrelated to pre 2.0 phone number required issues that were fixed.**

When using the Debit or Credit Card option to make a payment, the Mobile number field is required regardless of the plugin and Customizer settings being set to optional.

### To reproduce

1. Click the Debit or Credit card option on a product page
2. Click the mobile field, followed by any other field
3. Notice the required note

**Screenshots**
![https://d.pr/i/X781R9](https://d.pr/i/X781R9+)
Full Image: https://d.pr/i/X781R9

### Expected behavior

When the plugin is set to not require phone number, I would expect this field to be optional.  If the plugin settings don't apply to the Debit or Credit card fields, a note/tooltip, or documentation could clear it up.

**Environment (please complete the following information):**
 - WordPress Version - 5.5 Alpha
 - WooCommerce Version - 4.2.0
 - PayPal (Express) Checkout Plugin Version - 2.0.2
 - Browser [e.g. chrome, safari] and Version - Firefox latest
 - Any other plugins installed - No

**Comment by achyuthajoy** [comment]
Hey @mdmoore 

The `Require Phone Number` option or standard PayPal checkouts. It doesn't affect direct card payments and the form is populated by PayPal automatically. I didn't find any PayPal docs to disable the Mobile Number field, but will keep digging and update this thread if found. 

But based on your report it would be nice to add a alert indicating that the `Require Phone Number` feature doesn't apply to Direct Card Payments feature.

**Comment by achyuthajoy** [comment]
Hey @mdmoore based on PayPal Developer Documentation for Standard Card Fields, `mobile number` is a required field. If not provided by the plugin, the field will be displayed and cannot be turned off.

You can refer the documentation here - https://developer.paypal.com/docs/checkout/integration-features/standard-card-fields/

I'll close this issue for now, but feel free to re-open if if you have more questions.
