### ISSUE TITLE
PayPal Credit in the UK

### ISSUE THREAD

**Issue by philiprabbett** [woocommerce/woocommerce-gateway-paypal-express-checkout#782]
### Describe the bug
PayPal Credit has been available to users in the UK for some time now but this plugin doesn't allow non-US stores that are also not using US Dollar as the store currency to activate PayPal Credit.

### Expected behavior
PayPal Credit option in this plugin should be available to users outside of the US operating in a different currency to USD.

**Environment (please complete the following information):**
N/A

### Additional details
https://www.paypal.com/uk/webapps/mpp/paypal-virtual-credit
https://wordpress.org/support/topic/enable-paypal-credt-payments-in-the-uk/
https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/e6351c1f347443bffa39669a87a59f0a42202263/includes/functions.php#L78
#411

**Comment by jorgeatorres** [comment]
Merged into #787.
