### ISSUE TITLE
Allow stores to hide the BLIK alternative payment method

### ISSUE THREAD

**Issue by mattallan** [woocommerce/woocommerce-gateway-paypal-express-checkout#796]
### Describe the bug

Store managers from Poland cannot hide the BLIK payment method on checkout.
Discovered in slack: p1597873289104100-slack-CNXMMQBDW

### To reproduce

BLIK is [only available in Poland](https://developer.paypal.com/docs/checkout/integration-features/alternative-payment-methods/#availability), so here's how to reproduce this issue.

1. Set your stores currency in **WooCommerce > Settings > General** to `Polish złoty (zł)`
1. Set `$script_args['buyer-country'] = 'PL';` when loading the script to simulate a customer from Poland. Set this buyer-country code [here](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/f1f16de178cbf1d529deeaf574a52aca82a6e093/includes/class-wc-gateway-ppec-cart-handler.php#L555).
1. Load the checkout and notice BLIK: https://d.pr/i/nOwtbo

The issue is in our PayPal Checkout settings we don't have any option to hide this payment method: https://d.pr/i/99ubK4

### Expected behavior

`BLIK` should be listed in our Hide payment methods setting in **WooCommerce > Settings > Payments > PayPal Checkout**

**Comment by xTenNickxx** [comment]
can some1 help me, i cant remove blik from payment methods

**Comment by chickenn00dle** [comment]
Hey @xTenNickxx,

Sorry for the delayed reply. We've just merged a fix for this, which will be included in the next release. Thanks for your patience on this.
