### ISSUE TITLE
Paypal for woocomerce not working

### ISSUE THREAD

**Issue by manueljimenezm** [woocommerce/woocommerce-gateway-paypal-express-checkout#804]
I have 5 websites and the same happens in all of them, when updating to this new version 2.0.3 of paypal, the card payment form is not loaded.

When you click the button nothing happens, it is frozen and does not allow the customer to pay for the product.

I need to fix this. I have already tried it in different wordpress themes to rule out that it is the problem, but it does not work in any of them.

Site: stickercr.com

**Comment by jorgeatorres** [comment]
Hi @manueljimenezm!

Thanks for reaching out. I'm sorry you're having trouble with PayPal Checkout. I see you've already opened a forum thread [here](https://wordpress.org/support/topic/paypal-for-woocomerce-not-working/) asking the same question.
This repository is only for development and as such, I'm going to close this issue. That said, don't worry: someone should be replying to your forum post very soon.
