### ISSUE TITLE
"Billing Last name is a required field" Error during checkout via express checkout

### ISSUE THREAD

**Issue by farhadmn** [woocommerce/woocommerce-gateway-paypal-express-checkout#805]
I have installed Woocomerce Paypal Plugin, but I order a product from product page via express checkout button, I am getting in the checkout page the error "Billing Last name is a required field." Altough all informations are fetched from paypal. 

### To reproduce
1. Install "WooCommerce PayPal Checkout Gateway"
2. Try to order Products from Product Page via Paypal Express Button

**Environment (please complete the following information):**
 - WordPress Version: 5.5.1.
 - WooCommerce Version: 4.4.1 
 -  WooCommerce PayPal Checkout Gateway Version: 2.0.3

**Comment by chickenn00dle** [comment]
Thanks for the report @farhadmn!

I wasn't able to replicate this, but it seems this may be related to this issue: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/742#issuecomment-634445480

Could you confirm the points listed in that comment?

Additionally, I'll go ahead and close this issue so we can move the discussion to the above-linked issue.

Thank you!
