### ISSUE TITLE
Paypal Express checkout is hiding minimum order amount error message on Checkout page

### ISSUE THREAD

**Issue by thivapraba** [woocommerce/woocommerce-gateway-paypal-express-checkout#807]
I am using Paypal Express checkout, I am only having Paypal checkout on Checkout page also I am skipping the cart. I have minimum order amount Error messages based on Customer postcode input, this works fine for default Paypal checkout. But we prefer to use Paypal Express checkout. Paypal express won't let the user to enter Paypal page if the minimum order amount is not reached, that's perfectly working, but our custom message is not getting display, only alert mark and red line is appearing.

**Environment (please complete the following information):**
 - WordPress Version - 5.4.2
 - WooCommerce Version - Version 3.7.0
 - PayPal (Express) Checkout Plugin Version - Version 2.0.3
 - Browser [e.g. chrome, safari] and Version - Chrome

**Comment by jorgeatorres** [comment]
Merging this with #857 as it's the same issue.
