### ISSUE TITLE
Fatal error when product is no longer in catalog

### ISSUE THREAD

**Issue by Spreeuw** [woocommerce/woocommerce-gateway-paypal-express-checkout#826]
### Describe the bug
When a product is removed from the catalog, but an order with this product is still pending payment and attempted to be paid for by PayPal express, the gateway crashes.

### To reproduce
1. Create a temporary product
1. Create a manual order with this product
1. Remove the product from WooCommerce
1. Try to pay for the order with PP Express

Error:

> Uncaught Error: Call to a member function get_sku() on bool in /wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-client.php:842

### Expected behavior
Product existence should be checked before attempting to call product methods, order should be able to be paid for.

**Environment (please complete the following information):**
 - WordPress Version 5.5
 - WooCommerce Version 4.6
 - PayPal (Express) Checkout Plugin Version 2.1.0

**Comment by Jany-M** [comment]
@jorgeatorres About the other issue I opened. The product is created in runtime, so it's not present at all times, but it is created virtually to be able to add it to a Woo order. This works fine when the SKU check is disabled (Woo is used by several themes and plugins just for its checkout, not for its products management).

**Comment by jorgeatorres** [comment]
@Jany-M: Thanks for the additional details. I'll be sure to include that scenario in my testing.

**Comment by jessLundie** [comment]
Also seen in 3665663-zen, breaking subscription renewals for products that no longer exist. @jorgeatorres, I set the priority of this to High given its potential impact on Subscriptions sites. 

Is there any kind of workaround or snippet we can give this customer in the meantime to disable this so their subscription renewals can process successfully?

**Comment by Spreeuw** [comment]
@jorgeatorres this is a serious issue that is super easy to fix, what's holdup?
