### ISSUE TITLE
Hide funding methods not working

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/woocommerce-gateway-paypal-express-checkout#828]
### Describe the bug
The hide funding methods option is not being respected

### To reproduce

1. Setup PayPal Checkout plugin
2. Set to hide credit and debit cards
3. Go to item page, see both buttons
4. Add item to cart and see both buttons on checkout page as well.

**Screenshots**
![](https://d.pr/i/S0DHXe+)Image Link: https://d.pr/i/S0DHXe

![](https://d.pr/i/s6wL25+)Image Link: https://d.pr/i/s6wL25

### Expected behavior
I expected the hide funding methods to work

**Environment (please complete the following information):**
 - WordPress Version 5.5.1
 - WooCommerce Version 4.6
 - PayPal (Express) Checkout Plugin Version 2.1.0

**Comment by jorgeatorres** [comment]
Hi @melindahelt!

I can't reproduce this. Your screenshot seems to be of the cart settings, which are also the default for the product and checkout pages **unless** you have "Configure settings specific to Single Product view" or "Configure settings specific to regular checkout" checked:

<img width="617" alt="Screen Shot 2020-10-16 at 15 20 31" src="https://user-images.githubusercontent.com/184724/96294925-80455980-0fc3-11eb-8e74-6e76d541c508.png">

Can you confirm those **aren't checked**? If they are, specific settings in those sections override the global ones.

**Comment by melindahelt** [comment]
Thanks! I think we both missed those... I checked them and then adjusted each one individually to hide and it's working for me now. Sorry about that!

**Comment by jorgeatorres** [comment]
@melindahelt: No problem. We know the settings screen is confusing 🙈. We have discussed plans to make it better but nothing concrete yet. I'm glad you were able to fix the problem on your end!
