### ISSUE TITLE
Question about custom data

### ISSUE THREAD

**Issue by QuentinSeptier** [woocommerce/woocommerce-gateway-paypal-express-checkout#831]
Hi,

My question refers to #175 

Is it still impossible to add custom fields to the paypal order? I would like to add a technical field that allows me to identify my customer in the CRM.

Thank you in advance,

Regards.

**Comment by chickenn00dle** [comment]
Hey @QuentinSeptier 👋 

> Is it still impossible to add custom fields to the paypal order?

That's correct. You can refer to the following comment for further explanation:
https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/175#issuecomment-289799449
