### ISSUE TITLE
embed paypal express checkout button block in the first line(in front of woocommerce-gutenberg-products-block) of the checkout page , failed with show up in the lower left footer , why ? ?

### ISSUE THREAD

**Issue by theGreaterBayArea** [woocommerce/woocommerce-gateway-paypal-express-checkout#833]
### Describe the bug
embed paypal express checkout button block in the first line(in front of woocommerce-gutenberg-products-block) of the checkout page , failed with show up in the lower left footer , why ? ?
### To reproduce

i need paypal express checkout button block in the first line(in front of woocommerce-gutenberg-products-block)
![shopify-checkout](https://user-images.githubusercontent.com/5503064/98195565-09193a80-1f5d-11eb-808a-fc3fb16667e9.jpg)

### Expected behavior
i need paypal express checkout button block in the first line(in front of woocommerce-gutenberg-products-block)

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - PayPal (Express) Checkout Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

### Additional details
![backend](https://user-images.githubusercontent.com/5503064/98195610-22ba8200-1f5d-11eb-8997-cde8646f2045.png)
![frontend](https://user-images.githubusercontent.com/5503064/98195616-264e0900-1f5d-11eb-8418-e55d284ea17a.png)

  
  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
</details>

**Comment by theGreaterBayArea** [comment]
so PayPal does not give a fork/f**k about this ?

**Comment by jorgeatorres** [comment]
Hi @linuxandroid-xyz!

Thanks for the report. I apologize for the delayed response. Sorry to hear you were having issues with this, but sadly, it is expected, given PayPal Express Checkout doesn't have support for the WooCommerce blocks.
With the latest versions of WC and WC blocks you shouldn't even see PayPal Express Checkout as an option.

We've recently released a new extension, [PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/), which includes several new features and includes support for the same Smart Payment Buttons that PayPal Express Checkout uses. While it doesn't support the checkout block right now, it is one of the planned features. As such, it is not likely that we'll update PayPal Express Checkout with support for the WooCommerce blocks in the near future.

That said, if you wanted to use Checkout right now with the blocks, you'd have to work on a custom integration, for which we can't really provide support. I could give you some general pointers should you need that.
