### ISSUE TITLE
500 internal error on all product pages

### ISSUE THREAD

**Issue by stylehaircare** [woocommerce/woocommerce-gateway-paypal-express-checkout#839]
After updating to the version 2.1.1 all the product pages are showing 500 internal server error. Kindly check - thank you

**Environment (please complete the following information):**
 - WordPress Version 5.5.3
 - WooCommerce Version 4.7.1
 - PayPal (Express) Checkout Plugin Version  2.1.0

**Comment by jessepearson** [comment]
@stylehaircare If you haven't been able to get this sorted, please submit a ticket in your WooCommerce.com account here: https://woocommerce.com/my-account/create-a-ticket/?form=ticket

Someone in support will then be able to assist you.
