### ISSUE TITLE
"Pay Later" button appears even if "Enable PayPal Credit messages" is unchecked

### ISSUE THREAD

**Issue by kosiew** [woocommerce/woocommerce-gateway-paypal-express-checkout#840]
### Describe the bug

"Pay Later" appears even if "Enable PayPal Credit messages" are unchecked.

### To reproduce

1. Go to WC > Settings > Payments > PayPal Checkout.
2. Make sure your setup is compatible with PayPal Credit and that it is enabled:
3. add_filter( 'woocommerce_paypal_express_checkout_sdk_script_args', function( $settings ) {
	$settings['buyer-country'] = 'US';
	return $settings;
} );
4. If your button is using the vertical layout, Credit should not be a hidden funding method. If the layout is horizontal, the "Enable PayPal Credit to eligible customers" must be unchecked.
5. Go to the frontend (single product page, cart or checkout) and I see the "Pay Later" button.

**Screenshots**

![Screenshot](https://d.pr/i/4KHCjf+)
*if image does not load, please click on this link  : https://d.pr/i/4KHCjf*

### Expected behavior

["Pay Later" should not be visible if "Enable PayPal Credit messages" is not checked.](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/811)

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - PayPal (Express) Checkout Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

### Additional details

<details><summary>System status</summary>
  
  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
`
### WordPress Environment ###

WordPress address (URL): https://wpstore101.wpcomstaging.com
Site address (URL): https://wpstore101.wpcomstaging.com
WC Version: 4.8.0
REST API Version: ✔ 4.8.0
WC Blocks Version: ✔ 3.8.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.7.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.25
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.73.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.21-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.8.0
WC Database Prefix: wp_
Total Database Size: 19.41MB
Database Data Size: 11.10MB
Database Index Size: 8.31MB
wp_woocommerce_sessions: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.19MB + Index: 0.16MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.28MB + Index: 0.28MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_cookie_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_groups_capability: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_groups_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_group_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_user_capability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_groups_user_group: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mclean_refs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mclean_scan: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.06MB + Index: 1.06MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 2.52MB + Engine InnoDB
wp_posts: Data: 0.42MB + Index: 0.13MB + Engine InnoDB
wp_redirection_404: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.14MB + Index: 0.19MB + Engine InnoDB
wp_terms: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_track_user_activity: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.41MB + Index: 0.59MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_recommendations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_session_activity: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 3.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 68
aw_workflow: 2
bookable_resource: 64
custom_css: 1
customize_changeset: 13
follow_up_email: 2
global_product_addon: 2
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
nav_menu_item: 15
oembed_cache: 2
order_shipment: 4
page: 28
post: 2
product: 95
product_variation: 99
qts_quote_request: 1
qts_scheduled_jobs: 3
revision: 48
shop_coupon: 10
shop_order: 101
shop_order_refund: 4
shop_subscription: 20
wc_booking: 20
wc_membership_plan: 2
wc_user_membership: 1
wcpf_item: 5
wcpf_project: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Code Snippets: by Code Snippets Pro – 2.14.0
Meks Quick Plugin Disabler: by Meks – 1.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WooCommerce: by Automattic – 4.8.0

### Inactive Plugins (99) ###

Advanced Product Quantity: by Addify – 1.0.6
Akismet Anti-Spam: by Automattic – 4.1.7
All-in-One WP Migration: by ServMask – 7.31
AMP: by AMP Project Contributors – 2.0.8
AutomateWoo: by WooCommerce – 5.1.3
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.5.7
Bookings Helper: by WooCommerce – 1.0.3 – Installed version not tested with active version of WooCommerce 4.0
Braintree for WooCommerce Payment Gateway: by WooCommerce – 2.4.3
Classic Editor: by WordPress Contributors – 1.6
CoBlocks: by GoDaddy – 2.5.3
Disable Real MIME Check: by Sergey Biryukov – 1.0
Facebook for WooCommerce: by Facebook – 2.2.0
Follow-Up Emails: by WooCommerce – 4.9.8 (update to version 4.9.9 is available)
Free Gifts for WooCommerce: by FantasticPlugins – 5.9
GDPR Cookies: by opmc – 1.1
Google Ads & Marketing by Kliken: by Kliken – 1.0.6
Groups: by itthinx – 2.11.1
Gutenberg: by Gutenberg Team – 9.5.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Homepage Control: by WooThemes – 2.0.3
Jetpack by WordPress.com: by Automattic – 9.2.1
Layout Grid: by Automattic – 1.3
Loco Translate: by Tim Whitlock – 2.4.6
Mailchimp for WooCommerce: by Mailchimp – 2.5.0
Media Cleaner: by Jordy Meow – 6.0.9
Page Optimize: by Automattic – 0.5.1
Paywall for WooCommerce: by TIV.NET INC – 2.3.0
Pressable Automated Migration: by Pressable – 4.35
Product Filters for WooCommerce: by WooCommerce – 1.2.3 (update to version 1.2.4 is available)
Query Monitor: by John Blackbourn – 3.6.5
Quote Request for WooCommerce: by FantasticPlugins – 1.5
reCaptcha for WooCommerce: by I Thirteen Web Solution – 2.1
Redirection: by John Godley – 4.9.2
Sensei LMS: by Automattic – 3.6.0
Storefront Blog Customiser: by WooCommerce – 1.3.0
Storefront Footer Bar: by WooThemes – 1.0.4
Storefront Hamburger Menu: by WooCommerce – 1.2.2
Storefront Mega Menus: by WooCommerce – 1.6.2 – Installed version not tested with active version of WooCommerce 4.0
Storefront Parallax Hero: by WooCommerce – 1.5.7
Storefront Powerpack: by WooCommerce – 1.5.0
Storefront Pricing Tables: by WooCommerce – 1.1.0
Storefront Product Sharing: by WooCommerce – 1.0.6
Storefront Reviews: by WooCommerce – 1.0.6 – Installed version not tested with active version of WooCommerce 4.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.42

User Role Editor: by Vladimir Garagulya – 4.57.1
WooCommerce Additional Variation Images: by WooCommerce – 1.7.26
WooCommerce Admin: by WooCommerce – 1.7.2
WooCommerce Advanced Ajax Layered Navigation: by WooCommerce – 1.4.26
WooCommerce Advanced Product Labels: by Jeroen Sormani – 1.1.7 – Installed version not tested with active version of WooCommerce 4.0
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.7
WooCommerce All Products For Subscriptions: by SomewhereWarm – 3.1.19 (update to version 3.1.20 is available)
WooCommerce Amazon Pay: by WooCommerce – 1.12.2
WooCommerce Blocks: by Automattic – 4.0.0
WooCommerce Bookings: by WooCommerce – 1.15.31
WooCommerce Bookings Availability: by WooCommerce – 1.1.16
WooCommerce Brands: by WooCommerce – 1.6.21 (update to version 1.6.22 is available)
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.31
WooCommerce Cart Add-Ons: by WooCommerce – 1.15.34
WooCommerce Chained Products: by StoreApps – 2.9.8 (update to version 2.9.9 is available)
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.38
WooCommerce Composite Products: by SomewhereWarm – 7.1.6
WooCommerce Currency Converter: by WooCommerce – 1.6.23
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.1.2 (update to version 5.2.0 is available)
WooCommerce Custom Thank You Pages: by Jeroen Sormani – 1.0.3 – Installed version not tested with active version of WooCommerce 4.0
WooCommerce Deposits: by WooCommerce – 1.5.6
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.22
WooCommerce FedEx Shipping: by WooCommerce – 3.4.33
WooCommerce Force Sells: by WooCommerce – 1.1.27
WooCommerce Gift Cards: by SomewhereWarm – 1.5.2 (update to version 1.5.3 is available)
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.25
WooCommerce Memberships: by SkyVerge – 1.19.2 (update to version 1.20.0 is available)
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.20
WooCommerce Mix and Match Products: by Kathy Darling – 1.10.0 (update to version 1.10.6 is available)
WooCommerce Payments: by Automattic – 1.7.1
WooCommerce PDF Product Vouchers: by SkyVerge – 3.8.1 (update to version 3.8.2 is available)
WooCommerce Points and Rewards: by WooCommerce – 1.6.38 (update to version 1.6.41 is available)
WooCommerce Pre-Orders: by WooCommerce – 1.5.29
WooCommerce Product Add-ons: by WooCommerce – 3.2.0 (update to version 3.3.0 is available)
WooCommerce Product Bundles: by SomewhereWarm – 6.6.0 (update to version 6.6.4 is available)
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.35 (update to version 1.10.38 is available)
WooCommerce Product Vendors: by WooCommerce – 2.1.45
WooCommerce Recommendation Engine: by Lucas Stark – 3.2.5
WooCommerce Shipping & Tax: by Automattic – 1.25.4
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.12
WooCommerce Ship to Multiple Addresses: by WooCommerce – 3.6.24 (update to version 3.6.25 is available)
WooCommerce Smart Coupons: by StoreApps – 4.12.2 (update to version 4.13.0 is available)
WooCommerce Stripe Gateway: by WooCommerce – 4.5.5
WooCommerce Subscriptions: by WooCommerce – 3.0.11
WooCommerce Subscriptions Gifting: by WooCommerce – 2.1.2
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.30
WooCommerce UPS Shipping: by WooCommerce – 3.2.27 (update to version 3.2.30 is available)
WooCommerce USPS Shipping: by WooCommerce – 4.4.49
WooCommerce Warranty Requests: by WooCommerce – 1.9.18 (update to version 1.9.20 is available)
WooCommerce Xero Integration: by WooCommerce – 1.7.32 (update to version 1.7.34 is available)
WordPress.com Editing Toolkit: by Automattic – 2.8.13
WP Crontrol: by John Blackbourn & crontributors – 1.8.5
WP Mail Logging: by MailPoet – 1.9.7
WP phpMyAdmin: by Puvox.software – 5.0.4.1
WP REST API: by WP REST API Team – 2.0-beta15

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
paywall (paywall)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #3843 - /checkout-page/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.7.0 (update to version 2.9.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 1
Oldest: 2020-11-30 00:17:42 +0000
Newest: 2020-11-30 00:17:42 +0000

Complete: 848
Oldest: 2020-11-14 00:09:42 +0000
Newest: 2020-12-14 03:07:20 +0000

Failed: 4
Oldest: 2020-11-27 04:56:52 +0000
Newest: 2020-12-02 03:44:29 +0000

Pending: 20
Oldest: 2020-12-14 22:00:00 +0000
Newest: 2021-08-27 09:05:35 +0000

`
</details>

**Comment by jorgeatorres** [comment]
Hi @kosiew,

Thanks the report. Unless I'm missing something from your setup, this seems to be the correct behavior.
"Enable Credit messages" doesn't control whether PayPal Credit (or Pay Later) is available as an option. That's the job of the "Hide Funding Methods" option.

The Credit messages checkbox controls whether banners with promotions related to PayPal Credit are displayed alongside the buttons. For example:

<img width="452" alt="93278721-d4c6a080-f79b-11ea-8617-2cba18ffd80e" src="https://user-images.githubusercontent.com/184724/102103048-42ba4c80-3e0b-11eb-8cec-570afaf151d4.png">

Disabling messages just hides the banners, not the Pay Later button itself. To do that, you'd have to add "PayPal Credit" as a hidden method. That said, if "PayPal Credit" is disabled, Credit messages are automatically disabled too.

Please let me know if I've missed something or if you feel we can make this clearer on the settings screen.

**Comment by kosiew** [comment]
HI @jorgeatorres ,
In [PR 811](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/811), it was the "Enable Credit messages" that controls whether PayPal Credit (or Pay Later) is displayed.

**Comment by jorgeatorres** [comment]
Hi @kosiew,

I don't recall that being the case. Why do you think that's the case?

**Comment by jorgeatorres** [comment]
To expand on that: funding methods (i.e. which buttons you see) are controlled by the "Hide funding methods" setting if the layout is set to "Vertical". For the horizontal layout we do display a checkbox to disable Credit specifically ("Enable PayPal Credit to eligible customers") but at no point "Enable Credit messages" had anything to do with the Credit/Pay Later button appearing or not.

Are you seeing different?

**Comment by kosiew** [comment]
@jorgeatorres ,

You are right.
Tested and hiding `PayPal Credit` does hide the button.

![Screenshot](https://d.pr/i/HMA5PO+)
*if image does not load, please click on this link  : https://d.pr/i/HMA5PO*

**Comment by jorgeatorres** [comment]
@kosiew: Thanks for confirming! 😃 Do let me know if you have a suggestion to make this clearer. Thanks again!

**Comment by alexlii1971** [comment]
> @jorgeatorres ,
> 
> You are right. Tested and hiding `PayPal Credit` does hide the button.
> 
> ![Screenshot](https://camo.githubusercontent.com/948e0006ad6c30b3c3d96490edd8a8580369c0f38193c60b81bbb1f093a4e6db/68747470733a2f2f642e70722f692f484d4135504f2b) _if image does not load, please click on this link : https://d.pr/i/HMA5PO_

Hello,

I face the same issue, and I can not disable Pyapal credit and pay later.
where is that screenshot from please? is that from Woocomerce native setting or by other plugin?

Thanks
