### ISSUE TITLE
Update the WC tested up to: numbers

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce-gateway-paypal-express-checkout#864]
### Describe the bug

This came from a customer.

>I want to update to 5.2.2 WooCommerce but receive a warning that WooCommerce PayPal Checkout Gateway is only tested up to 4.7

>This appears to be the official WooCommerce PayPal plugin but has not been updated for 5 months.

>Can you advise on how to proceed to maintain functionality and security of my site?

### To reproduce
1. Look at the `woocommerce-gateway-paypal-express-checkout.php` header to see where that's coming from. :P

**Screenshots**
![https://d.pr/i/JeUcHd](https://d.pr/i/JeUcHd+)
Image link: https://d.pr/i/JeUcHd

### Expected behavior
It would be updated to show the current version of WooCommerce.

**Comment by CJMcGregor** [comment]
Beyond just updating the version in this file- Is this plugin actually fully compatible with WooCommerce 5+ ? I would like to update my WooCommerce to 5+ but the fact that this Paypal plugin hasn't been updated in 6 months worries me. Is this still the go-to official paypal checkout plugin for WooCommerce or is there something else we should be using ?

**Comment by jorgeatorres** [comment]
@CJMcGregor: Hi! The plugin is fully compatible with WooCommerce 5+ and the latest WordPress. As for whether this is still the "go-to" PayPal plugin, we have recently released [PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/) which supports the newest stack from PayPal, including the Smart Payment Buttons currently in PayPal Checkout. Many more features are planned to be released, so we recommend you give this a try and, if it works for you, consider upgrading to PayPal Payments to ensure your site is future and feature proofed.

That said, PayPal Checkout is still being maintained and we will be releasing a new version very soon with some bug and compatibility fixes.
